project_id = "zwoainzzqhudmmknuycq"

[functions.create-team-member]
verify_jwt = false

[functions.get-user-last-access]
verify_jwt = false

[functions.restructure-novidade]
verify_jwt = false

[functions.restructure-process]
verify_jwt = false

[functions.sync-cadastros]
verify_jwt = false

[functions.sync-perdcomp]
verify_jwt = false

[functions.notify-ticket]
verify_jwt = false

[functions.dw-query]
verify_jwt = false

[functions.delete-team-member]
verify_jwt = false

[functions.check-ticket-deadlines]
verify_jwt = false

[functions.processar-procedimento]
verify_jwt = false

[functions.gerar-sintese-executiva]
verify_jwt = false

[functions.gerar-recomendacoes-pessoas]
verify_jwt = false

[functions.gerar-relatorio-individual]
verify_jwt = false