project_id = "zwoainzzqhudmmknuycq"

[functions.create-team-member]
verify_jwt = false

[functions.get-user-last-access]
verify_jwt = false

[functions.restructure-novidade]
verify_jwt = false

[functions.restructure-process]
verify_jwt = false

[functions.sync-cadastros]
verify_jwt = false

[functions.sync-perdcomp]
verify_jwt = false

[functions.notify-ticket]
verify_jwt = false