project_id = "zwoainzzqhudmmknuycq"

[functions.create-team-member]
verify_jwt = false

[functions.get-user-last-access]
verify_jwt = false

[functions.restructure-novidade]
verify_jwt = false

[functions.restructure-process]
verify_jwt = false
