import type { RoiProcesso } from '@/utils/roiCalculator';
import { dashboardRoiFmtBRL as fmtBRL, dashboardRoiFmtNum as fmtNum } from '@/lib/dashboardRoiModel';

export interface BarData { label: string; atual: number; otimizado: number }
export function BarChart({ data, modo = 'comparacao', valueFmt = fmtBRL }: { data: BarData[]; modo?: 'comparacao' | 'atual' | 'otimizado'; valueFmt?: (v: number) => string }) {
  const W = 1000, H = 220, padTop = 22, padBottom = 44, padX = 20;
  const innerW = W - padX * 2, innerH = H - padTop - padBottom;
  const showAtual = modo !== 'otimizado', showOtimizado = modo !== 'atual';
  const max = Math.max(1, ...data.flatMap(d => [showAtual ? d.atual : 0, showOtimizado ? d.otimizado : 0]));
  const grupoW = innerW / (data.length || 1), barCount = Number(showAtual) + Number(showOtimizado);
  const innerPad = 20, barGap = 6, barW = barCount > 0 ? (grupoW - innerPad - (barCount - 1) * barGap) / barCount : grupoW;
  return <div className="dashv2-chart"><div className="dashv2-chart-wrap" style={{ aspectRatio: `${W} / ${H}` }}>
    <svg viewBox={`0 0 ${W} ${H}`} preserveAspectRatio="xMidYMid meet" style={{ width: '100%', height: '100%' }}>
      {[0, .25, .5, .75, 1].map(p => <line key={p} x1={padX} x2={W-padX} y1={padTop+innerH*p} y2={padTop+innerH*p} stroke="#e2e8f0" strokeWidth="0.8" />)}
      {data.map((d, i) => { let x = padX+i*grupoW+innerPad/2; const nodes: React.ReactNode[] = [];
        if (showAtual) { const h=innerH*(d.atual/max); nodes.push(<g key="a"><rect x={x} y={padTop+innerH-h} width={barW} height={Math.max(h,.5)} fill="#94a3b8" rx="2" />{d.atual>0&&<text x={x+barW/2} y={padTop+innerH-h-5} fontSize="10" textAnchor="middle" fill="#475569" fontWeight="600">{valueFmt(d.atual)}</text>}</g>); x += barW+barGap; }
        if (showOtimizado) { const h=innerH*(d.otimizado/max); nodes.push(<g key="o"><rect x={x} y={padTop+innerH-h} width={barW} height={Math.max(h,.5)} fill="#0d9488" rx="2" />{d.otimizado>0&&<text x={x+barW/2} y={padTop+innerH-h-5} fontSize="10" textAnchor="middle" fill="#0f766e" fontWeight="600">{valueFmt(d.otimizado)}</text>}</g>); }
        return <g key={d.label}>{nodes}<text x={padX+i*grupoW+grupoW/2} y={padTop+innerH+18} fontSize="11" textAnchor="middle" fill="#334155" fontWeight="600">{d.label}</text></g>;
      })}<line x1={padX} x2={W-padX} y1={padTop+innerH} y2={padTop+innerH} stroke="#94a3b8" strokeWidth="1" />
    </svg></div>{modo==='comparacao'&&<div className="dashv2-legend"><span><i style={{background:'#94a3b8'}} /> Como Era</span><span><i style={{background:'#0d9488'}} /> Como Ficará</span></div>}</div>;
}

export interface HBarItem { label: string; valor: number; cor: string }
export function HBarChart({ items, valueFmt = fmtBRL }: { items: HBarItem[]; valueFmt?: (v:number)=>string }) {
  const max=Math.max(1,...items.map(i=>i.valor)); return <div className="dashv2-hbar">{items.map(it=><div key={it.label} className="dashv2-hbar-row"><div className="dashv2-hbar-label">{it.label}</div><div className="dashv2-hbar-track"><div className="dashv2-hbar-fill" style={{width:`${Math.min(100,it.valor/max*100)}%`,background:it.cor}} /></div><div className="dashv2-hbar-value">{valueFmt(it.valor)}</div></div>)}</div>;
}

export function ProjectionChart({ meses, investment, economiaMensal }: { meses:number; investment:number; economiaMensal:number }) {
  const W=1200,H=200,padTop=24,padBottom=30,padLeft=60,padRight=24,innerW=W-padLeft-padRight,innerH=H-padTop-padBottom,midY=padTop+innerH/2;
  const points=Array.from({length:meses+1},(_,m)=>({m,econ:m*economiaMensal,saldo:m*economiaMensal-investment}));
  const maxAbs=Math.max(investment,...points.map(p=>Math.abs(p.saldo)),1),x=(m:number)=>padLeft+(m/meses)*innerW,y=(v:number)=>midY-(v/maxAbs)*(innerH/2-6);
  const path=points.map((p,i)=>`${i?'L':'M'}${x(p.m).toFixed(1)},${y(p.econ).toFixed(1)}`).join(' '), investY=y(-investment), payback=economiaMensal>0&&investment>0?investment/economiaMensal:null;
  const ticks=Array.from({length:Math.min(meses,12)+1},(_,i)=>Math.round(i/Math.min(meses,12)*meses));
  return <div className="dashv2-chart"><div className="dashv2-chart-wrap" style={{aspectRatio:`${W} / ${H}`}}><svg viewBox={`0 0 ${W} ${H}`} preserveAspectRatio="xMidYMid meet" style={{width:'100%',height:'100%'}}><defs><linearGradient id="dashv2-area" x1="0" x2="0" y1="0" y2="1"><stop offset="0%" stopColor="#0d9488" stopOpacity="0.25"/><stop offset="100%" stopColor="#0d9488" stopOpacity="0"/></linearGradient></defs>
    <line x1={padLeft} x2={W-padRight} y1={midY} y2={midY} stroke="#cbd5e1" strokeWidth="0.8" strokeDasharray="4 4"/><text x={padLeft-8} y={midY+3.5} fontSize="10" fill="#94a3b8" textAnchor="end">Break-even</text>
    {investment>0&&<><line x1={padLeft} x2={W-padRight} y1={investY} y2={investY} stroke="#b91c1c" strokeWidth="1" strokeDasharray="6 4"/><text x={padLeft-8} y={investY+3.5} fontSize="10" fill="#b91c1c" textAnchor="end">Invest.</text><text x={padLeft+8} y={investY-5} fontSize="10" fill="#b91c1c" fontWeight="600">{fmtBRL(investment)}</text></>}
    {economiaMensal>0&&<><path d={`${path} L${W-padRight},${midY} L${padLeft},${midY} Z`} fill="url(#dashv2-area)"/><path d={path} stroke="#0d9488" strokeWidth="2" fill="none"/></>}
    {payback!=null&&payback>0&&payback<=meses&&<><line x1={x(payback)} x2={x(payback)} y1={padTop} y2={padTop+innerH} stroke="#b45309" strokeWidth="1"/><circle cx={x(payback)} cy={midY} r="3.5" fill="#b45309"/><text x={x(payback)+6} y={midY-6} fontSize="10" fill="#b45309" fontWeight="700">Payback {fmtNum(payback,0)}m</text></>}
    <line x1={padLeft} x2={W-padRight} y1={padTop+innerH} y2={padTop+innerH} stroke="#cbd5e1" strokeWidth="0.8"/>{ticks.map((m,i)=><g key={i}><line x1={x(m)} x2={x(m)} y1={padTop+innerH} y2={padTop+innerH+3} stroke="#cbd5e1" strokeWidth="0.8"/><text x={x(m)} y={padTop+innerH+14} fontSize="10" textAnchor="middle" fill="#94a3b8">{m}m</text></g>)}
  </svg></div><div className="dashv2-legend"><span><i style={{background:'#b91c1c'}}/> Investimento</span><span><i style={{background:'#0d9488'}}/> Economia acumulada</span><span><i style={{background:'#b45309'}}/> Payback</span></div></div>;
}

export function MaturityHeatmap({ processos }: { processos:RoiProcesso[] }) { const cols=[{key:'isMapeado',label:'Mapeado'},{key:'temDiagnostico',label:'Diagnóstico'},{key:'temCenarioFuturo',label:'Cenário Futuro'},{key:'temInvestimento',label:'Investimento'},{key:'implementado',label:'Implementado'}] as const;
  if(!processos.length)return <p className="dashv2-empty-row" style={{padding:16}}>Sem processos no escopo.</p>; return <div className="dashv2-heatmap" role="table" aria-label="Maturidade por processo"><div className="dashv2-heatmap-row dashv2-heatmap-head" role="row"><div className="dashv2-heatmap-proc" role="columnheader">Processo</div>{cols.map(c=><div key={c.key} className="dashv2-heatmap-cell" role="columnheader">{c.label}</div>)}</div>{processos.map(p=><div key={p.processoId} className="dashv2-heatmap-row" role="row"><div className="dashv2-heatmap-proc" role="cell" title={p.processoNome}>{p.processoNome}</div>{cols.map(c=>{const on=!!p.maturidade[c.key];return <div key={c.key} className={`dashv2-heatmap-cell ${on?'on':'off'}`} role="cell" aria-label={`${c.label}: ${on?'sim':'não'}`}>{on?'✓':'∅'}</div>})}</div>)}</div>;
}

export function WaterfallChart({custoAtual,economiaRealizada,economiaProjetada,custoFuturo}:{custoAtual:number;economiaRealizada:number;economiaProjetada:number;custoFuturo:number}) { const W=1000,H=240,padTop=26,padBottom=52,padX=30,innerH=H-padTop-padBottom,innerW=W-padX*2,max=Math.max(custoAtual,1),y=(v:number)=>padTop+innerH*(1-v/max),slot=innerW/4,barW=slot*.5; const cols=[{label:'Custo atual',base:0,top:custoAtual,cor:'#1e3a8a',val:custoAtual},{label:'− Realizada',base:custoAtual-economiaRealizada,top:custoAtual,cor:'#0d9488',val:economiaRealizada},{label:'− Potencial',base:custoFuturo,top:custoAtual-economiaRealizada,cor:'#5eead4',val:economiaProjetada},{label:'Custo futuro',base:0,top:custoFuturo,cor:'#475569',val:custoFuturo}]; return <div className="dashv2-chart"><div className="dashv2-chart-wrap" style={{aspectRatio:`${W} / ${H}`}}><svg viewBox={`0 0 ${W} ${H}`} preserveAspectRatio="xMidYMid meet" style={{width:'100%',height:'100%'}}>{[0,.25,.5,.75,1].map(p=><line key={p} x1={padX} x2={W-padX} y1={padTop+innerH*p} y2={padTop+innerH*p} stroke="#e2e8f0" strokeWidth="0.8"/>)}{cols.map((c,i)=>{const x=padX+i*slot+(slot-barW)/2,yt=y(c.top),h=Math.max(2,y(c.base)-yt),prev=cols[i-1];return <g key={c.label}>{i>0&&<line x1={padX+(i-1)*slot+(slot+barW)/2} x2={x} y1={y(prev.base)} y2={y(prev.base)} stroke="#cbd5e1" strokeWidth="0.8" strokeDasharray="3 3"/>}<rect x={x} y={yt} width={barW} height={h} fill={c.cor} rx="2"/><text x={x+barW/2} y={yt-6} fontSize="11" textAnchor="middle" fill="#334155" fontWeight="700">{fmtBRL(c.val)}</text><text x={x+barW/2} y={padTop+innerH+18} fontSize="11" textAnchor="middle" fill="#334155" fontWeight="600">{c.label}</text></g>})}<line x1={padX} x2={W-padX} y1={padTop+innerH} y2={padTop+innerH} stroke="#94a3b8" strokeWidth="1"/></svg></div><div className="dashv2-legend"><span><i style={{background:'#0d9488'}}/> Economia realizada</span><span><i style={{background:'#5eead4'}}/> Potencial restante</span></div></div> }
export function BulletChart({realizado,meta}:{realizado:number;meta:number}) { const max=Math.max(meta,realizado,1); return <div className="dashv2-bullet"><div className="dashv2-bullet-track"><div className="dashv2-bullet-fill" style={{width:`${Math.min(100,realizado/max*100)}%`}}/><div className="dashv2-bullet-meta" style={{left:`${Math.min(100,meta/max*100)}%`}} title={`Meta ${fmtBRL(meta)}`}/></div><div className="dashv2-bullet-labels"><span><i style={{background:'#0d9488'}}/> Realizado {fmtBRL(realizado)}</span><span>Meta {fmtBRL(meta)}</span></div></div> }
export function FunnelChart({items}:{items:HBarItem[]}) { const max=Math.max(1,...items.map(i=>i.valor)); return <div className="dashv2-funnel">{items.map(it=><div key={it.label} className="dashv2-funnel-row"><span className="dashv2-funnel-label">{it.label}</span><div className="dashv2-funnel-track"><div className="dashv2-funnel-bar" style={{width:`${it.valor>0?Math.max(8,it.valor/max*100):0}%`,background:it.cor}}/></div><span className="dashv2-funnel-val">{it.valor}</span></div>)}</div> }
