import { melhoriasRelacionadasAoGargalo, processoIdsDoGargalo } from '@/utils/gargaloMelhorias';
import { dica } from '@/utils/tooltips';
import { dashboardRoiFmtBRL as fmtBRL, dashboardRoiFmtNum as fmtNum, dashboardRoiFmtPct as fmtPct, dashboardRoiFmtPlain as fmtPlain } from '@/lib/dashboardRoiModel';
import { HBarChart } from '@/components/equipe/mapa/dashboard-roi/Charts';
import { EmptyRow, InsightCallout, KPICard, StorySection } from '@/components/equipe/mapa/dashboard-roi/Primitives';
import { useDashboardRoiSections } from '@/components/equipe/mapa/dashboard-roi/SectionContext';

export function DiagnosticSection(){const {v,horizonte,horizonteFator,periodoSufixo,topCategoria,custosCategoria,gargalosFiltrados,gargalosPorOrigem,processosFiltrados,melhorias,procNomeById,topEtapas}=useDashboardRoiSections();return <StorySection numero="3" titulo="Diagnóstico — Como Era" intro="O custo do status quo: este é o cenário antes das melhorias. Aqui estão as dores quantificadas em horas, dinheiro e erros — base para o business case da transformação.">
 <div className="dashv2-section-header"><h3>O custo de operar hoje</h3><span className="dashv2-section-sub">Visão financeira e de qualidade do estado atual</span></div><div className="dashv2-kpi-grid"><KPICard variant="highlight" label={`Custo Operacional ${periodoSufixo}`} valor={fmtBRL(v.custoAtualAno*horizonteFator)} hint={`${v.qtdProcessos} processos no escopo`} tooltip={dica('dashboard.kpi.custoAtual')}/><KPICard label={`Horas Alocadas ${periodoSufixo}`} valor={`${fmtNum(v.horasAtualAno*horizonteFator)} h`} hint={`${fmtNum(v.horasAtualAno/12)} h / mês`} tooltip={dica('dashboard.kpi.horasAtual')}/><KPICard label={`Custo de Retrabalho ${periodoSufixo}`} valor={fmtBRL(v.custosCategoria.retrabalho*horizonteFator)} hint="Tempo perdido refazendo" tooltip={dica('dashboard.kpi.custoRetrabalho')}/><KPICard variant="warning" label="Retrabalho" valor={fmtPct(v.taxaRetrabalhoAtual*100)} hint="% do tempo refazendo" tooltip={dica('dashboard.kpi.retrabalho')}/></div>
 <InsightCallout>{topCategoria&&topCategoria.atual>0?<>Maior frente de custo: <strong>{topCategoria.label}</strong> — {fmtBRL(topCategoria.atual)} de {fmtBRL(v.custoAtualAno*horizonteFator)} em {horizonte}m.</>:<>Custo do estado atual ainda não quantificado neste escopo.</>}</InsightCallout>
 <div className="dashv2-section-header"><h3>Onde o dinheiro é gasto (R$)</h3><span className="dashv2-section-sub">Composição do custo operacional atual — do maior para o menor</span></div><div className="dashv2-card"><HBarChart items={[...custosCategoria].map(c=>({label:c.label,valor:c.atual,cor:c.cor})).sort((a,b)=>b.valor-a.valor)} valueFmt={fmtPlain}/></div>
 <div className="dashv2-section-header"><h3>Panorama dos gargalos</h3><span className="dashv2-section-sub">Os pontos de fricção mapeados</span></div><div className="dashv2-kpi-grid"><KPICard variant="warning" label="Gargalos identificados" valor={fmtNum(v.qtdGargalos,0)} hint="Total catalogado no escopo"/><KPICard label="Gargalos endereçados" valor={`${gargalosFiltrados.filter(g=>melhoriasRelacionadasAoGargalo(g,melhorias).length>0).length} / ${v.qtdGargalos}`} hint="Já têm melhoria no mesmo processo"/><KPICard label="Processos afetados" valor={fmtNum(new Set(gargalosFiltrados.flatMap(g=>processoIdsDoGargalo(g))).size,0)} hint="Com ao menos um gargalo"/><KPICard label="Origens distintas" valor={fmtNum(gargalosPorOrigem.length,0)} hint="Cliente, Processo, Sistema…"/></div>
 <InsightCallout>Os gargalos são mapeados <strong>qualitativamente</strong> (origem, processos afetados e cobertura por melhorias). O custo quantitativo do estado atual vem das <strong>etapas</strong> (seção acima), que têm horas e responsáveis cadastrados.</InsightCallout>
 <div className="dashv2-grid2"><div><div className="dashv2-section-header"><h3>Gargalos por origem</h3><span className="dashv2-section-sub">De onde vem cada ponto de fricção</span></div><div className="dashv2-card">{gargalosPorOrigem.length===0?<p className="dashv2-empty-row" style={{padding:16}}>Nenhum gargalo cadastrado no escopo.</p>:<HBarChart items={[...gargalosPorOrigem].sort((a,b)=>b.valor-a.valor)} valueFmt={x=>`${fmtNum(x,0)}`}/>}</div></div><div><div className="dashv2-section-header"><h3>Gargalos por processo</h3><span className="dashv2-section-sub">Onde os pontos de fricção se concentram</span></div><div className="dashv2-card"><HBarChart items={processosFiltrados.map(p=>({label:p.name,valor:gargalosFiltrados.filter(g=>processoIdsDoGargalo(g).includes(p.id)).length,cor:'var(--accent-color)'})).filter(i=>i.valor>0).sort((a,b)=>b.valor-a.valor)} valueFmt={x=>`${fmtNum(x,0)}`}/></div></div></div>
 <div className="dashv2-section-header"><h3>Gargalos identificados</h3><span className="dashv2-section-sub">Ranqueados por nº de processos afetados</span></div><div className="dashv2-table-wrap"><table className="dashv2-table"><thead><tr><th>#</th><th>Gargalo</th><th>Processos afetados</th><th>Origem</th><th>Endereçado por melhoria</th></tr></thead><tbody>{gargalosFiltrados.length===0?<EmptyRow cols={5}/>: [...gargalosFiltrados].sort((a,b)=>processoIdsDoGargalo(b).length-processoIdsDoGargalo(a).length).slice(0,12).map((g,i)=>{const procs=processoIdsDoGargalo(g).map(id=>procNomeById.get(id)||id),ms=melhoriasRelacionadasAoGargalo(g,melhorias);return <tr key={g.id}><td>{i+1}</td><td>{g.nome}</td><td>{procs.length?procs.join(', '):'—'}</td><td>{g.origem||'—'}</td><td>{ms.length?ms.map(m=>m.improvement_description).join('; '):'—'}</td></tr>})}</tbody></table></div>
 <div className="dashv2-section-header"><h3>Etapas mais críticas</h3><span className="dashv2-section-sub">Top etapas por horas internas e custo</span></div><div className="dashv2-table-wrap"><table className="dashv2-table"><thead><tr><th>#</th><th>Etapa</th><th>Processo</th><th>Horas / Execução</th><th>Custo / Execução</th></tr></thead><tbody>{topEtapas.length===0?<EmptyRow cols={5}/>:topEtapas.map((e,i)=><tr key={e.id}><td>{i+1}</td><td>{e.nome}</td><td>{procNomeById.get(e.process_id)||'—'}</td><td>{fmtNum(e.horas)} h</td><td>{fmtBRL(e.custo)}</td></tr>)}</tbody></table></div>
</StorySection>}
