import HistoricoMedicoes from '@/components/equipe/mapa/HistoricoMedicoes';
import { fmtRoi } from '@/utils/roiGuards';
import { dashboardRoiDelta as delta, dashboardRoiDeltaPct as deltaPct, dashboardRoiFmtBRL as fmtBRL, dashboardRoiFmtNum as fmtNum, dashboardRoiFmtPct as fmtPct, dashboardRoiFmtPlain as fmtPlain } from '@/lib/dashboardRoiModel';
import { BarChart, BulletChart, FunnelChart, MaturityHeatmap, ProjectionChart, WaterfallChart } from '@/components/equipe/mapa/dashboard-roi/Charts';
import { InsightCallout, KPICard, StorySection } from '@/components/equipe/mapa/dashboard-roi/Primitives';
import { useDashboardRoiSections } from '@/components/equipe/mapa/dashboard-roi/SectionContext';

export function EvolutionSection(){const {v,horizonte,horizonteFator,periodoSlash,custosCategoria,statusMelhoriasFunnel,pctRealizado,roiDisp,roiHorizonteTxt,paybackTxt,filtroProcesso,procNomeById}=useDashboardRoiSections();return <StorySection numero="6" titulo="Evolução — Realizado vs Potencial" intro="Quanto do retorno mapeado já foi capturado (melhorias concluídas) e quanto ainda é potencial. À medida que as melhorias são implementadas, a economia migra de potencial para realizada.">
 <div className="dashv2-section-header"><h3>Retorno: realizado e potencial</h3><span className="dashv2-section-sub">O que já foi capturado vs o que ainda há a destravar</span></div><div className="dashv2-kpi-grid"><KPICard variant="highlight" label="Economia Realizada / ano" valor={fmtBRL(v.economiaRealizada)} hint={`${v.maturidade.implementados}/${v.maturidade.total} processos implementados`}/><KPICard label="Potencial restante / ano" valor={fmtBRL(v.economiaProjetada)} hint="A capturar com as melhorias"/><KPICard variant="highlight" label="ROI Realizado" valor={fmtRoi(v.roiRealizado)} positivo={v.roiRealizado!=null?v.roiRealizado>=0:undefined} hint="Economia ÷ investimento realizado"/><KPICard label="Maturidade do escopo" valor={`${v.maturidade.completudePct}%`} hint="Média das fases concluídas"/></div>
 <InsightCallout>{v.economiaAnual>0?<>Das <strong>{fmtBRL(v.economiaAnual)}</strong> de economia anual possível, <strong>{fmtBRL(v.economiaRealizada)}</strong> ({pctRealizado}%) já foram capturadas; restam <strong>{fmtBRL(v.economiaProjetada)}</strong> a destravar.</>:<>O cenário futuro ainda não foi desenhado neste escopo — a economia aparece quando as etapas tiverem o "como ficará".</>}</InsightCallout>
 <div className="dashv2-section-header"><h3>Ponte: do custo atual ao custo futuro</h3><span className="dashv2-section-sub">Economia já realizada vs potencial restante (por ano)</span></div><div className="dashv2-card"><WaterfallChart custoAtual={v.custoAtualAno} economiaRealizada={v.economiaRealizada} economiaProjetada={v.economiaProjetada} custoFuturo={v.custoFuturoAno}/></div>
 <div className="dashv2-section-header"><h3>Captura da economia</h3><span className="dashv2-section-sub">Realizado vs meta (economia potencial total)</span></div><div className="dashv2-card"><BulletChart realizado={v.economiaRealizada} meta={v.economiaAnual}/></div>
 <div className="dashv2-section-header"><h3>Entrega das melhorias</h3><span className="dashv2-section-sub">Status do plano de melhorias do escopo</span></div><div className="dashv2-card"><FunnelChart items={statusMelhoriasFunnel}/></div>
 <div className="dashv2-section-header"><h3>Maturidade por processo</h3><span className="dashv2-section-sub">Em que fase cada processo está</span></div><div className="dashv2-card"><MaturityHeatmap processos={v.porProcesso}/></div>
 <div className="dashv2-section-header"><h3>Custos por categoria — Como Era × Como Ficará (R$)</h3><span className="dashv2-section-sub">Comparação lado a lado por frente de custo</span></div><div className="dashv2-card"><BarChart data={custosCategoria.map(c=>({label:c.label,atual:c.atual,otimizado:c.otimizado}))} valueFmt={fmtPlain}/></div>
 <div className="dashv2-section-header"><h3>Horas e qualidade</h3><span className="dashv2-section-sub">Os outros eixos do ganho</span></div><div className="dashv2-card"><BarChart data={[{label:`Horas ${periodoSlash}`,atual:v.horasAtualAno*horizonteFator,otimizado:v.horasFuturoAno*horizonteFator},{label:'Retrabalho %',atual:v.taxaRetrabalhoAtual*100,otimizado:v.taxaRetrabalhoFuturo*100}]} valueFmt={fmtNum}/></div>
 <div className="dashv2-section-header"><h3>Curva do break-even</h3><span className="dashv2-section-sub">Quando o investment se paga</span></div><div className="dashv2-card"><ProjectionChart meses={horizonte} investment={v.investimentoTotal} economiaMensal={v.economiaMensal}/></div>
 <div className="dashv2-section-header"><h3>Comparativo final</h3><span className="dashv2-section-sub">Linha por linha do que muda</span></div><div className="dashv2-table-wrap"><table className="dashv2-table"><thead><tr><th>Indicador</th><th>Como Era</th><th>Como Ficará</th><th>Δ</th><th>%</th></tr></thead><tbody><tr><td>{`Custo ${periodoSlash}`}</td><td>{fmtBRL(v.custoAtualAno*horizonteFator)}</td><td>{fmtBRL(v.custoFuturoAno*horizonteFator)}</td><td>{fmtBRL(delta(v.custoAtualAno,v.custoFuturoAno)*horizonteFator)}</td><td>{fmtPct(deltaPct(v.custoAtualAno,v.custoFuturoAno))}</td></tr><tr><td>{`Horas ${periodoSlash}`}</td><td>{fmtNum(v.horasAtualAno*horizonteFator)} h</td><td>{fmtNum(v.horasFuturoAno*horizonteFator)} h</td><td>{fmtNum(delta(v.horasAtualAno,v.horasFuturoAno)*horizonteFator)} h</td><td>{fmtPct(deltaPct(v.horasAtualAno,v.horasFuturoAno))}</td></tr><tr><td>Retrabalho médio</td><td>{fmtPct(v.taxaRetrabalhoAtual*100)}</td><td>{fmtPct(v.taxaRetrabalhoFuturo*100)}</td><td>{fmtPct(delta(v.taxaRetrabalhoAtual,v.taxaRetrabalhoFuturo)*100)}</td><td>—</td></tr><tr className="dashv2-table-total"><td>Investimento</td><td colSpan={2}>{fmtBRL(v.investimentoTotal)}</td><td colSpan={2}>Pagamento único</td></tr></tbody></table></div>
 <div className="dashv2-section-header"><h3>Histórico de medições</h3><span className="dashv2-section-sub">{filtroProcesso?'Evolução das baselines de ROI salvas deste processo':'Selecione um processo no filtro acima para ver a evolução das medições'}</span></div><div className="dashv2-card">{filtroProcesso?<HistoricoMedicoes processId={filtroProcesso} processoNome={procNomeById.get(filtroProcesso)}/>:<p className="dashv2-empty-row" style={{padding:16}}>Selecione um processo no filtro <strong>Processo</strong> (acima) para ver o histórico de medições dele.</p>}</div>
 <div className="dashv2-quote dashv2-quote-final"><div className="dashv2-quote-mark">★</div><div className="dashv2-quote-body">{roiDisp?<>Recomendação: o investimento de <strong>{fmtBRL(v.investimentoTotal)}</strong> se paga em <strong>{paybackTxt}</strong> e gera ROI de <strong>{roiHorizonteTxt}</strong> em {horizonte} meses, além de liberar <strong>{fmtNum(v.horasLiberadas*horizonteFator)} horas</strong> da equipe no período para atividades de maior valor.</>:<>Já foram realizados <strong>{fmtBRL(v.economiaRealizada)}/ano</strong> de economia ({pctRealizado}% do potencial mapeado). ROI e payback serão consolidados quando o investimento das melhorias for informado.</>}</div></div>
</StorySection>}
