import { melhoriaIdsDoProcesso } from '@/utils/gargaloMelhorias';
import { dica } from '@/utils/tooltips';
import { dashboardRoiDeltaPct as deltaPct, dashboardRoiFmtBRL as fmtBRL, dashboardRoiFmtNum as fmtNum, dashboardRoiFmtPct as fmtPct, dashboardRoiFmtPlain as fmtPlain } from '@/lib/dashboardRoiModel';
import { HBarChart } from '@/components/equipe/mapa/dashboard-roi/Charts';
import { EmptyRow, InsightCallout, KPICard, StorySection } from '@/components/equipe/mapa/dashboard-roi/Primitives';
import { useDashboardRoiSections } from '@/components/equipe/mapa/dashboard-roi/SectionContext';

export function FutureSection(){const {v,horizonte,horizonteFator,periodoSufixo,custosCategoria,etapasFiltradas,responsaveis,melhorias,procNomeById}=useDashboardRoiSections();return <StorySection numero="5" titulo="Cenário Futuro — Como Ficará" intro="O estado projetado após implementadas todas as melhorias. Este é o novo patamar de eficiência da operação.">
 <div className="dashv2-section-header"><h3>A operação otimizada</h3><span className="dashv2-section-sub">Estado projetado após o plano de melhorias</span></div><div className="dashv2-kpi-grid"><KPICard variant="highlight" label={`Custo Operacional ${periodoSufixo}`} valor={fmtBRL(v.custoFuturoAno*horizonteFator)} hint={`Redução de ${fmtPct(deltaPct(v.custoAtualAno,v.custoFuturoAno))}`} tooltip={dica('dashboard.kpi.custoFuturo')}/><KPICard label={`Horas Alocadas ${periodoSufixo}`} valor={`${fmtNum(v.horasFuturoAno*horizonteFator)} h`} hint={`Liberadas: ${fmtNum(v.horasLiberadas*horizonteFator)} h`} tooltip={dica('dashboard.kpi.horasFuturo')}/><KPICard label={`Custo de Retrabalho ${periodoSufixo}`} valor={fmtBRL(v.custosCategoriaFicou.retrabalho*horizonteFator)} hint="Retrabalho residual" tooltip={dica('dashboard.kpi.custoRetrabalho')}/><KPICard label="Retrabalho" valor={fmtPct(v.taxaRetrabalhoFuturo*100)} hint="% do tempo refazendo" tooltip={dica('dashboard.kpi.retrabalho')}/></div>
 <InsightCallout>{v.custoFuturoAno<v.custoAtualAno?<>Redução projetada de custo: <strong>{fmtPct(deltaPct(v.custoAtualAno,v.custoFuturoAno))}</strong> · <strong>{fmtPlain(v.horasLiberadas*horizonteFator)} h</strong> liberadas em {horizonte}m.</>:<>Cenário futuro ainda não desenhado neste escopo (0 etapas com "como ficará").</>}</InsightCallout>
 <div className="dashv2-section-header"><h3>Nova distribuição de custos (R$)</h3><span className="dashv2-section-sub">Composição do custo otimizado — do maior para o menor</span></div><div className="dashv2-card"><HBarChart items={[...custosCategoria].map(c=>({label:c.label,valor:c.otimizado,cor:c.cor})).sort((a,b)=>b.valor-a.valor)} valueFmt={fmtPlain}/></div>
 <div className="dashv2-section-header"><h3>Etapas no novo fluxo</h3><span className="dashv2-section-sub">Visão otimizada por etapa</span></div><div className="dashv2-table-wrap"><table className="dashv2-table"><thead><tr><th>Etapa</th><th>Processo</th><th>Melhorias aplicadas ao processo</th><th>Horas / Execução</th><th>Custo / Execução</th></tr></thead><tbody>{etapasFiltradas.length===0?<EmptyRow cols={5}/>:etapasFiltradas.map(e=>{const exec=e.ficou?.executadoPor??e.executadoPor,horas=(exec||[]).reduce((s,r)=>s+(r.horas??0),0),medio=responsaveis.length?responsaveis.reduce((s,r)=>s+(r.hourly_rate||0),0)/responsaveis.length:0,ids=melhoriaIdsDoProcesso(melhorias,e.process_id),nomes=melhorias.filter(m=>ids.has(m.id)).map(m=>m.improvement_description).join(', ');return <tr key={e.id}><td>{e.name}</td><td>{procNomeById.get(e.process_id)||'—'}</td><td>{nomes||'—'}</td><td>{fmtNum(horas)} h</td><td>{fmtBRL(horas*medio)}</td></tr>})}</tbody></table></div>
</StorySection>}
