import { melhoriasRelacionadasAoGargalo } from '@/utils/gargaloMelhorias';
import { dica } from '@/utils/tooltips';
import { dashboardRoiFmtBRL as fmtBRL, dashboardRoiFmtNum as fmtNum, dashboardRoiFmtPlain as fmtPlain } from '@/lib/dashboardRoiModel';
import { HBarChart } from '@/components/equipe/mapa/dashboard-roi/Charts';
import { EmptyRow, InsightCallout, KPICard, StorySection } from '@/components/equipe/mapa/dashboard-roi/Primitives';
import { useDashboardRoiSections } from '@/components/equipe/mapa/dashboard-roi/SectionContext';

export function ImprovementsSection(){const {v,investimentoComposicao,statusMelhoriasFunnel,gargalosFiltrados,melhorias,sistemas,responsaveis}=useDashboardRoiSections();return <StorySection numero="4" titulo="As Melhorias Propostas" intro="O plano de ação: cada melhoria foi desenhada para resolver um ou mais gargalos identificados no diagnóstico. Aqui está o que será implementado e quanto custa.">
 <div className="dashv2-section-header"><h3>O plano em números</h3><span className="dashv2-section-sub">O investment necessário para alcançar o estado futuro</span></div><div className="dashv2-kpi-grid"><KPICard variant="highlight" label="Investimento Total" valor={fmtBRL(v.investimentoTotal)} hint="Pagamento único (CapEx)" tooltip={dica('dashboard.kpi.investment')}/><KPICard label="Melhorias Planejadas" valor={String(v.qtdMelhorias)} hint="Iniciativas catalogadas"/><KPICard label="Gargalos Atacados" valor={`${gargalosFiltrados.filter(g=>melhoriasRelacionadasAoGargalo(g,melhorias).length>0).length} / ${v.qtdGargalos}`} hint="Com melhoria no mesmo processo"/><KPICard label="Sistemas Novos" valor={String(v.qtdSistemasNovos)} hint="Internos, criados com as melhorias"/><KPICard label="Sistemas após melhorias" valor={`${v.qtdSistemas} → ${v.qtdSistemasAposMelhorias}`} hint="Atuais + novos sistemas internos"/></div>
 <InsightCallout><strong>{statusMelhoriasFunnel[3].valor}</strong> de <strong>{v.qtdMelhorias}</strong> melhorias concluídas · investimento total {fmtBRL(v.investimentoTotal)}{v.investimentoTotal===0?' (ainda não informado)':''}.</InsightCallout>
 <div className="dashv2-grid2"><div><div className="dashv2-section-header"><h3>Composição do investimento (R$)</h3><span className="dashv2-section-sub">Para onde vai cada real investido — do maior para o menor</span></div><div className="dashv2-card"><HBarChart items={[...investimentoComposicao].sort((a,b)=>b.valor-a.valor)} valueFmt={fmtPlain}/></div></div><div><div className="dashv2-section-header"><h3>De → Para: gargalo × melhoria</h3><span className="dashv2-section-sub">Quais melhorias resolvem cada gargalo</span></div><div className="dashv2-table-wrap"><table className="dashv2-table"><thead><tr><th>Gargalo</th><th>Melhoria(s) que resolve(m)</th><th>Status</th></tr></thead><tbody>{gargalosFiltrados.length===0?<EmptyRow cols={3}/>:gargalosFiltrados.map(g=>{const ms=melhoriasRelacionadasAoGargalo(g,melhorias);return <tr key={g.id}><td>{g.nome}</td><td>{ms.length?ms.map(m=>m.improvement_description).join('; '):'—'}</td><td>{ms.length?'Coberto':'Aberto'}</td></tr>})}</tbody></table></div></div></div>
 <div className="dashv2-section-header"><h3>Melhorias catalogadas</h3><span className="dashv2-section-sub">Lista completa com sistemas desenvolvidos e horas de implementação</span></div><div className="dashv2-table-wrap"><table className="dashv2-table"><thead><tr><th>Melhoria</th><th>Sistemas</th><th>Treinamento</th><th>Horas execução</th><th>Custo externo</th><th>Custo total</th></tr></thead><tbody>{melhorias.length===0?<EmptyRow cols={6}/>:melhorias.map(m=>{const sis=(m.sistemas||[]).map(id=>sistemas.find(s=>s.id===id)?.nome).filter(Boolean).join(', '),medio=responsaveis.length?responsaveis.reduce((s,r)=>s+(r.hourly_rate||0),0)/responsaveis.length:0,horas=(m.executadoPor||[]).reduce((s,r)=>s+(r.horas||0),0),exec=(m.executadoPor||[]).reduce((s,r)=>s+(r.horas||0)*((r.responsavelId&&responsaveis.find(x=>x.id===r.responsavelId)?.hourly_rate)||medio),0),total=(m.training_hours||0)*medio+exec+(m.one_time_external_cost||0);return <tr key={m.id}><td>{m.improvement_description}</td><td>{sis||'—'}</td><td>{fmtNum(m.training_hours||0)} h</td><td>{fmtNum(horas)} h</td><td>{fmtBRL(m.one_time_external_cost||0)}</td><td>{fmtBRL(total)}</td></tr>})}</tbody></table></div>
</StorySection>}
