import { dashboardRoiFmtNum as fmtNum, dashboardRoiFmtPlain as fmtPlain } from '@/lib/dashboardRoiModel';
import { HBarChart } from '@/components/equipe/mapa/dashboard-roi/Charts';
import { EmptyRow, InsightCallout, StatChip, StorySection } from '@/components/equipe/mapa/dashboard-roi/Primitives';
import { useDashboardRoiSections } from '@/components/equipe/mapa/dashboard-roi/SectionContext';

export function MappingSection(){const {v,horizonte,horizonteFator,periodoSufixo,topHorasProc,etapasFiltradas}=useDashboardRoiSections();return <StorySection numero="2" titulo="O Mapeamento" intro="O ponto de partida: para entender o que pode ser melhorado, mapeamos integralmente o escopo da operação — pessoas, processos, sistemas e documentos.">
  <div className="dashv2-section-header"><h3>Tamanho do escopo</h3><span className="dashv2-section-sub">O que foi catalogado</span></div><div className="dashv2-stat-grid"><StatChip label="Projetos" valor={v.qtdProjetos}/><StatChip label="Processos" valor={v.qtdProcessos}/>{v.emMapeamento.length>0&&<StatChip label="Em mapeamento" valor={v.emMapeamento.length} variant="warning"/>}<StatChip label="Etapas" valor={v.qtdEtapas} variant="highlight"/><StatChip label="Responsáveis" valor={v.qtdResponsaveis}/><StatChip label="Documentos" valor={v.qtdDocumentos}/><StatChip label="Sistemas" valor={v.qtdSistemas}/><StatChip label="Gargalos" valor={v.qtdGargalos} variant="warning"/></div>
  <InsightCallout>{topHorasProc?<>Processo de maior carga horária: <strong>{topHorasProc.processoNome}</strong> — {fmtPlain(topHorasProc.horasAnual*horizonteFator)} h em {horizonte}m. <strong>{v.maturidade.mapeados}/{v.maturidade.total}</strong> processos mapeados.</>:<>Sem processos no escopo.</>}{v.emMapeamento.length>0&&<> <strong>{v.emMapeamento.length}</strong> processo{v.emMapeamento.length>1?'s':''} em mapeamento (dados de ROI incompletos) {v.emMapeamento.length>1?'ficam':'fica'} fora do consolidado.</>}</InsightCallout>
  <div className="dashv2-section-header"><h3>Carga horária por processo (h)</h3><span className="dashv2-section-sub">Horas atuais por processo — do maior para o menor</span></div><div className="dashv2-card"><HBarChart items={[...v.porProcesso].map(p=>({label:p.processoNome,valor:p.horasAnual*horizonteFator,cor:'var(--accent-color)'})).sort((a,b)=>b.valor-a.valor)} valueFmt={fmtPlain}/></div>
  <div className="dashv2-section-header"><h3>Processos mapeados</h3><span className="dashv2-section-sub">Detalhamento por processo macro</span></div><div className="dashv2-table-wrap"><table className="dashv2-table"><thead><tr><th>Processo</th><th>Etapas</th><th>Documentos</th><th>Sistemas</th><th>Horas / Execução</th><th>{`Execuções ${periodoSufixo}`}</th></tr></thead><tbody>{v.porProcesso.length===0?<EmptyRow cols={6}/>:v.porProcesso.map(p=>{const ets=etapasFiltradas.filter(e=>e.process_id===p.processoId),docs=new Set(ets.flatMap(e=>[...(e.docsEntrada||[]).map(d=>d.documentoId||d.nome),...(e.docsSaida||[]).map(d=>d.documentoId||d.nome)])).size,sis=new Set(ets.flatMap(e=>e.sistemas||[])).size;return <tr key={p.processoId}><td>{p.processoNome}</td><td>{ets.length}</td><td>{docs}</td><td>{sis}</td><td>{fmtNum(p.horasPorExecucao)} h</td><td>{fmtNum(p.execucoesAnuais*horizonteFator,0)}</td></tr>})}</tbody></table></div>
</StorySection>}
