import { Tooltip } from '@/components/equipe/mapa/Tooltip';

type Variant = 'default' | 'highlight' | 'warning';
function MiniSparkline({points,color='#0d9488'}:{points:number[];color?:string}) { const max=Math.max(1,...points),W=80,H=24,path=points.map((v,i)=>`${i?'L':'M'}${i/Math.max(1,points.length-1)*W},${H-v/max*H}`).join(' '); return <svg viewBox={`0 0 ${W} ${H}`} className="dashv2-spark" preserveAspectRatio="none"><path d={path} stroke={color} strokeWidth="1.5" fill="none"/></svg> }
export function AlertChip({pct}:{pct:number}) { const level=pct>=67?'ok':pct>=34?'warn':'crit'; const glyph={ok:'🟢',warn:'🟡',crit:'🔴'}[level]; return <span className={`dashv2-alert-chip ${level}`} aria-label={`${pct}%`}>{glyph}</span> }
export function InsightCallout({children}:{children:React.ReactNode}) { return <div className="dashv2-callout"><span className="dashv2-callout-icon" aria-hidden>💡</span><p>{children}</p></div> }
export function KPICard({label,valor,variacao,positivo,hint,spark,size='md',tooltip,variant='default'}:{label:string;valor:string;variacao?:string;positivo?:boolean;hint?:string;spark?:number[];size?:'sm'|'md'|'lg';tooltip?:string;variant?:Variant}) { const cls=variant==='highlight'?' highlight':variant==='warning'?' warning':''; return <div className={`dashv2-kpi dashv2-kpi-${size}${cls}`}><div className="dashv2-kpi-label">{tooltip?<Tooltip text={tooltip}>{label}</Tooltip>:label}</div><div className="dashv2-kpi-valor">{valor}</div>{variacao&&<div className={`dashv2-kpi-var${positivo?' positivo':positivo===false?' negativo':''}`}>{variacao}</div>}{hint&&<div className="dashv2-kpi-hint">{hint}</div>}{spark&&<MiniSparkline points={spark}/>}</div> }
export function StatChip({label,valor,variant='default'}:{label:string;valor:string|number;variant?:Variant}) { const cls=variant==='highlight'?' highlight':variant==='warning'?' warning':''; return <div className={`dashv2-stat-chip${cls}`}><div className="dashv2-stat-valor">{valor}</div><div className="dashv2-stat-label">{label}</div></div> }
export function StorySection({numero,titulo,intro,children}:{numero:string;titulo:string;intro:string;children:React.ReactNode}) { return <section className="dashv2-story"><div className="dashv2-story-header"><div className="dashv2-story-num">{numero}</div><div><h2>{titulo}</h2><p>{intro}</p></div></div>{children}</section> }
export function EmptyRow({cols,msg='Sem dados — preencha o cadastro para visualizar.'}:{cols:number;msg?:string}) { return <tr><td colSpan={cols} className="dashv2-empty-row">{msg}</td></tr> }
