import { dica } from '@/utils/tooltips';
import { dashboardRoiFmtBRL as fmtBRL, dashboardRoiFmtNum as fmtNum } from '@/lib/dashboardRoiModel';
import { ProjectionChart } from '@/components/equipe/mapa/dashboard-roi/Charts';
import { InsightCallout, KPICard, StorySection } from '@/components/equipe/mapa/dashboard-roi/Primitives';
import { useDashboardRoiSections } from '@/components/equipe/mapa/dashboard-roi/SectionContext';

export function SummarySection() { const {v,horizonte,horizonteFator,periodoSufixo,economiaHorizonte,resultadoLiquidoHorizonte,roiDisp,roiHorizonte,roiHorizonteTxt,paybackTxt,topCustoProc}=useDashboardRoiSections(); return <StorySection numero="1" titulo="Sumário Executivo" intro="A apresentação completa em três linhas: o que mapeamos, o quanto o cenário atual custa, e qual o retorno do investment na transformação.">
  <div className="dashv2-kpi-grid"><KPICard variant="highlight" label={`Economia ${periodoSufixo}`} valor={fmtBRL(economiaHorizonte)} hint={`≈ ${fmtBRL(v.economiaMensal)} / mês`} tooltip={dica('dashboard.kpi.annual_savings')}/><KPICard variant="highlight" label="Retorno (ROI)" valor={roiHorizonteTxt} positivo={roiDisp?roiHorizonte>=0:undefined} hint={roiDisp?`Em ${horizonte} meses`:'Investimento não informado'} tooltip={dica('dashboard.kpi.roi')}/><KPICard label={`Resultado líquido (${horizonte}m)`} valor={fmtBRL(resultadoLiquidoHorizonte)} positivo={resultadoLiquidoHorizonte>=0} hint="Economia acum. − investment"/><KPICard label="Payback" valor={paybackTxt} hint="Tempo de recuperação" tooltip={dica('dashboard.kpi.payback')}/><KPICard label={`Horas Liberadas ${periodoSufixo}`} valor={`${fmtNum(v.horasLiberadas*horizonteFator)} h`} hint="Capacidade humana" tooltip={dica('dashboard.kpi.hours_freed')}/></div>
  <InsightCallout>{topCustoProc?<>Escopo <strong>{v.maturidade.completudePct}%</strong> modelado. Maior custo operacional hoje: <strong>{topCustoProc.processoNome}</strong> — {fmtBRL(topCustoProc.custoAnual*horizonteFator)} em {horizonte}m.</>:<>Nenhum processo no escopo selecionado.</>}</InsightCallout>
  <div className="dashv2-quote"><div className="dashv2-quote-mark">"</div><div className="dashv2-quote-body">{roiDisp?<>Investindo <strong>{fmtBRL(v.investimentoTotal)}</strong> no plano de melhorias, a operação passa a economizar <strong>{fmtBRL(economiaHorizonte)} em {horizonte} meses</strong>, com retorno do investment em <strong>{paybackTxt}</strong> — liberando <strong>{fmtNum(v.horasLiberadas*horizonteFator)} horas</strong> da equipe no período.</>:<>O escopo ainda está em construção: o cenário futuro e o investimento não foram totalmente informados, então <strong>ROI e payback aparecem como "em construção"</strong>. O custo operacional mapeado hoje é de <strong>{fmtBRL(v.custoAtualAno*horizonteFator)} em {horizonte} meses</strong> — base para o business case quando as melhorias forem desenhadas.</>}</div></div>
  <div className="dashv2-section-header"><h3>Projeção financeira</h3><span className="dashv2-section-sub">Investimento × economia acumulada ao longo dos próximos {horizonte} meses</span></div><div className="dashv2-card"><ProjectionChart meses={horizonte} investment={v.investimentoTotal} economiaMensal={v.economiaMensal}/></div>
</StorySection> }
