import { useEffect, useMemo, useRef, useState } from 'react';
import { Link } from 'react-router-dom';
import { useQueryClient } from '@tanstack/react-query';
import Select from '@/components/equipe/mapa/Select';
import Modal from '@/components/equipe/mapa/Modal';
import TourTrigger from '@/components/equipe/mapa/tour/TourTrigger';
import { NotasInfoButton, NotasMetodologicasModal } from '@/components/equipe/mapa/NotasMetodologicasModal';
import { Tooltip } from '@/components/equipe/mapa/Tooltip';
import { AlertChip } from '@/components/equipe/mapa/dashboard-roi/Primitives';
import { type DashboardRoiAggregate, type DashboardRoiSectionModel } from '@/components/equipe/mapa/dashboard-roi/SectionContext';
import { DashboardRoiSectionProvider } from '@/components/equipe/mapa/dashboard-roi/SectionProvider';
import { SummarySection } from '@/components/equipe/mapa/dashboard-roi/SummarySection';
import { MappingSection } from '@/components/equipe/mapa/dashboard-roi/MappingSection';
import { DiagnosticSection } from '@/components/equipe/mapa/dashboard-roi/DiagnosticSection';
import { ImprovementsSection } from '@/components/equipe/mapa/dashboard-roi/ImprovementsSection';
import { FutureSection } from '@/components/equipe/mapa/dashboard-roi/FutureSection';
import { EvolutionSection } from '@/components/equipe/mapa/dashboard-roi/EvolutionSection';
import type { MelhoriaStatus, ProjetoStatus, Sistema } from '@/types';
import { calcularRoi, execucoesAnuais, statusEconomiaProcesso } from '@/utils/roiCalculator';
import { roiDisponivel } from '@/utils/roiGuards';
import { gargalosDoProcesso, processoIdsDoGargalo } from '@/utils/gargaloMelhorias';
import { enrichEtapas } from '@/utils/enrichEtapas';
import { dica } from '@/utils/tooltips';
import { useClusterGlobal } from '@/hooks/useClusterGlobal';
import { useClusters } from '@/hooks/useClusters';
import { useProjetosLista, useProcessosLista, useEtapasLista, useResponsaveisLista, useSistemasLista, useGargalosLista, useMelhoriasLista, useDocumentosLista } from '@/hooks/useDominioListas';
import { fetchSnapshotsLatest, SNAPSHOTS_LATEST_QUERY_KEY, useSnapshotsLatest } from '@/hooks/useSnapshots';
import { buildRoiCsv, triggerCsvDownload } from '@/lib/roiCsv';
import type { SecaoImagem } from '@/lib/roiVisualExport';
import {
  DASHBOARD_ROI_ABAS as ABAS, DASHBOARD_ROI_ABA_STATUS_MIN as ABA_STATUS_MIN,
  DASHBOARD_ROI_MATURIDADE_OPCOES as MATURIDADE_OPCOES, DASHBOARD_ROI_STATUS_ORDEM as STATUS_ORDEM,
  dashboardRoiFmtNum as fmtNum, dashboardRoiFmtPct as fmtPct,
  type DashboardRoiAba as Aba, type DashboardRoiFiltroMaturidade as FiltroMaturidade,
} from '@/lib/dashboardRoiModel';

export default function DashboardRoiPage() {
  const [aba,setAba]=useState<Aba>('sumario');
  const {data:projetos=[]}=useProjetosLista(), {data:processos=[]}=useProcessosLista();
  const {data:rawEtapas=[]}=useEtapasLista(), {data:responsaveis=[]}=useResponsaveisLista();
  const {data:sistemas=[]}=useSistemasLista(), {data:gargalos=[]}=useGargalosLista();
  const {data:melhorias=[]}=useMelhoriasLista(), {data:documentos=[]}=useDocumentosLista();
  const {data:snapshotsLatest=[]}=useSnapshotsLatest(), queryClient=useQueryClient();
  const etapas=useMemo(()=>enrichEtapas(rawEtapas,documentos,sistemas,responsaveis),[rawEtapas,documentos,sistemas,responsaveis]);
  const {cluster:filtroCluster}=useClusterGlobal(); const {data:clusters=[]}=useClusters();
  const [filtroProjeto,setFiltroProjeto]=useState(''), [filtroProcesso,setFiltroProcesso]=useState('');
  const [filtroMaturidade,setFiltroMaturidade]=useState<FiltroMaturidade>('');
  const [horizonte,setHorizonte]=useState<12|24|36>(24), [exportando,setExportando]=useState(false), [exportOpen,setExportOpen]=useState(false), [notasOpen,setNotasOpen]=useState(false);
  const captureRef=useRef<HTMLDivElement>(null);
  const projetoAtivo=projetos.find(p=>p.id===filtroProjeto), clusterNome=clusters.find(c=>c.id===filtroCluster)?.nome;
  const tituloProjeto=projetoAtivo?.name||(filtroCluster&&clusterNome?`Visão Geral — ${clusterNome}`:'Visão Geral — Todos os projetos');
  const projetoStatus:ProjetoStatus=projetoAtivo?.status||'Mapeamento', statusIdx=STATUS_ORDEM.indexOf(projetoStatus);
  const clusterIdPorProjetoId=useMemo(()=>new Map(projetos.map(p=>[p.id,p.cluster_id||''])),[projetos]);
  const projetosDoCluster=useMemo(()=>filtroCluster?projetos.filter(p=>(p.cluster_id||'')===filtroCluster):projetos,[projetos,filtroCluster]);
  const processosFiltrados=useMemo(()=>{let arr=processos;if(filtroCluster)arr=arr.filter(p=>p.project_id&&clusterIdPorProjetoId.get(p.project_id)===filtroCluster);if(filtroProjeto)arr=arr.filter(p=>p.project_id===filtroProjeto);if(filtroProcesso)arr=arr.filter(p=>p.id===filtroProcesso);if(filtroMaturidade)arr=arr.filter(p=>{const ets=etapas.filter(e=>e.process_id===p.id);switch(filtroMaturidade){case'mapeado':return ets.length>0&&execucoesAnuais(p)>0;case'diagnosticado':return gargalosDoProcesso(gargalos,p.id).length>0||ets.some(e=>(e.error_rate??0)>0||(e.rework_rate??0)>0);case'futuro':return ets.some(e=>e.ficou!=null);case'implementado':return statusEconomiaProcesso(p,melhorias)==='realizado';default:return true}});return arr},[processos,filtroCluster,filtroProjeto,filtroProcesso,filtroMaturidade,clusterIdPorProjetoId,etapas,gargalos,melhorias]);
  const etapasFiltradas=useMemo(()=>{const ids=new Set(processosFiltrados.map(p=>p.id));return etapas.filter(e=>ids.has(e.process_id))},[etapas,processosFiltrados]);
  const gargalosFiltrados=useMemo(()=>{const ids=new Set(processosFiltrados.map(p=>p.id));return gargalos.filter(g=>processoIdsDoGargalo(g).some(id=>ids.has(id)))},[gargalos,processosFiltrados]);
  const latestDoEscopo=useMemo(()=>{const ids=new Set(processosFiltrados.map(p=>p.id));return snapshotsLatest.filter(s=>ids.has(s.process_id))},[snapshotsLatest,processosFiltrados]);
  const melhoriasDoEscopo=useMemo(()=>filtroCluster?melhorias.filter(m=>(m.cluster_id||'')===filtroCluster):melhorias,[melhorias,filtroCluster]);
  const sistemasDoEscopo=useMemo(()=>filtroCluster?sistemas.filter(s=>((s as unknown as {cluster_id?:string}).cluster_id||'')===filtroCluster):sistemas,[sistemas,filtroCluster]);
  const documentosDoEscopo=useMemo(()=>filtroCluster?documentos.filter(d=>((d as unknown as {cluster_id?:string}).cluster_id||'')===filtroCluster):documentos,[documentos,filtroCluster]);
  const v:DashboardRoiAggregate=useMemo(()=>{const agregado=calcularRoi({processos:processosFiltrados,etapas:etapasFiltradas,responsaveis,sistemas:sistemasDoEscopo,gargalos:gargalosFiltrados,melhorias:melhoriasDoEscopo,projetos});const novos=new Set(melhoriasDoEscopo.flatMap(m=>m.sistemas||[]));const atuais=sistemasDoEscopo.filter((s:Sistema)=>!novos.has(s.id)&&!novos.has(s.nome));return {...agregado,qtdProjetos:filtroProjeto?1:projetosDoCluster.length,qtdProcessos:processosFiltrados.length,qtdEtapas:etapasFiltradas.length,qtdGargalos:gargalosFiltrados.length,qtdMelhorias:melhoriasDoEscopo.length,qtdSistemas:atuais.length,qtdSistemasNovos:novos.size,qtdSistemasAposMelhorias:atuais.length+novos.size,qtdDocumentos:documentosDoEscopo.length,qtdResponsaveis:responsaveis.length}},[filtroProjeto,projetosDoCluster.length,processosFiltrados,etapasFiltradas,gargalosFiltrados,melhoriasDoEscopo,sistemasDoEscopo,documentosDoEscopo.length,responsaveis,projetos]);
  const horizonteFator=horizonte/12, periodoSufixo=horizonte===12?'/ Ano':`/ ${horizonte}m`, periodoSlash=horizonte===12?'/ ano':`/ ${horizonte}m`;
  const economiaHorizonte=v.economiaMensal*horizonte, resultadoLiquidoHorizonte=economiaHorizonte-v.investimentoTotal, roiDisp=roiDisponivel(v.investimentoTotal), roiHorizonte=roiDisp?economiaHorizonte/v.investimentoTotal*100:0;
  const roiHorizonteTxt=roiDisp?fmtPct(roiHorizonte):'em construção', paybackTxt=v.paybackMeses==null?'em construção':`${fmtNum(v.paybackMeses,0)} meses`;
  const limparFiltros=()=>{setFiltroProjeto('');setFiltroProcesso('');setFiltroMaturidade('')};
  const clusterAnterior=useRef(filtroCluster); useEffect(()=>{if(clusterAnterior.current===filtroCluster)return;clusterAnterior.current=filtroCluster;if(filtroCluster&&filtroProjeto&&clusterIdPorProjetoId.get(filtroProjeto)!==filtroCluster)setFiltroProjeto('');setFiltroProcesso('')},[filtroCluster,filtroProjeto,clusterIdPorProjetoId]);
  const handleExportCsv=async()=>{setExportando(true);try{const fresh=await queryClient.fetchQuery({queryKey:SNAPSHOTS_LATEST_QUERY_KEY as unknown as readonly unknown[],queryFn:fetchSnapshotsLatest,staleTime:0});const csv=buildRoiCsv({projetos,processos,snapshotsLatest:fresh,project_id:filtroProjeto||undefined});triggerCsvDownload(csv,filtroProjeto?`roi-${filtroProjeto}.csv`:'roi.csv')}finally{setExportando(false)}};
  const esperarPaint=(ms=380)=>new Promise<void>(res=>requestAnimationFrame(()=>window.setTimeout(res,ms)));
  const exportVisual=async(formato:'html'|'pdf')=>{setExportando(true);const original=aba,node=captureRef.current;try{const {capturarNodePng,montarHtml,montarPdf,baixarBlob}=await import('@/lib/roiVisualExport');if(document.fonts?.ready)try{await document.fonts.ready}catch{/* noop */}node?.classList.add('exporting');const secoes:SecaoImagem[]=[];let warmed=false;for(const a of ABAS){setAba(a.id);await esperarPaint();if(!captureRef.current)continue;if(!warmed){try{await capturarNodePng(captureRef.current)}catch{/* noop */}warmed=true}const img=await capturarNodePng(captureRef.current);secoes.push({label:a.label,...img})}const base=(filtroProjeto?`dashboard-roi-${tituloProjeto}`:'dashboard-roi').replace(/[^\w.-]+/g,'_');if(formato==='html'){const html=montarHtml(secoes,`${tituloProjeto} — Dashboard ROI`);baixarBlob(new Blob([html],{type:'text/html;charset=utf-8'}),`${base}.html`)}else await montarPdf(secoes,`${base}.pdf`)}finally{node?.classList.remove('exporting');setAba(original);setExportando(false);setExportOpen(false)}};
  const custosCategoria=[{label:'Pessoas',atual:v.custosCategoria.pessoas*horizonteFator,otimizado:v.custosCategoriaFicou.pessoas*horizonteFator,cor:'#1e3a8a'},{label:'Sistemas',atual:v.custosCategoria.sistemas*horizonteFator,otimizado:v.custosCategoriaFicou.sistemas*horizonteFator,cor:'#0d9488'},{label:'Retrabalho',atual:v.custosCategoria.retrabalho*horizonteFator,otimizado:v.custosCategoriaFicou.retrabalho*horizonteFator,cor:'#b45309'},{label:'Externo',atual:v.custosCategoria.externo*horizonteFator,otimizado:v.custosCategoriaFicou.externo*horizonteFator,cor:'#475569'}];
  const investimentoComposicao=[{label:'Treinamento (Melhorias)',valor:v.investimentoBreakdown.treinamentoMelhorias,cor:'#0d9488'},{label:'Execução de Melhorias',valor:v.investimentoBreakdown.execucaoMelhorias,cor:'#1e3a8a'},{label:'Custo Externo',valor:v.investimentoBreakdown.externo,cor:'#b45309'}];
  const statusMelhoriasFunnel=useMemo(()=>{const c:Record<MelhoriaStatus,number>={'Backlog':0,'Não iniciado':0,'Em progresso':0,'Concluído':0};for(const m of melhoriasDoEscopo){const s=(m.improvement_status as MelhoriaStatus)||'Não iniciado';if(s in c)c[s]++;else c['Não iniciado']++}return [{label:'Backlog',valor:c.Backlog,cor:'#94a3b8'},{label:'Não iniciado',valor:c['Não iniciado'],cor:'#b45309'},{label:'Em progresso',valor:c['Em progresso'],cor:'#1e3a8a'},{label:'Concluído',valor:c.Concluído,cor:'#0d9488'}]},[melhoriasDoEscopo]);
  const pctRealizado=v.economiaAnual>0?Math.round(v.economiaRealizada/v.economiaAnual*100):0, matPct=(n:number)=>v.maturidade.total?Math.round(n/v.maturidade.total*100):0;
  const matPorAba:Partial<Record<Aba,number>>={mapeamento:matPct(v.maturidade.mapeados),diagnostico:matPct(v.maturidade.comDiagnostico),futuro:matPct(v.maturidade.comCenarioFuturo),evolucao:matPct(v.maturidade.implementados)};
  const topCustoProc=[...v.porProcesso].sort((a,b)=>b.custoAnual-a.custoAnual)[0],topHorasProc=[...v.porProcesso].sort((a,b)=>b.horasAnual-a.horasAnual)[0],topCategoria=[...custosCategoria].sort((a,b)=>b.atual-a.atual)[0];
  const gargalosPorOrigem=useMemo(()=>{const map=new Map<string,number>();for(const g of gargalosFiltrados){const k=g.origem||'Outros';map.set(k,(map.get(k)||0)+1)}return [...map.entries()].map(([label,valor])=>({label,valor,cor:label==='Cliente'?'#1e3a8a':label==='Interno'||label==='Processo'?'#0d9488':label==='Externo'?'#b45309':label==='Sistema'?'#475569':label==='Pessoas'?'#047857':'#94a3b8'}))},[gargalosFiltrados]);
  const topEtapas=useMemo(()=>[...etapasFiltradas].map(e=>{const horas=(e.executadoPor||[]).reduce((s,r)=>s+(r.horas||0),0),medio=responsaveis.length?responsaveis.reduce((s,r)=>s+(r.hourly_rate||0),0)/responsaveis.length:0;return{id:e.id,nome:e.name,process_id:e.process_id,horas,custo:horas*medio}}).sort((a,b)=>b.horas-a.horas).slice(0,10),[etapasFiltradas,responsaveis]);
  const procNomeById=useMemo(()=>new Map(processos.map(p=>[p.id,p.name])),[processos]);
  const ultimaAtualizacao=useMemo(()=>{if(!latestDoEscopo.length)return'Hoje';const mais=latestDoEscopo.reduce((a,b)=>a.snapshot_at>b.snapshot_at?a:b),[y,m,d]=mais.snapshot_at.slice(0,10).split('-');return`${d}/${m}/${y}`},[latestDoEscopo]);
  const sectionModel:DashboardRoiSectionModel={v,horizonte,horizonteFator,periodoSufixo,periodoSlash,economiaHorizonte,resultadoLiquidoHorizonte,roiDisp,roiHorizonte,roiHorizonteTxt,paybackTxt,pctRealizado,topCustoProc,topHorasProc,topCategoria,custosCategoria,investimentoComposicao,statusMelhoriasFunnel,gargalosPorOrigem,topEtapas,etapasFiltradas,gargalosFiltrados,processosFiltrados,melhorias,sistemas,responsaveis,procNomeById,filtroProcesso};

  return <div className="dashv2">
    <div className="dashv2-hero"><div className="dashv2-hero-text"><div className="dashv2-hero-eyebrow">{projetoAtivo&&<span className="dashv2-fase-badge">Fase: {projetoStatus}</span>}<span className="dashv2-hero-update">Última atualização: {ultimaAtualizacao}</span></div><h1>{tituloProjeto}</h1><p>Esta apresentação percorre, em uma linha narrativa única, o caminho do projeto: o escopo mapeado, os gargalos diagnosticados, as melhorias propostas, o cenário futuro projetado e o retorno consolidado do investment.</p></div><div className="dashv2-hero-actions"><TourTrigger dataTour="help"/><NotasInfoButton onClick={()=>setNotasOpen(true)}/><button className="btn-secondary" onClick={()=>setExportOpen(true)} disabled={exportando} title="Exportar — escolha o formato (CSV, HTML ou PDF)" data-tour="roi-export"><svg viewBox="0 0 24 24" fill="none" stroke="currentColor" strokeWidth="2" strokeLinecap="round" strokeLinejoin="round"><path d="M21 15v4a2 2 0 0 1-2 2H5a2 2 0 0 1-2-2v-4"/><polyline points="7 10 12 15 17 10"/><line x1="12" y1="15" x2="12" y2="3"/></svg>{exportando?'Exportando…':'Exportar'}</button><Link to={filtroProjeto?`/equipe/digital/mapa/processos?focus=${encodeURIComponent(filtroProjeto)}`:'/equipe/digital/mapa/processos'} className="btn-primary" style={{textDecoration:'none',display:'inline-flex',alignItems:'center',gap:6,padding:'9px 16px',borderRadius:8,fontSize:'.85rem',fontWeight:600,background:'#0d9488',color:'#fff',border:'1px solid #0d9488'}}><svg viewBox="0 0 24 24" fill="none" stroke="currentColor" strokeWidth="2" strokeLinecap="round" strokeLinejoin="round"><path d="M11 4H4a2 2 0 0 0-2 2v14a2 2 0 0 0 2 2h14a2 2 0 0 0 2-2v-7"/><path d="M18.5 2.5a2.121 2.121 0 0 1 3 3L12 15l-4 1 1-4 9.5-9.5z"/></svg>Editar Escopo</Link></div></div>
    <NotasMetodologicasModal isOpen={notasOpen} onClose={()=>setNotasOpen(false)} escopo="dashboard"/>
    <Modal isOpen={exportOpen} onClose={()=>setExportOpen(false)}><div className="modal" style={{maxWidth:460,width:'100%'}}><h2 style={{margin:'0 0 4px',fontSize:'1.15rem',color:'#0f172a'}}>Exportar Dashboard ROI</h2><p style={{color:'#64748b',fontSize:'.84rem',margin:'0 0 16px',lineHeight:1.45}}>Escolha o formato. O <strong>CSV</strong> traz os dados consolidados por processo (Ferramenta C); <strong>HTML</strong> e <strong>PDF</strong> capturam a apresentação visual — todas as seções, com os gráficos.</p><div style={{display:'flex',flexDirection:'column',gap:10}}>{([{fmt:'csv',titulo:'CSV',sub:'Dados consolidados por processo',icone:<path d="M3 3h18v18H3z M3 9h18 M3 15h18 M9 3v18 M15 3v18"/>},{fmt:'html',titulo:'HTML',sub:'Apresentação visual (com gráficos)',icone:<><polyline points="16 18 22 12 16 6"/><polyline points="8 6 2 12 8 18"/></>},{fmt:'pdf',titulo:'PDF',sub:'Apresentação visual (com gráficos)',icone:<><path d="M14 2H6a2 2 0 0 0-2 2v16a2 2 0 0 0 2 2h12a2 2 0 0 0 2-2V8z"/><polyline points="14 2 14 8 20 8"/></>} ] as const).map(opt=><button key={opt.fmt} type="button" disabled={exportando} onClick={()=>{if(opt.fmt==='csv'){setExportOpen(false);void handleExportCsv()}else void exportVisual(opt.fmt)}} style={{display:'flex',alignItems:'center',gap:12,width:'100%',padding:'12px 14px',border:'1px solid #e2e8f0',borderRadius:10,background:'#fff',textAlign:'left',cursor:exportando?'default':'pointer',opacity:exportando?.55:1}}><span style={{display:'inline-flex',width:36,height:36,flex:'0 0 36px',alignItems:'center',justifyContent:'center',borderRadius:8,background:'#f1f5f9',color:'#0d9488'}}><svg width="18" height="18" viewBox="0 0 24 24" fill="none" stroke="currentColor" strokeWidth="2" strokeLinecap="round" strokeLinejoin="round">{opt.icone}</svg></span><span style={{display:'flex',flexDirection:'column',gap:2}}><span style={{fontWeight:600,color:'#0f172a',fontSize:'.9rem'}}>{opt.titulo}</span><span style={{fontSize:'.78rem',color:'#64748b'}}>{opt.sub}</span></span></button>)}</div>{exportando&&<p style={{marginTop:14,marginBottom:0,fontSize:'.82rem',color:'#0d9488',display:'flex',alignItems:'center',gap:8}}><span className="dashv2-spinner" aria-hidden style={{width:14,height:14,border:'2px solid #99f6e4',borderTopColor:'#0d9488',borderRadius:'50%',display:'inline-block',animation:'spin .7s linear infinite'}}/>Gerando… percorrendo as seções e capturando os gráficos.</p>}</div></Modal>
    <div className="dashv2-filters" data-tour="roi-filtros"><div className="dashv2-filter"><label><Tooltip text={dica('dashboard.filtro.projeto')}>Projeto</Tooltip></label><Select value={filtroProjeto} onChange={setFiltroProjeto} options={[{value:'',label:'Todos os projetos'},...projetosDoCluster.map(p=>({value:p.id,label:p.name}))]} placeholder="Selecione..."/></div><div className="dashv2-filter"><label><Tooltip text={dica('dashboard.filtro.processo')}>Processo</Tooltip></label><Select value={filtroProcesso} onChange={setFiltroProcesso} options={[{value:'',label:'Todos os processos'},...processosFiltrados.map(p=>({value:p.id,label:p.name}))]} placeholder="Todos os processos"/></div><div className="dashv2-filter"><label>Fase / Maturidade</label><Select value={filtroMaturidade} onChange={v=>setFiltroMaturidade(v as FiltroMaturidade)} options={MATURIDADE_OPCOES} placeholder="Todas as fases"/></div><div className="dashv2-filter"><label><Tooltip text={dica('dashboard.filtro.horizonte')}>Horizonte</Tooltip></label><div className="dashv2-segment"><button className={horizonte===12?'active':''} onClick={()=>setHorizonte(12)}>12m</button><button className={horizonte===24?'active':''} onClick={()=>setHorizonte(24)}>24m</button><button className={horizonte===36?'active':''} onClick={()=>setHorizonte(36)}>36m</button></div></div><button className="dashv2-filter-clear" onClick={limparFiltros}>Limpar</button></div>
    <div className="dashv2-pagenav" data-tour="roi-stepper"><div className="dashv2-pagenav-head"><span className="dashv2-pagenav-eyebrow">Páginas do relatório · {ABAS.findIndex(x=>x.id===aba)+1}/{ABAS.length} — clique para navegar</span><span className="dashv2-pagenav-mat">Maturidade do escopo: <strong>{v.maturidade.completudePct}%</strong></span></div><div className="dashv2-tabs" role="tablist">{ABAS.map(a=>{const mat=matPorAba[a.id],fasePrevia=!projetoAtivo||STATUS_ORDEM.indexOf(ABA_STATUS_MIN[a.id])<=statusIdx;return <button key={a.id} role="tab" aria-selected={aba===a.id} className={`dashv2-tab${aba===a.id?' active':''}${fasePrevia?'':' pendente'}`} onClick={()=>setAba(a.id)} title={fasePrevia?a.subtitulo:`${a.subtitulo} — dados completos quando o projeto chegar nesta fase`}><span className="dashv2-tab-num">{a.numero}</span><span className="dashv2-tab-text"><span className="dashv2-tab-label">{a.label}</span><span className="dashv2-tab-sub">{a.subtitulo}</span></span>{mat!=null&&<span className="dashv2-tab-mat"><AlertChip pct={mat}/> {mat}%</span>}</button>})}</div></div>
    <DashboardRoiSectionProvider value={sectionModel}><div className="dashv2-content" ref={captureRef}>{aba==='sumario'&&<SummarySection/>}{aba==='mapeamento'&&<MappingSection/>}{aba==='diagnostico'&&<DiagnosticSection/>}{aba==='melhorias'&&<ImprovementsSection/>}{aba==='futuro'&&<FutureSection/>}{aba==='evolucao'&&<EvolutionSection/>}</div></DashboardRoiSectionProvider>
    <footer style={{marginTop:32,paddingTop:16,paddingBottom:48,borderTop:'1px solid #e2e8f0',textAlign:'center',fontSize:'.8rem',color:'#64748b'}}>Última atualização: {ultimaAtualizacao}</footer>
  </div>;
}
