// Descrições oficiais dos CFOPs (Convênio s/nº de 1970, com alterações).
// O endpoint /api/v1/saida_icms/resumo_cfop devolve apenas o código numérico,
// então mantemos aqui o lookup para exibição. Códigos não mapeados caem no
// fallback "—".

export const CFOP_DESCRIPTIONS: Record<number, string> = {
  // 1xxx — Entradas/aquisições estaduais
  1101: 'Compra para industrialização ou produção rural',
  1116: 'Compra p/ industrialização originada de encomenda para recebimento futuro',
  1201: 'Devolução de venda de produção do estabelecimento',
  1407: 'Compra p/ uso ou consumo, mercadoria sujeita ao regime de ST',
  1410: 'Devolução de venda de produção, mercadoria sujeita ao regime de ST',
  1551: 'Compra de bem para o ativo imobilizado',
  1554: 'Devolução de venda de bem do ativo imobilizado',
  1556: 'Compra de material para uso ou consumo',
  1653: 'Compra de combustível ou lubrificante por consumidor ou usuário final',
  1905: 'Entrada de mercadoria recebida com fim específico de exportação',
  1908: 'Entrada de bem por conta de contrato de comodato',
  1910: 'Entrada de bonificação, doação ou brinde',
  1912: 'Entrada de mercadoria ou bem recebido para demonstração',
  1916: 'Retorno de remessa de mercadoria ou bem para industrialização',
  1921: 'Retorno de vasilhame ou sacaria',
  1922: 'Simples faturamento decorrente de compra para recebimento futuro',
  1949: 'Outra entrada de mercadoria ou prestação de serviço não especificada',

  // 2xxx — Entradas interestaduais
  2101: 'Compra para industrialização ou produção rural',
  2118: 'Compra de mercadoria pelo adquirente original em venda à ordem (armazém-geral)',
  2251: 'Compra de energia elétrica para distribuição ou comercialização',
  2406: 'Compra de bem para o ativo imobilizado, mercadoria sujeita ao regime de ST',
  2407: 'Compra para uso ou consumo, mercadoria sujeita ao regime de ST',
  2410: 'Devolução de venda de produção, mercadoria sujeita ao regime de ST',
  2503: 'Entrada de devolução de produto remetido com fim específico de exportação',
  2551: 'Compra de bem para o ativo imobilizado',
  2555: 'Devolução de transferência de bem do ativo imobilizado',
  2556: 'Compra de material para uso ou consumo',
  2908: 'Entrada de bem por conta de contrato de comodato',
  2910: 'Entrada de bonificação, doação ou brinde',
  2911: 'Entrada de amostra grátis',
  2912: 'Entrada de mercadoria ou bem recebido para demonstração',
  2916: 'Retorno de remessa de mercadoria ou bem para industrialização',
  2920: 'Entrada de vasilhame ou sacaria',
  2922: 'Simples faturamento decorrente de compra para recebimento futuro',
  2925: 'Retorno de mercadoria remetida para industrialização por encomenda',
  2949: 'Outra entrada de mercadoria ou prestação de serviço não especificada',

  // 5xxx — Saídas estaduais
  5101: 'Venda de produção do estabelecimento',
  5102: 'Venda de mercadoria adquirida ou recebida de terceiros',
  5116: 'Venda de produção do estabelecimento, originada de encomenda p/ entrega futura',
  5118: 'Venda de produção do estabelecimento entregue por conta e ordem (venda à ordem)',
  5401: 'Venda de produção, mercadoria sujeita a ST (contribuinte substituto)',
  5412: 'Devolução de compra para industrialização, mercadoria sujeita a ST',
  5551: 'Venda de bem do ativo imobilizado',
  5553: 'Devolução de compra de bem para o ativo imobilizado',
  5554: 'Remessa de bem do ativo imobilizado para uso fora do estabelecimento',
  5556: 'Devolução de compra de material de uso ou consumo',
  5652: 'Venda de combustível ou lubrificante de produção, destinada a não-contribuinte',
  5906: 'Retorno de mercadoria recebida em depósito',
  5909: 'Retorno de bem recebido por conta de contrato de comodato',
  5910: 'Remessa em bonificação, doação ou brinde',
  5912: 'Remessa de mercadoria ou bem para demonstração',
  5913: 'Retorno de mercadoria ou bem recebido para demonstração',
  5915: 'Remessa de mercadoria ou bem para conserto ou reparo',
  5920: 'Remessa de vasilhame ou sacaria',
  5922: 'Simples faturamento decorrente de venda para entrega futura',
  5923: 'Remessa por conta e ordem do adquirente original, em venda à ordem',
  5927: 'Baixa de estoque decorrente de perda, roubo ou deterioração',
  5933: 'Prestação de serviço tributado pelo ISSQN',
  5949: 'Outra saída de mercadoria ou prestação de serviço não especificado',

  // 6xxx — Saídas interestaduais
  6101: 'Venda de produção do estabelecimento',
  6102: 'Venda de mercadoria adquirida ou recebida de terceiros',
  6109: 'Venda de produção destinada à Zona Franca de Manaus ou Áreas de Livre Comércio',
  6120: 'Venda de mercadoria entregue ao destinatário pelo vendedor (venda à ordem)',
  6201: 'Devolução de compra para industrialização ou produção rural',
  6251: 'Venda de energia elétrica para distribuição ou comercialização',
  6413: 'Devolução de compra p/ comercialização, mercadoria sujeita a ST',
  6501: 'Remessa de produção do estabelecimento com fim específico de exportação',
  6551: 'Venda de bem do ativo imobilizado',
  6553: 'Devolução de compra de bem para o ativo imobilizado',
  6555: 'Devolução de bem do ativo imobilizado de terceiros recebido para uso',
  6556: 'Devolução de compra de material de uso ou consumo',
  6652: 'Venda de combustível ou lubrificante de produção, destinada a não-contribuinte',
  6909: 'Retorno de bem recebido por conta de contrato de comodato',
  6910: 'Remessa em bonificação, doação ou brinde',
  6913: 'Retorno de mercadoria ou bem recebido para demonstração',
  6915: 'Remessa de mercadoria ou bem para conserto ou reparo',
  6921: 'Retorno de vasilhame ou sacaria',
  6949: 'Outra saída de mercadoria ou prestação de serviço não especificado',
};

export const getCfopDescription = (cfop: number): string =>
  CFOP_DESCRIPTIONS[cfop] ?? '—';
