import type { FamiliaSaida } from '@/hooks/useSaidaIcms';

export const ICMS_PAGE_TOOLTIPS = {
  cliente: 'Cliente da consulta. Obrigatório.',
  contribuinte: 'Contribuinte da base.',
  start_date: 'Início do período das notas.',
  end_date: 'Fim do período das notas.',
  limparFiltros: 'Restaura os filtros.',
  buscar: 'Carrega os dados do período.',
  tabT01: 'Apuração e recolhimentos.',
  tabT02: 'Conciliação por CFOP.',
  tabT03_1: 'Saídas por família.',
  tabT03_2: 'Saídas com ST.',
} as const;

export const ICMS_FAMILIA_TAB_TOOLTIPS: Record<FamiliaSaida, string> = {
  acucar: 'Saídas de açúcar.',
  acucar_st: 'Saídas ST de açúcar.',
  etanol_interno: 'Saídas internas de etanol.',
  etanol_interestado: 'Saídas interestaduais de etanol.',
  etanol_interestado_st: 'Saídas ST de etanol interestadual.',
  residuos_producao: 'Saídas de resíduos.',
  sucata: 'Operações com sucata.',
  biodiesel: 'Saídas de biodiesel.',
};

export const ICMS_T01_TOOLTIPS = {
  periodo: 'Competência da apuração.',
  debitosSaidas: 'Débitos das saídas.',
  creditos: 'Créditos do período.',
  estornosDebito: 'Estornos de débito.',
  icmsRecolher: 'ICMS normal a recolher.',
  difal: 'DIFAL do período.',
  totalRecolhido: 'ICMS normal + DIFAL.',
  diferenca: 'Diferença da conferência.',
  matrizEfd: 'Valores da EFD.',
  matrizRecolhimentos: 'Valores recolhidos.',
  matrizCheck: 'Conferência final.',
  apurado: 'Valor apurado.',
  creditosMatriz: 'Créditos da matriz.',
  devido: 'Valor devido.',
  dar: 'Valor do DAR.',
  total: 'Total recolhido.',
  efdXRecolhido: 'EFD x recolhido.',
} as const;

export const ICMS_T02_TOOLTIPS = {
  cfop: 'CFOP da saída.',
  descricao: 'Descrição do CFOP.',
  vlItem: 'Valor do item.',
  bcIcms: 'Base do ICMS.',
  icms: 'Valor do ICMS.',
  pctIcms: 'Percentual do ICMS.',
} as const;

export const ICMS_T03_COLUMN_TOOLTIPS: Record<string, string> = {
  ID_CONTRIBUINTE: 'Contribuinte da linha.',
  MES_ANO: 'Competência da linha.',
  DATA_NOTA: 'Data da nota.',
  NUM_NOTA: 'Número da nota.',
  NUM_DOC: 'Número do documento.',
  CFOP: 'CFOP da operação.',
  CST_ICMS: 'CST do ICMS.',
  DESCRICAO_CFOP: 'Descrição do CFOP.',
  DESCRICAO_PRODUTO: 'Descrição do produto.',
  VALOR_MERCADORIA: 'Valor da mercadoria.',
  VL_MERCADORIA: 'Valor da mercadoria.',
  INCIDENCIA_ICMS: 'Incidência de ICMS.',
  BASE_CALCULO_ICMS: 'Base de cálculo.',
  ALIQUOTA: 'Alíquota aplicada.',
  ICMS_NORMAL: 'ICMS normal.',
  BENEFICIO: 'Benefício fiscal.',
  VALOR_CREDITO: 'Crédito fiscal.',
  ICMS_RECOLHER: 'ICMS a recolher.',
  CHECK_: 'Check principal.',
  FUNDES: 'Valor de FUNDES.',
  FUNDED: 'Valor de FUNDED.',
  FUNDEIC: 'Valor de FUNDEIC.',
  FUNDES_EFD: 'FUNDES na EFD.',
  FUNDED_EFD: 'FUNDED na EFD.',
  FUNDEIC_EFD: 'FUNDEIC na EFD.',
  QUANTIDADE: 'Quantidade da linha.',
  PMPF: 'PMPF aplicado.',
  PMPF_BC_REDUZIDA: 'PMPF reduzido.',
  pmpf_bc_reduzida: 'PMPF reduzido.',
  BC_CALCULADA: 'Base recalculada.',
  bc_calculada: 'Base recalculada.',
  ICMS_17_CALCULADO: 'ICMS a 17%.',
  icms_17_calculado: 'ICMS a 17%.',
  BC_ICMS_C190: 'Base no C190.',
  VL_ICMS_C190: 'ICMS no C190.',
  ICMS_12: 'ICMS a 12%.',
  VALOR_ICMS: 'Valor do ICMS.',
  CREDITO_OUTORGADO: 'Crédito outorgado.',
  ICMS_DEVIDO: 'ICMS devido.',
  EFD_C190_NF: 'NF do C190.',
  ADREM: 'Alíquota específica.',
  ICMS_17: 'ICMS a 17%.',
  CLASSIF: 'Classificação da linha.',
  C190_CHECK: 'Check do C190.',
  ICMS_C190_CHECK: 'Check do ICMS no C190.',
  ICMS_RECOLHER_E116_CHECK: 'Check E116 do ICMS a recolher.',
  ICMS_DEVIDO_E116_CHECK: 'Check E116 do ICMS devido.',
  FUNDES_E116_CHECK: 'Check E116 do FUNDES.',
  FUNDED_E116_CHECK: 'Check E116 do FUNDED.',
  FUNDEIC_E116_CHECK: 'Check E116 do FUNDEIC.',
};

export const ICMS_FAMILIA_TAB_TOOLBAR_TOOLTIPS = {
  adicionarCorrecao: 'Adiciona correção manual.',
  excluirCorrecao: 'Exclui a correção.',
  paginaAnterior: 'Página anterior.',
  paginaProxima: 'Próxima página.',
} as const;

export const ICMS_CORRECAO_FIELD_TOOLTIPS: Record<string, string> = {
  competencia: 'Competência da correção.',
  data_lancamento: 'Data da correção.',
  descricao: 'Motivo da correção.',
  produto: 'Produto da correção.',
  aliquota: 'Alíquota da correção.',
  valor: 'Valor ajustado.',
  credito: 'Crédito ajustado.',
  fundes: 'FUNDES ajustado.',
  funded: 'FUNDED ajustado.',
  icms_12: 'ICMS a 12%.',
  icms: 'ICMS ajustado.',
  credito_outor: 'Crédito outorgado.',
  fundeic: 'FUNDEIC ajustado.',
  icms_devido: 'ICMS devido ajustado.',
  cancelar: 'Fecha sem salvar.',
  salvar: 'Salva a correção.',
} as const;

export const ICMS_T03_2_TOOLTIPS = {
  resumoCompetencia: 'Competência do resumo.',
  resumoIcmsSt: 'ICMS ST do mês.',
  resumoBcSt: 'Base de ST do mês.',
  resumoDiferencaEfd: 'Diferença x EFD.',
  familiaTodos: 'Todas as famílias.',
  familiaAcucarSt: 'Filtra Açúcar ST.',
  familiaEtanolSt: 'Filtra Etanol ST.',
  familiaNaoClassificados: 'Somente não classificados.',
  familia: 'Família fiscal.',
  competencia: 'Competência.',
  nf: 'Número da nota.',
  data: 'Data da nota.',
  cfop: 'CFOP da saída.',
  cst: 'CST da operação.',
  ncm: 'NCM do produto.',
  codProduto: 'Código do produto.',
  descricao: 'Descrição da linha.',
  produto: 'Nome do produto.',
  valorMercadoria: 'Valor da mercadoria.',
  incidenciaSt: 'Incidência de ST.',
  bcSt: 'Base de ST.',
  aliquota: 'Alíquota da ST.',
  mva: 'MVA aplicada.',
  icmsSt: 'ICMS ST da linha.',
  efdBcSt: 'Base ST na EFD.',
  diferenca: 'Diferença x EFD.',
} as const;
