// AUTO-GERADO por projects/osg/scripts/build_checklist.py — NÃO editar à mão.
// Fonte: Memorando de Solicitações Iniciais (fonte pura) + DocBox Consolidado + PDF de validação (diagramas).
// Regenerar: python scripts/build_checklist.py  (grava o .xlsx e este .ts a partir das mesmas ROWS).

export interface ChecklistItem {
  obrigatorio: boolean;
  modulo: string;
  entidade: string;
  documento: string;
  nota: string;
  categoriaDocbox: string;
  confidencial: boolean;
}

export const MODULO_ORDER: string[] = ["Qualificação das Partes", "Diagnóstico Patrimonial", "Quadro Societário", "EXTRAS POR PROJETO"];
export const ENTIDADE_ORDER: string[] = ["Pessoa Física", "Pessoa Jurídica", "Matrícula (Imóvel Rural)", "Matrícula (Imóvel Urbano)", "Bem", "Pessoa Jurídica (Cooperativa)"];

export const CHECKLIST_PADRAO: ChecklistItem[] = [
  { obrigatorio: true, modulo: "Qualificação das Partes", entidade: "Pessoa Física", documento: "Comprovante de endereço", nota: "Atualizado e completo (rua, nº, bairro, cidade, estado, CEP) dos fundadores, sócios, herdeiros e cônjuges/companheiros(as).", categoriaDocbox: "Documentos Pessoais", confidencial: false },
  { obrigatorio: true, modulo: "Qualificação das Partes", entidade: "Pessoa Física", documento: "CPF", nota: "Dos fundadores, sócios, herdeiros e respectivos cônjuges/companheiros(as).", categoriaDocbox: "Documentos Pessoais", confidencial: false },
  { obrigatorio: true, modulo: "Qualificação das Partes", entidade: "Pessoa Física", documento: "DIRPF – Último Exercício", nota: "Declaração entregue referente ao último ano-calendário, de todos os envolvidos (fundadores, sócios e herdeiros).", categoriaDocbox: "DIRPF", confidencial: false },
  { obrigatorio: true, modulo: "Qualificação das Partes", entidade: "Pessoa Física", documento: "RG / CNH", nota: "Identidade Civil com órgão expedidor, dos fundadores, sócios, herdeiros e respectivos cônjuges/companheiros(as).", categoriaDocbox: "Documentos Pessoais", confidencial: false },
  { obrigatorio: false, modulo: "Qualificação das Partes", entidade: "Pessoa Física", documento: "Certidão de casamento / união estável", nota: "Se casado ou em união estável (informar a data inicial da união).", categoriaDocbox: "Documentos Pessoais", confidencial: false },
  { obrigatorio: false, modulo: "Qualificação das Partes", entidade: "Pessoa Física", documento: "Certidão de nascimento", nota: "Se solteiro ou menor de idade.", categoriaDocbox: "Documentos Pessoais", confidencial: false },
  { obrigatorio: false, modulo: "Qualificação das Partes", entidade: "Pessoa Física", documento: "Contrato de doação", nota: "Eventuais contratos de doação realizados a favor ou pelos fundadores, sócios e/ou herdeiros (pré-existentes).", categoriaDocbox: "Documentos Sucessórios", confidencial: true },
  { obrigatorio: false, modulo: "Qualificação das Partes", entidade: "Pessoa Física", documento: "DIRPF – Exercícios Anteriores", nota: "Dos anos-calendário anteriores àqueles em que bens imóveis e/ou quotas foram integralizados em outras empresas.", categoriaDocbox: "DIRPF", confidencial: false },
  { obrigatorio: false, modulo: "Qualificação das Partes", entidade: "Pessoa Física", documento: "GIA / DAR de ITCMD/ITCD", nota: "Declaração/apuração do imposto (distinta do comprovante de pagamento), quando houver doação/transmissão.", categoriaDocbox: "Documentos Sucessórios", confidencial: false },
  { obrigatorio: false, modulo: "Qualificação das Partes", entidade: "Pessoa Física", documento: "Guia / comprovante de recolhimento do ITCMD", nota: "Quando houver doação/transmissão.", categoriaDocbox: "Documentos Sucessórios", confidencial: false },
  { obrigatorio: false, modulo: "Qualificação das Partes", entidade: "Pessoa Física", documento: "Organograma / composição familiar", nota: "Nomes e grau de parentesco de fundadores, sócios, herdeiros e respectivos cônjuges/companheiros(as). Base da legítima × disponível na sucessão.", categoriaDocbox: "Documentos Pessoais", confidencial: false },
  { obrigatorio: false, modulo: "Qualificação das Partes", entidade: "Pessoa Física", documento: "Pacto antenupcial", nota: "Se existente / regime diverso da comunhão parcial.", categoriaDocbox: "Documentos Pessoais", confidencial: false },
  { obrigatorio: false, modulo: "Qualificação das Partes", entidade: "Pessoa Física", documento: "Testamento", nota: "Eventuais testamentos realizados a favor ou pelos fundadores, sócios e/ou herdeiros (pré-existentes).", categoriaDocbox: "Documentos Sucessórios", confidencial: true },
  { obrigatorio: true, modulo: "Qualificação das Partes", entidade: "Pessoa Jurídica", documento: "Balanço / Balancete / DRE", nota: "Dos três últimos exercícios, ainda que não registrados, e último balancete do ano-calendário vigente.", categoriaDocbox: "Documentos Societários", confidencial: false },
  { obrigatorio: true, modulo: "Qualificação das Partes", entidade: "Pessoa Jurídica", documento: "CNPJ (situação cadastral e regime tributário)", nota: "Atualizado, das PJ do Grupo, indicando o regime tributário adotado.", categoriaDocbox: "Documentos Societários", confidencial: false },
  { obrigatorio: true, modulo: "Qualificação das Partes", entidade: "Pessoa Jurídica", documento: "Contrato social e alterações", nota: "De constituição e todas as alterações posteriores (incluindo S.A.), das empresas do Grupo ou relacionadas, ainda que em nome de PF, PJ ou de terceiros.", categoriaDocbox: "Documentos Societários", confidencial: false },
  { obrigatorio: true, modulo: "Qualificação das Partes", entidade: "Pessoa Jurídica", documento: "Declaração de inexistência de Simples Nacional", nota: "Firmada por representante do Grupo. Caso existam, encaminhar contratos sociais e balanços dessas PJ. (DocBox OSG-Societários — não constava no modelo de Memorando de 2019.)", categoriaDocbox: "Documentos Societários", confidencial: false },
  { obrigatorio: false, modulo: "Qualificação das Partes", entidade: "Pessoa Jurídica", documento: "Boletins de subscrição e laudos de avaliação", nota: "Em caso de sociedades anônimas (inclui livro de ações e transferências).", categoriaDocbox: "Documentos Societários", confidencial: false },
  { obrigatorio: false, modulo: "Qualificação das Partes", entidade: "Pessoa Jurídica", documento: "Contrato de compra e venda de quotas/ações", nota: "Firmados entre sócios atuais ou com terceiros (incluindo sócios antigos).", categoriaDocbox: "Documentos Societários", confidencial: false },
  { obrigatorio: false, modulo: "Qualificação das Partes", entidade: "Pessoa Jurídica", documento: "Deliberação / comprovante de aporte em moeda", nota: "Só se o aumento de capital for por aporte em moeda (insumo da Planilha de Capital Social — consta no PDF de validação; NÃO no Memorando nem na solicitação DocBox).", categoriaDocbox: "Documentos Societários", confidencial: false },
  { obrigatorio: false, modulo: "Qualificação das Partes", entidade: "Pessoa Jurídica", documento: "Documentos de AFAC / mútuo", nota: "Só se houver conversão de AFAC/mútuo em capital (insumo da Planilha de Capital Social — consta no PDF de validação; NÃO no Memorando nem na solicitação DocBox).", categoriaDocbox: "Documentos Societários", confidencial: false },
  { obrigatorio: false, modulo: "Qualificação das Partes", entidade: "Pessoa Jurídica", documento: "Informação de percentual de participação do grupo", nota: "Percentual de participação dos membros do grupo, devidamente reconhecido, independentemente de outros atos societários.", categoriaDocbox: "Documentos Societários", confidencial: false },
  { obrigatorio: false, modulo: "Qualificação das Partes", entidade: "Pessoa Jurídica", documento: "Instrumento de cessão de quotas/ações", nota: "Eventuais cessões (gratuitas ou onerosas).", categoriaDocbox: "Documentos Societários", confidencial: false },
  { obrigatorio: false, modulo: "Qualificação das Partes", entidade: "Pessoa Jurídica", documento: "Livros societários", nota: "Conforme o tipo societário: ações nominativas, transferências, debêntures, partes beneficiárias, administração, presença e registro de assembleias/reuniões (termo de abertura/encerramento e páginas preenchidas).", categoriaDocbox: "Documentos Societários", confidencial: false },
  { obrigatorio: false, modulo: "Qualificação das Partes", entidade: "Pessoa Jurídica", documento: "Protocolo/acordo societário ou familiar", nota: "De qualquer natureza, ainda que não formalizados na Junta Comercial ou Cartório.", categoriaDocbox: "Documentos Societários", confidencial: false },
  { obrigatorio: true, modulo: "Diagnóstico Patrimonial", entidade: "Matrícula (Imóvel Rural)", documento: "CCIR", nota: "Atualizado, para levantamento do número de cadastro do imóvel rural.", categoriaDocbox: "Documentos Fiscais", confidencial: false },
  { obrigatorio: true, modulo: "Diagnóstico Patrimonial", entidade: "Matrícula (Imóvel Rural)", documento: "ITR", nota: "Atualizado dos imóveis rurais. (Obrigatório pelo DocBox atual OSG-Fiscais; o modelo de Memorando de 2019 pedia só CCIR+IPTU — DocBox prevalece.)", categoriaDocbox: "Documentos Fiscais", confidencial: false },
  { obrigatorio: true, modulo: "Diagnóstico Patrimonial", entidade: "Matrícula (Imóvel Rural)", documento: "Matrícula do imóvel (inteiro teor)", nota: "Certidão de Inteiro Teor atualizada dos imóveis rurais, em nome das PF ou de terceiros, e também das PJ.", categoriaDocbox: "Documentos dos Bens Imóveis", confidencial: false },
  { obrigatorio: false, modulo: "Diagnóstico Patrimonial", entidade: "Matrícula (Imóvel Rural)", documento: "CAR (Cadastro Ambiental Rural)", nota: "Quando usado no acervo do cliente (a validar com a OSG — não consta no Modelo Docbox/memorando padrão).", categoriaDocbox: "Documentos dos Bens Imóveis", confidencial: false },
  { obrigatorio: false, modulo: "Diagnóstico Patrimonial", entidade: "Matrícula (Imóvel Rural)", documento: "Contrato particular de compra e venda (CCV)", nota: "Imóvel não quitado e/ou transferência não registrada à margem da matrícula (inclusive em nome de terceiros).", categoriaDocbox: "Documentos dos Bens Imóveis", confidencial: false },
  { obrigatorio: false, modulo: "Diagnóstico Patrimonial", entidade: "Matrícula (Imóvel Rural)", documento: "Documento de georreferenciamento (SIGEF)", nota: "Se o imóvel for georreferenciado.", categoriaDocbox: "Documentos dos Bens Imóveis", confidencial: false },
  { obrigatorio: false, modulo: "Diagnóstico Patrimonial", entidade: "Matrícula (Imóvel Rural)", documento: "Escritura pública de compra e venda", nota: "Imóvel não quitado e/ou transferência não registrada à margem da matrícula (inclusive em nome de terceiros).", categoriaDocbox: "Documentos dos Bens Imóveis", confidencial: false },
  { obrigatorio: false, modulo: "Diagnóstico Patrimonial", entidade: "Matrícula (Imóvel Rural)", documento: "Matrícula anterior (remissão)", nota: "Quando a matrícula atual faz remissão à matrícula-mãe/anterior.", categoriaDocbox: "Documentos dos Bens Imóveis", confidencial: false },
  { obrigatorio: true, modulo: "Diagnóstico Patrimonial", entidade: "Matrícula (Imóvel Urbano)", documento: "IPTU / Inscrição Municipal", nota: "Carnê/título do último exercício, para levantamento do número de cadastro do imóvel urbano.", categoriaDocbox: "Documentos Fiscais", confidencial: false },
  { obrigatorio: true, modulo: "Diagnóstico Patrimonial", entidade: "Matrícula (Imóvel Urbano)", documento: "Matrícula do imóvel (inteiro teor)", nota: "Certidão de Inteiro Teor atualizada dos imóveis urbanos, em nome das PF ou de terceiros, e também das PJ.", categoriaDocbox: "Documentos dos Bens Imóveis", confidencial: false },
  { obrigatorio: false, modulo: "Diagnóstico Patrimonial", entidade: "Matrícula (Imóvel Urbano)", documento: "Contrato particular de compra e venda (CCV)", nota: "Imóvel urbano não quitado e/ou transferência não registrada à margem da matrícula.", categoriaDocbox: "Documentos dos Bens Imóveis", confidencial: false },
  { obrigatorio: false, modulo: "Diagnóstico Patrimonial", entidade: "Matrícula (Imóvel Urbano)", documento: "Escritura pública de compra e venda", nota: "Imóvel urbano não quitado e/ou transferência não registrada à margem da matrícula.", categoriaDocbox: "Documentos dos Bens Imóveis", confidencial: false },
  { obrigatorio: true, modulo: "Diagnóstico Patrimonial", entidade: "Bem", documento: "Relação de áreas exploradas por imóvel", nota: "Rol dos imóveis explorados (próprios × de terceiros) com área total e explorada por unidade produtora — Memorando item 8 / DocBox OSG-Atividade Rural. Obrigatório quando há atividade rural.", categoriaDocbox: "Documentos da Atividade Rural", confidencial: false },
  { obrigatorio: false, modulo: "Diagnóstico Patrimonial", entidade: "Bem", documento: "Contrato de exploração rural pré-existente", nota: "Arrendamento, parceria, composse, comodato e/ou condomínio das unidades produtoras, devidamente assinados/reconhecidos.", categoriaDocbox: "Documentos da Atividade Rural", confidencial: false },
  { obrigatorio: false, modulo: "Diagnóstico Patrimonial", entidade: "Bem", documento: "Contrato de locação de imóvel urbano", nota: "Imóveis urbanos do grupo cedidos a terceiros e/ou PF/PJ, devidamente assinados.", categoriaDocbox: "Documentos de Locação", confidencial: false },
  { obrigatorio: false, modulo: "Diagnóstico Patrimonial", entidade: "Bem", documento: "Informações contábeis das PJs envolvidas", nota: "Dados contábeis das PJs (ECD/DRE e demais), quando aplicável ao planejamento tributário.", categoriaDocbox: "Documentos do Planejamento Tributário", confidencial: false },
  { obrigatorio: false, modulo: "Diagnóstico Patrimonial", entidade: "Bem", documento: "Laudo de avaliação de valor de mercado", nota: "Quando o estudo utilizar valor de mercado dos bens.", categoriaDocbox: "Documentos dos Bens Imóveis", confidencial: false },
  { obrigatorio: false, modulo: "Diagnóstico Patrimonial", entidade: "Bem", documento: "Livro-caixa do Produtor Rural", nota: "CONDICIONAL — insumo do Planejamento Tributário Rural (fase TAX); NÃO é pedido no Memorando inicial da OSG. Só quando o escopo inclui planejamento tributário rural.", categoriaDocbox: "Documentos do Planejamento Tributário", confidencial: false },
  { obrigatorio: false, modulo: "Diagnóstico Patrimonial", entidade: "Bem", documento: "Passivos / riscos ambientais (informação)", nota: "Processos de regularização agrária/ambiental, processos que impeçam transferência, ou imóvel em área de moratória da soja (após 2008).", categoriaDocbox: "Documentos dos Bens Imóveis", confidencial: false },
  { obrigatorio: false, modulo: "Diagnóstico Patrimonial", entidade: "Bem", documento: "Planilha de Diagnóstico Tributário (receitas/despesas)", nota: "CONDICIONAL — receitas/despesas por safra/cultura p/ o planejamento tributário rural (fase TAX). Só quando o escopo inclui planejamento tributário.", categoriaDocbox: "Documentos do Planejamento Tributário", confidencial: false },
  { obrigatorio: false, modulo: "Diagnóstico Patrimonial", entidade: "Bem", documento: "Planilha de resultado projetado (PF e PJ)", nota: "Projeção do resultado (PF e PJ), separada por tipo de atividade, conforme modelo enviado.", categoriaDocbox: "Documentos do Planejamento Tributário", confidencial: false },
  { obrigatorio: false, modulo: "Diagnóstico Patrimonial", entidade: "Bem", documento: "Projeção de investimentos (próximos anos)", nota: "Descrição do projeto e possíveis valores a desembolsar (ex.: 2027-2029), se aplicável.", categoriaDocbox: "Documentos do Planejamento Tributário", confidencial: false },
  { obrigatorio: false, modulo: "Diagnóstico Patrimonial", entidade: "Bem", documento: "Relatório de bens da atividade rural (aquisição e mercado)", nota: "Em Excel: bens da atividade rural com datas de aquisição, valores de aquisição e valores de mercado.", categoriaDocbox: "Documentos do Planejamento Tributário", confidencial: false },
  { obrigatorio: false, modulo: "Diagnóstico Patrimonial", entidade: "Bem", documento: "Relatório de dívidas da atividade rural", nota: "Em Excel: valores a pagar para os próximos anos, conforme as datas de vencimento.", categoriaDocbox: "Documentos do Planejamento Tributário", confidencial: false },
  { obrigatorio: false, modulo: "Diagnóstico Patrimonial", entidade: "Bem", documento: "Relação de bens com intenção de alienação", nota: "Matrículas em processo e/ou com previsão/desejo de alienação.", categoriaDocbox: "Documentos dos Bens Imóveis", confidencial: false },
  { obrigatorio: false, modulo: "Quadro Societário", entidade: "Pessoa Jurídica", documento: "Diagnóstico de outras consultorias", nota: "Diagnósticos Sucessórios, Societários e/ou de Governança realizados por outras consultorias.", categoriaDocbox: "Documentos de Governança", confidencial: false },
  { obrigatorio: false, modulo: "Quadro Societário", entidade: "Pessoa Jurídica", documento: "Laudo / simulação de valor das quotas", nota: "Avaliação ou simulação do valor das quotas, quando existente (insumo do estudo sucessório).", categoriaDocbox: "Documentos Societários", confidencial: false },
  { obrigatorio: false, modulo: "Quadro Societário", entidade: "Pessoa Jurídica", documento: "Matriz de alçadas existente", nota: "Matriz e eventuais políticas de alçadas (financeiras e/ou de atos e negócios jurídicos), ainda que em planilha ou minuta não formalizada.", categoriaDocbox: "Documentos de Governança", confidencial: false },
  { obrigatorio: false, modulo: "Quadro Societário", entidade: "Pessoa Jurídica", documento: "Organograma societário do grupo", nota: "Estrutura societária atual (holdings, sociedades controladas, sócios e participações).", categoriaDocbox: "Documentos Societários", confidencial: false },
  { obrigatorio: false, modulo: "Quadro Societário", entidade: "Pessoa Jurídica", documento: "Respostas do questionário de governança", nota: "Respostas do cliente/família ao questionário de governança da PSA.", categoriaDocbox: "Documentos de Governança", confidencial: false },
  { obrigatorio: false, modulo: "EXTRAS POR PROJETO", entidade: "Pessoa Jurídica (Cooperativa)", documento: "Acordo com cooperativas centrais/federações", nota: "Cooperativa.", categoriaDocbox: "Documentos Societários", confidencial: false },
  { obrigatorio: false, modulo: "EXTRAS POR PROJETO", entidade: "Pessoa Jurídica (Cooperativa)", documento: "Ata de assembleia", nota: "Ordinária/Extraordinária, dos últimos 3 anos (cooperativa).", categoriaDocbox: "Documentos Societários", confidencial: false },
  { obrigatorio: false, modulo: "EXTRAS POR PROJETO", entidade: "Pessoa Jurídica (Cooperativa)", documento: "Edital de convocação", nota: "Das assembleias (cooperativa).", categoriaDocbox: "Documentos Societários", confidencial: false },
  { obrigatorio: false, modulo: "EXTRAS POR PROJETO", entidade: "Pessoa Jurídica (Cooperativa)", documento: "Estatuto Social", nota: "Atualizado (cooperativa).", categoriaDocbox: "Documentos Societários", confidencial: false },
  { obrigatorio: false, modulo: "EXTRAS POR PROJETO", entidade: "Pessoa Jurídica (Cooperativa)", documento: "Lista de cooperados", nota: "Atualizada (cooperativa).", categoriaDocbox: "Documentos Societários", confidencial: false },
  { obrigatorio: false, modulo: "EXTRAS POR PROJETO", entidade: "Pessoa Jurídica (Cooperativa)", documento: "Livro de presença das assembleias", nota: "Cooperativa.", categoriaDocbox: "Documentos Societários", confidencial: false },
  { obrigatorio: false, modulo: "EXTRAS POR PROJETO", entidade: "Pessoa Jurídica (Cooperativa)", documento: "Política de distribuição de sobras/perdas", nota: "Controle de sobras/perdas e sua destinação (cooperativa).", categoriaDocbox: "Documentos Societários", confidencial: false },
  { obrigatorio: false, modulo: "EXTRAS POR PROJETO", entidade: "Pessoa Jurídica (Cooperativa)", documento: "Registro na Junta Comercial", nota: "Registro da cooperativa na Junta Comercial.", categoriaDocbox: "Documentos Societários", confidencial: false },
];
