import type {
  AbaApoioWp,
  AbaCenarioWp,
  AbaFarolWp,
  AbaResumoWp,
  AbaVendaDeAtivosWp,
  CabecalhoWp,
  ParametrosWp,
  ValidacaoWp,
} from '@/lib/planejamento-tributario/tipos';

/**
 * O mapa do papel de trabalho de Planejamento Tributário, em código.
 *
 * Isto é a PT-01 transcrita: para cada aba do WP, quais linhas existem, em que
 * endereço, com que unidade e em que nível da hierarquia. O documento em prosa
 * vive em `PT-01-mapa-do-wp.md`; aqui está a mesma coisa numa forma que o parser
 * lê e que o teste consegue conferir.
 *
 * **Gerado a partir do arquivo, não digitado.** Os rótulos saem do próprio
 * `WP Atualizado`, porque um caractere diferente num rótulo faz a leitura não
 * achar a linha, e esse é o tipo de erro que passa por revisão humana. Os
 * metadados (nível, unidade, editável) vêm de regras declaradas no gerador e
 * revisadas à mão.
 *
 * **O endereço é o do modelo, e o modelo é o único formato aceito.** Os quatro
 * estudos antigos põem a mesma linha em posições diferentes: a primeira linha de
 * tributo do `Resumo` é a 15 na Lunardi, 16 no Piccini, 17 no Bahia Potrich e 19
 * no Boscoli. A Mônica confirmou em 31/08/2026 que o `WP Atualizado` é o
 * definitivo, e é por isso que ler por endereço funciona.
 *
 * **`VERSAO_DO_MAPA` é gravada em cada revisão importada.** Quando o modelo
 * mudar, a versão sobe, e as revisões antigas continuam explicáveis porque se
 * sabe com que régua foram lidas. É exigência do "pronto quando" da PT-02.
 */
export const VERSAO_DO_MAPA = '1.4';

/**
 * O cabeçalho do estudo. Não vira slide: é o que identifica a revisão importada,
 * e é de onde saem o nome do cliente escrito na planilha e os anos do estudo.
 */
export const CABECALHO_DO_ESTUDO: CabecalhoWp = {
  aba: 'Resumo',
  cliente: 'B3',
  dataBase: 'B4',
  preparadoPor: 'B7',
  revisadoPor: 'B8',
};

/** As duas premissas de projeção, na única aba que as declara. */
export const PARAMETROS: ParametrosWp = {
  aba: 'DRE Projetada',
  crescimentoAnual: 'C5',
  anoBase: 'C7',
};

/**
 * A DRE é uma lista fixa de contas, e não muda de estudo para estudo: o que muda
 * é quais foram preenchidas. Regra dada pela Mônica em 31/08/2026, e é por isso
 * que não existe aqui um campo dizendo se a linha vai ao slide: isso se decide na
 * leitura, pela presença de valor, não no mapa.
 *
 * `editavel` marca as sete contas de "outros", que na aba de cenário são fórmulas
 * espelhadas de `DRE Projetada` coluna B. O texto delas é conteúdo que o
 * consultor escreve, então a leitura deve seguir a fórmula em vez de casar pelo
 * rótulo.
 */

export const ABA_RESUMO: AbaResumoWp = {
  nome: 'Resumo',
  cabecalhoAnos: 14,
  cabecalhoCenarios: 15,
  colunasPorAno: [
    ['D', 'E', 'F'],
    ['H', 'I', 'J'],
    ['L', 'M', 'N'],
  ],
  linhas: [
    {
      linha: 16,
      rotulo: 'Pessoa Física',
      grupo: 'pessoa_fisica',
      nivel: 0,
      unidade: 'moeda',
      eTotal: true,
    },
    { linha: 17, rotulo: 'IRPF', grupo: 'pessoa_fisica', nivel: 1, unidade: 'moeda' },
    {
      linha: 18,
      rotulo: 'CBS (a partir de 2027)',
      grupo: 'pessoa_fisica',
      nivel: 1,
      unidade: 'moeda',
    },
    { linha: 19, rotulo: 'INSS', grupo: 'pessoa_fisica', nivel: 1, unidade: 'moeda' },
    {
      linha: 21,
      rotulo: 'PJ - Lucro Presumido',
      grupo: 'pj_lucro_presumido',
      nivel: 0,
      unidade: 'moeda',
      eTotal: true,
    },
    { linha: 22, rotulo: 'IRPJ/CSLL', grupo: 'pj_lucro_presumido', nivel: 1, unidade: 'moeda' },
    { linha: 23, rotulo: 'PIS/Cofins', grupo: 'pj_lucro_presumido', nivel: 1, unidade: 'moeda' },
    {
      linha: 24,
      rotulo: 'CBS (a partir de 2027)',
      grupo: 'pj_lucro_presumido',
      nivel: 1,
      unidade: 'moeda',
    },
    { linha: 25, rotulo: 'INSS', grupo: 'pj_lucro_presumido', nivel: 1, unidade: 'moeda' },
    {
      linha: 27,
      rotulo: 'PJ - Lucro Real',
      grupo: 'pj_lucro_real',
      nivel: 0,
      unidade: 'moeda',
      eTotal: true,
    },
    { linha: 28, rotulo: 'IRPJ/CSLL', grupo: 'pj_lucro_real', nivel: 1, unidade: 'moeda' },
    { linha: 29, rotulo: 'PIS/Cofins', grupo: 'pj_lucro_real', nivel: 1, unidade: 'moeda' },
    {
      linha: 30,
      rotulo: 'CBS (a partir de 2027)',
      grupo: 'pj_lucro_real',
      nivel: 1,
      unidade: 'moeda',
    },
    { linha: 31, rotulo: 'INSS', grupo: 'pj_lucro_real', nivel: 1, unidade: 'moeda' },
    { linha: 33, rotulo: 'Total', nivel: 0, unidade: 'moeda', eTotal: true },
    { linha: 34, rotulo: 'Redução', nivel: 0, unidade: 'percentual' },
  ],
};

export const ABA_FAROL: AbaFarolWp = {
  nome: 'Farol',
  cabecalhoRegimes: 8,
  cabecalhoPessoas: 9,
  colunas: [
    { coluna: 'C', regime: 'presumido', pessoa: 'pf' },
    { coluna: 'D', regime: 'presumido', pessoa: 'pj' },
    { coluna: 'E', regime: 'real', pessoa: 'pf' },
    { coluna: 'F', regime: 'real', pessoa: 'pj' },
  ],
  notas: { de: 34, ate: 39 },
  linhas: [
    { linha: 11, rotulo: 'IRPF/IRPJ/CSLL', nivel: 0, unidade: 'texto', eTitulo: true },
    {
      linha: 12,
      rotulo: 'Tributação com base no faturamento',
      grupo: 'IRPF/IRPJ/CSLL',
      nivel: 1,
      unidade: 'percentual',
    },
    {
      linha: 13,
      rotulo: 'Tributação com base no lucro efetivo',
      grupo: 'IRPF/IRPJ/CSLL',
      nivel: 1,
      unidade: 'percentual',
    },
    {
      linha: 14,
      rotulo: 'Tributação de dividendos',
      grupo: 'IRPF/IRPJ/CSLL',
      nivel: 1,
      unidade: 'percentual',
    },
    {
      linha: 15,
      rotulo: 'Uso de prejuízos fiscais sem limitações',
      grupo: 'IRPF/IRPJ/CSLL',
      nivel: 1,
      unidade: 'percentual',
    },
    {
      linha: 16,
      rotulo: 'Dedução fiscal imediata de gastos com imobilizados',
      grupo: 'IRPF/IRPJ/CSLL',
      nivel: 1,
      unidade: 'percentual',
    },
    {
      linha: 18,
      rotulo: 'PIS/Cofins - Vigente até 31/12/2026',
      nivel: 0,
      unidade: 'texto',
      eTitulo: true,
    },
    {
      linha: 19,
      rotulo: 'Tributação com base no faturamento',
      grupo: 'PIS/Cofins - Vigente até 31/12/2026',
      nivel: 1,
      unidade: 'percentual',
    },
    {
      linha: 20,
      rotulo: 'Alíquotas reduzidas para os principais produtos agrícolas',
      grupo: 'PIS/Cofins - Vigente até 31/12/2026',
      nivel: 1,
      unidade: 'percentual',
    },
    {
      linha: 21,
      rotulo: 'Apropriação de crédito sobre as aquisições',
      grupo: 'PIS/Cofins - Vigente até 31/12/2026',
      nivel: 1,
      unidade: 'percentual',
    },
    {
      linha: 23,
      rotulo: 'IBS e CBS - Vigente a partir de 2027',
      nivel: 0,
      unidade: 'texto',
      eTitulo: true,
    },
    {
      linha: 24,
      rotulo: 'Tributação com base no faturamento',
      grupo: 'IBS e CBS - Vigente a partir de 2027',
      nivel: 1,
      unidade: 'percentual',
    },
    {
      linha: 25,
      rotulo: 'Alíquota reduzida para os produtos agrícolas',
      grupo: 'IBS e CBS - Vigente a partir de 2027',
      nivel: 1,
      unidade: 'percentual',
    },
    {
      linha: 26,
      rotulo: 'Apropriação de crédito sobre as aquisições',
      grupo: 'IBS e CBS - Vigente a partir de 2027',
      nivel: 1,
      unidade: 'percentual',
    },
    { linha: 28, rotulo: 'FUNRURAL', nivel: 0, unidade: 'texto', eTitulo: true },
    {
      linha: 29,
      rotulo: 'Opção pela folha de pagamento ou faturamento',
      grupo: 'FUNRURAL',
      nivel: 1,
      unidade: 'percentual',
    },
    {
      linha: 30,
      rotulo: 'Tributação com base na folha de pagamento',
      grupo: 'FUNRURAL',
      nivel: 1,
      unidade: 'percentual',
    },
    {
      linha: 31,
      rotulo: 'Tributação com base no faturamento⁴',
      grupo: 'FUNRURAL',
      nivel: 1,
      unidade: 'percentual',
    },
  ],
};

export const ABAS_DE_CENARIO: AbaCenarioWp[] = [
  {
    nome: 'Cenário Atual (PF)',
    anos: 29,
    contribuinte: 30,
    dre: [
      { linha: 31, rotulo: 'Receita', nivel: 0, unidade: 'moeda', eTotal: true },
      {
        linha: 32,
        rotulo: '(+) M.I. Arrendamento/Aluguel',
        grupo: 'Receita',
        nivel: 1,
        unidade: 'moeda',
        eTotal: true,
      },
      {
        linha: 33,
        rotulo: '(+) Arrendamento/Aluguel',
        grupo: '(+) M.I. Arrendamento/Aluguel',
        nivel: 2,
        unidade: 'moeda',
      },
      {
        linha: 34,
        rotulo: '(+) M.I. - Agrícola própria',
        grupo: 'Receita',
        nivel: 1,
        unidade: 'moeda',
        eTotal: true,
      },
      {
        linha: 35,
        rotulo: '(+) Soja - Própria',
        grupo: '(+) M.I. - Agrícola própria',
        nivel: 2,
        unidade: 'moeda',
      },
      {
        linha: 36,
        rotulo: '(+) Milho - Própria',
        grupo: '(+) M.I. - Agrícola própria',
        nivel: 2,
        unidade: 'moeda',
      },
      {
        linha: 37,
        rotulo: '(+) Algodão - Própria',
        grupo: '(+) M.I. - Agrícola própria',
        nivel: 2,
        unidade: 'moeda',
      },
      {
        linha: 38,
        rotulo: '(+) Milheto - Própria',
        grupo: '(+) M.I. - Agrícola própria',
        nivel: 2,
        unidade: 'moeda',
      },
      {
        linha: 39,
        rotulo: '(+) Sorgo - Própria',
        grupo: '(+) M.I. - Agrícola própria',
        nivel: 2,
        unidade: 'moeda',
      },
      {
        linha: 40,
        rotulo: '(+) Arroz - Própria',
        grupo: '(+) M.I. - Agrícola própria',
        nivel: 2,
        unidade: 'moeda',
      },
      {
        linha: 41,
        rotulo: '(+) Feijão - Própria',
        grupo: '(+) M.I. - Agrícola própria',
        nivel: 2,
        unidade: 'moeda',
      },
      {
        linha: 42,
        rotulo: '(+) Sementes - Própria',
        grupo: '(+) M.I. - Agrícola própria',
        nivel: 2,
        unidade: 'moeda',
      },
      {
        linha: 43,
        rotulo: '(+) Gado (cria/recria) - Própria',
        grupo: '(+) M.I. - Agrícola própria',
        nivel: 2,
        unidade: 'moeda',
      },
      {
        linha: 44,
        rotulo: '(+) Gado (abate) - Própria',
        grupo: '(+) M.I. - Agrícola própria',
        nivel: 2,
        unidade: 'moeda',
      },
      {
        linha: 45,
        rotulo: '(+) Outros: especificar - Própria',
        grupo: '(+) M.I. - Agrícola própria',
        nivel: 2,
        unidade: 'moeda',
        editavel: true,
      },
      {
        linha: 46,
        rotulo: '(+) M.I. - Agrícola arrendada',
        grupo: 'Receita',
        nivel: 1,
        unidade: 'moeda',
        eTotal: true,
      },
      {
        linha: 47,
        rotulo: '(+) Soja - Arrendada',
        grupo: '(+) M.I. - Agrícola arrendada',
        nivel: 2,
        unidade: 'moeda',
      },
      {
        linha: 48,
        rotulo: '(+) Milho - Arrendada',
        grupo: '(+) M.I. - Agrícola arrendada',
        nivel: 2,
        unidade: 'moeda',
      },
      {
        linha: 49,
        rotulo: '(+) Algodão - Arrendada',
        grupo: '(+) M.I. - Agrícola arrendada',
        nivel: 2,
        unidade: 'moeda',
      },
      {
        linha: 50,
        rotulo: '(+) Milheto - Arrendada',
        grupo: '(+) M.I. - Agrícola arrendada',
        nivel: 2,
        unidade: 'moeda',
      },
      {
        linha: 51,
        rotulo: '(+) Sorgo - Arrendada',
        grupo: '(+) M.I. - Agrícola arrendada',
        nivel: 2,
        unidade: 'moeda',
      },
      {
        linha: 52,
        rotulo: '(+) Arroz - Arrendada',
        grupo: '(+) M.I. - Agrícola arrendada',
        nivel: 2,
        unidade: 'moeda',
      },
      {
        linha: 53,
        rotulo: '(+) Feijão - Arrendada',
        grupo: '(+) M.I. - Agrícola arrendada',
        nivel: 2,
        unidade: 'moeda',
      },
      {
        linha: 54,
        rotulo: '(+) Sementes - Arrendada',
        grupo: '(+) M.I. - Agrícola arrendada',
        nivel: 2,
        unidade: 'moeda',
      },
      {
        linha: 55,
        rotulo: '(+) Gado (cria/recria) - Arrendada',
        grupo: '(+) M.I. - Agrícola arrendada',
        nivel: 2,
        unidade: 'moeda',
      },
      {
        linha: 56,
        rotulo: '(+) Gado (abate) - Arrendada',
        grupo: '(+) M.I. - Agrícola arrendada',
        nivel: 2,
        unidade: 'moeda',
      },
      {
        linha: 57,
        rotulo: '(+) Outros: especificar - Arrendada',
        grupo: '(+) M.I. - Agrícola arrendada',
        nivel: 2,
        unidade: 'moeda',
        editavel: true,
      },
      {
        linha: 58,
        rotulo: '(+) M.E. - Agrícola própria',
        grupo: 'Receita',
        nivel: 1,
        unidade: 'moeda',
        eTotal: true,
      },
      {
        linha: 59,
        rotulo: '(+) Soja - Própria',
        grupo: '(+) M.E. - Agrícola própria',
        nivel: 2,
        unidade: 'moeda',
      },
      {
        linha: 60,
        rotulo: '(+) Milho - Própria',
        grupo: '(+) M.E. - Agrícola própria',
        nivel: 2,
        unidade: 'moeda',
      },
      {
        linha: 61,
        rotulo: '(+) Algodão - Própria',
        grupo: '(+) M.E. - Agrícola própria',
        nivel: 2,
        unidade: 'moeda',
      },
      {
        linha: 62,
        rotulo: '(+) Outros: especificar - Própria',
        grupo: '(+) M.E. - Agrícola própria',
        nivel: 2,
        unidade: 'moeda',
        editavel: true,
      },
      {
        linha: 63,
        rotulo: '(+) M.E. - Agrícola arrendada',
        grupo: 'Receita',
        nivel: 1,
        unidade: 'moeda',
        eTotal: true,
      },
      {
        linha: 64,
        rotulo: '(+) Soja - Arrendada',
        grupo: '(+) M.E. - Agrícola arrendada',
        nivel: 2,
        unidade: 'moeda',
      },
      {
        linha: 65,
        rotulo: '(+) Milho - Arrendada',
        grupo: '(+) M.E. - Agrícola arrendada',
        nivel: 2,
        unidade: 'moeda',
      },
      {
        linha: 66,
        rotulo: '(+) Algodão - Arrendada',
        grupo: '(+) M.E. - Agrícola arrendada',
        nivel: 2,
        unidade: 'moeda',
      },
      {
        linha: 67,
        rotulo: '(+) Outros: especificar - Arrendada',
        grupo: '(+) M.E. - Agrícola arrendada',
        nivel: 2,
        unidade: 'moeda',
        editavel: true,
      },
      {
        linha: 68,
        rotulo: '(+) M.I. - Beneficiamento',
        grupo: 'Receita',
        nivel: 1,
        unidade: 'moeda',
        eTotal: true,
      },
      {
        linha: 69,
        rotulo: '(+) Soja grãos',
        grupo: '(+) M.I. - Beneficiamento',
        nivel: 2,
        unidade: 'moeda',
      },
      {
        linha: 70,
        rotulo: '(+) Milho grãos',
        grupo: '(+) M.I. - Beneficiamento',
        nivel: 2,
        unidade: 'moeda',
      },
      {
        linha: 71,
        rotulo: '(+) Algodão pluma',
        grupo: '(+) M.I. - Beneficiamento',
        nivel: 2,
        unidade: 'moeda',
      },
      {
        linha: 72,
        rotulo: '(+) Sementes',
        grupo: '(+) M.I. - Beneficiamento',
        nivel: 2,
        unidade: 'moeda',
      },
      {
        linha: 73,
        rotulo: '(+) M.I. - Outras receitas',
        grupo: 'Receita',
        nivel: 1,
        unidade: 'moeda',
        eTotal: true,
      },
      {
        linha: 74,
        rotulo: '(+) Ganho na venda de imobilizado (Bens da atividade rural)',
        grupo: '(+) M.I. - Outras receitas',
        nivel: 2,
        unidade: 'moeda',
      },
      {
        linha: 75,
        rotulo:
          '(+) Outros: especificar (ex. distribuição de lucros de outras sociedades; eventuais venda de insumos agrícolas, etc)',
        grupo: '(+) M.I. - Outras receitas',
        nivel: 2,
        unidade: 'moeda',
        editavel: true,
      },
      { linha: 76, rotulo: '(-) Custos', nivel: 0, unidade: 'moeda', eTotal: true },
      {
        linha: 77,
        rotulo: '(-) Defensivos - Própria',
        grupo: '(-) Custos',
        nivel: 1,
        unidade: 'moeda',
      },
      {
        linha: 78,
        rotulo: '(-) Defensivos - Arrendada',
        grupo: '(-) Custos',
        nivel: 1,
        unidade: 'moeda',
      },
      {
        linha: 79,
        rotulo: '(-) Fertilizantes e sais minerais - Própria',
        grupo: '(-) Custos',
        nivel: 1,
        unidade: 'moeda',
      },
      {
        linha: 80,
        rotulo: '(-) Fertilizantes e sais minerais - Arrendada',
        grupo: '(-) Custos',
        nivel: 1,
        unidade: 'moeda',
      },
      {
        linha: 81,
        rotulo: '(-) Sementes - Própria',
        grupo: '(-) Custos',
        nivel: 1,
        unidade: 'moeda',
      },
      {
        linha: 82,
        rotulo: '(-) Sementes - Arrendada',
        grupo: '(-) Custos',
        nivel: 1,
        unidade: 'moeda',
      },
      {
        linha: 83,
        rotulo: '(-) Máquinas/Equip. (aquisições)',
        grupo: '(-) Custos',
        nivel: 1,
        unidade: 'moeda',
      },
      {
        linha: 84,
        rotulo: '(-) Máquinas/Equip. (serviços)',
        grupo: '(-) Custos',
        nivel: 1,
        unidade: 'moeda',
      },
      {
        linha: 85,
        rotulo: '(-) Pecuária - DDG, uréia, sais, caroço e torta',
        grupo: '(-) Custos',
        nivel: 1,
        unidade: 'moeda',
      },
      {
        linha: 86,
        rotulo: '(-) Reposição de cabeças de gado (reprodução/recria/bezerro)',
        grupo: '(-) Custos',
        nivel: 1,
        unidade: 'moeda',
      },
      {
        linha: 87,
        rotulo: '(-) Reposição de cabeças de gado (boi magro/garrote)',
        grupo: '(-) Custos',
        nivel: 1,
        unidade: 'moeda',
      },
      {
        linha: 88,
        rotulo: '(-) Custos com cria do gado',
        grupo: '(-) Custos',
        nivel: 1,
        unidade: 'moeda',
      },
      {
        linha: 89,
        rotulo: '(-) Consultoria agronômica',
        grupo: '(-) Custos',
        nivel: 1,
        unidade: 'moeda',
      },
      {
        linha: 90,
        rotulo: '(-) Despesas com avião agrícola',
        grupo: '(-) Custos',
        nivel: 1,
        unidade: 'moeda',
      },
      {
        linha: 91,
        rotulo: '(-) Manutenção de estradas',
        grupo: '(-) Custos',
        nivel: 1,
        unidade: 'moeda',
      },
      {
        linha: 92,
        rotulo: '(-) Combustível (Diesel, gasolina, energia, etc)',
        grupo: '(-) Custos',
        nivel: 1,
        unidade: 'moeda',
      },
      {
        linha: 93,
        rotulo: '(-) Beneficiamento de sementes',
        grupo: '(-) Custos',
        nivel: 1,
        unidade: 'moeda',
      },
      {
        linha: 94,
        rotulo: '(-) Tributos e contribuições',
        grupo: '(-) Custos',
        nivel: 1,
        unidade: 'moeda',
      },
      {
        linha: 95,
        rotulo: '(-) Arrendamento não declarados',
        grupo: '(-) Custos',
        nivel: 1,
        unidade: 'moeda',
      },
      {
        linha: 96,
        rotulo: '(-) Arrendamento declarados',
        grupo: '(-) Custos',
        nivel: 1,
        unidade: 'moeda',
      },
      {
        linha: 97,
        rotulo: '(-) Fol. Pgto - Própria - Agrícola',
        grupo: '(-) Custos',
        nivel: 1,
        unidade: 'moeda',
      },
      {
        linha: 98,
        rotulo: '(-) Fol. Pgto - Arrendada - Agrícola',
        grupo: '(-) Custos',
        nivel: 1,
        unidade: 'moeda',
      },
      {
        linha: 99,
        rotulo: '(-) Fol. Pgto - Beneficiamento',
        grupo: '(-) Custos',
        nivel: 1,
        unidade: 'moeda',
      },
      {
        linha: 100,
        rotulo: '(-) Outros: especificar',
        grupo: '(-) Custos',
        nivel: 1,
        unidade: 'moeda',
        editavel: true,
      },
      {
        linha: 101,
        rotulo: '(-) Despesas administrativas',
        nivel: 0,
        unidade: 'moeda',
        eTotal: true,
      },
      {
        linha: 102,
        rotulo: '(-) Comissões',
        grupo: '(-) Despesas administrativas',
        nivel: 1,
        unidade: 'moeda',
      },
      {
        linha: 103,
        rotulo: '(-) Material de escritório',
        grupo: '(-) Despesas administrativas',
        nivel: 1,
        unidade: 'moeda',
      },
      {
        linha: 104,
        rotulo: '(-) Copa e cozinha',
        grupo: '(-) Despesas administrativas',
        nivel: 1,
        unidade: 'moeda',
      },
      {
        linha: 105,
        rotulo: '(-) Honorários contábeis/advocatícios',
        grupo: '(-) Despesas administrativas',
        nivel: 1,
        unidade: 'moeda',
      },
      {
        linha: 106,
        rotulo: '(-) Telefone/internet',
        grupo: '(-) Despesas administrativas',
        nivel: 1,
        unidade: 'moeda',
      },
      {
        linha: 107,
        rotulo: '(-) Água',
        grupo: '(-) Despesas administrativas',
        nivel: 1,
        unidade: 'moeda',
      },
      {
        linha: 108,
        rotulo: '(-) Outros: especificar',
        grupo: '(-) Despesas administrativas',
        nivel: 1,
        unidade: 'moeda',
        editavel: true,
      },
      {
        linha: 109,
        rotulo: '(+/-) Resultado financeiro',
        nivel: 0,
        unidade: 'moeda',
        eTotal: true,
      },
      {
        linha: 110,
        rotulo: '(+) Receita financeira',
        grupo: '(+/-) Resultado financeiro',
        nivel: 1,
        unidade: 'moeda',
      },
      {
        linha: 111,
        rotulo: '(-) Despesa financeira (taxas bancárias, juros sobre financiamentos)',
        grupo: '(+/-) Resultado financeiro',
        nivel: 1,
        unidade: 'moeda',
      },
      {
        linha: 112,
        rotulo: '(=) Lucro/Prejuízo do exercício',
        nivel: 0,
        unidade: 'moeda',
        eTotal: true,
      },
    ],
    apuracao: [
      {
        linha: 116,
        rotulo: 'Saldo de prejuízo a compensar de exercício(s) anterior(es)',
        nivel: 1,
        unidade: 'moeda',
      },
      { linha: 117, rotulo: 'Resultado do exercício', nivel: 1, unidade: 'moeda' },
      { linha: 118, rotulo: 'Compensação de prejuízo', nivel: 1, unidade: 'moeda' },
      { linha: 119, rotulo: 'Lucro/Prejuízo fiscal do exercício', nivel: 1, unidade: 'moeda' },
      { linha: 120, rotulo: 'Presunção de 20%', nivel: 1, unidade: 'moeda' },
      { linha: 121, rotulo: 'Resultado tributável', nivel: 1, unidade: 'moeda' },
      { linha: 122, rotulo: 'Total a recolher', nivel: 1, unidade: 'moeda' },
      { linha: 123, rotulo: 'Saldo de prejuízo a compensar', nivel: 1, unidade: 'moeda' },
    ],
  },
  {
    nome: 'Cenário 01 (PFxPJ)',
    anos: 39,
    contribuinte: 40,
    dre: [
      { linha: 41, rotulo: 'Receita', nivel: 0, unidade: 'moeda', eTotal: true },
      {
        linha: 42,
        rotulo: '(+) M.I. Arrendamento/Aluguel',
        grupo: 'Receita',
        nivel: 1,
        unidade: 'moeda',
        eTotal: true,
      },
      {
        linha: 43,
        rotulo: '(+) Arrendamento/Aluguel',
        grupo: '(+) M.I. Arrendamento/Aluguel',
        nivel: 2,
        unidade: 'moeda',
      },
      {
        linha: 44,
        rotulo: '(+) M.I. - Agrícola própria',
        grupo: 'Receita',
        nivel: 1,
        unidade: 'moeda',
        eTotal: true,
      },
      {
        linha: 45,
        rotulo: '(+) Soja - Própria',
        grupo: '(+) M.I. - Agrícola própria',
        nivel: 2,
        unidade: 'moeda',
      },
      {
        linha: 46,
        rotulo: '(+) Milho - Própria',
        grupo: '(+) M.I. - Agrícola própria',
        nivel: 2,
        unidade: 'moeda',
      },
      {
        linha: 47,
        rotulo: '(+) Algodão - Própria',
        grupo: '(+) M.I. - Agrícola própria',
        nivel: 2,
        unidade: 'moeda',
      },
      {
        linha: 48,
        rotulo: '(+) Milheto - Própria',
        grupo: '(+) M.I. - Agrícola própria',
        nivel: 2,
        unidade: 'moeda',
      },
      {
        linha: 49,
        rotulo: '(+) Sorgo - Própria',
        grupo: '(+) M.I. - Agrícola própria',
        nivel: 2,
        unidade: 'moeda',
      },
      {
        linha: 50,
        rotulo: '(+) Arroz - Própria',
        grupo: '(+) M.I. - Agrícola própria',
        nivel: 2,
        unidade: 'moeda',
      },
      {
        linha: 51,
        rotulo: '(+) Feijão - Própria',
        grupo: '(+) M.I. - Agrícola própria',
        nivel: 2,
        unidade: 'moeda',
      },
      {
        linha: 52,
        rotulo: '(+) Sementes - Própria',
        grupo: '(+) M.I. - Agrícola própria',
        nivel: 2,
        unidade: 'moeda',
      },
      {
        linha: 53,
        rotulo: '(+) Gado (cria/recria) - Própria',
        grupo: '(+) M.I. - Agrícola própria',
        nivel: 2,
        unidade: 'moeda',
      },
      {
        linha: 54,
        rotulo: '(+) Gado (abate) - Própria',
        grupo: '(+) M.I. - Agrícola própria',
        nivel: 2,
        unidade: 'moeda',
      },
      {
        linha: 55,
        rotulo: '(+) Outros: especificar - Própria',
        grupo: '(+) M.I. - Agrícola própria',
        nivel: 2,
        unidade: 'moeda',
        editavel: true,
      },
      {
        linha: 56,
        rotulo: '(+) M.I. - Agrícola arrendada',
        grupo: 'Receita',
        nivel: 1,
        unidade: 'moeda',
        eTotal: true,
      },
      {
        linha: 57,
        rotulo: '(+) Soja - Arrendada',
        grupo: '(+) M.I. - Agrícola arrendada',
        nivel: 2,
        unidade: 'moeda',
      },
      {
        linha: 58,
        rotulo: '(+) Milho - Arrendada',
        grupo: '(+) M.I. - Agrícola arrendada',
        nivel: 2,
        unidade: 'moeda',
      },
      {
        linha: 59,
        rotulo: '(+) Algodão - Arrendada',
        grupo: '(+) M.I. - Agrícola arrendada',
        nivel: 2,
        unidade: 'moeda',
      },
      {
        linha: 60,
        rotulo: '(+) Milheto - Arrendada',
        grupo: '(+) M.I. - Agrícola arrendada',
        nivel: 2,
        unidade: 'moeda',
      },
      {
        linha: 61,
        rotulo: '(+) Sorgo - Arrendada',
        grupo: '(+) M.I. - Agrícola arrendada',
        nivel: 2,
        unidade: 'moeda',
      },
      {
        linha: 62,
        rotulo: '(+) Arroz - Arrendada',
        grupo: '(+) M.I. - Agrícola arrendada',
        nivel: 2,
        unidade: 'moeda',
      },
      {
        linha: 63,
        rotulo: '(+) Feijão - Arrendada',
        grupo: '(+) M.I. - Agrícola arrendada',
        nivel: 2,
        unidade: 'moeda',
      },
      {
        linha: 64,
        rotulo: '(+) Sementes - Arrendada',
        grupo: '(+) M.I. - Agrícola arrendada',
        nivel: 2,
        unidade: 'moeda',
      },
      {
        linha: 65,
        rotulo: '(+) Gado (cria/recria) - Arrendada',
        grupo: '(+) M.I. - Agrícola arrendada',
        nivel: 2,
        unidade: 'moeda',
      },
      {
        linha: 66,
        rotulo: '(+) Gado (abate) - Arrendada',
        grupo: '(+) M.I. - Agrícola arrendada',
        nivel: 2,
        unidade: 'moeda',
      },
      {
        linha: 67,
        rotulo: '(+) Outros: especificar - Arrendada',
        grupo: '(+) M.I. - Agrícola arrendada',
        nivel: 2,
        unidade: 'moeda',
        editavel: true,
      },
      {
        linha: 68,
        rotulo: '(+) M.E. - Agrícola própria',
        grupo: 'Receita',
        nivel: 1,
        unidade: 'moeda',
        eTotal: true,
      },
      {
        linha: 69,
        rotulo: '(+) Soja - Própria',
        grupo: '(+) M.E. - Agrícola própria',
        nivel: 2,
        unidade: 'moeda',
      },
      {
        linha: 70,
        rotulo: '(+) Milho - Própria',
        grupo: '(+) M.E. - Agrícola própria',
        nivel: 2,
        unidade: 'moeda',
      },
      {
        linha: 71,
        rotulo: '(+) Algodão - Própria',
        grupo: '(+) M.E. - Agrícola própria',
        nivel: 2,
        unidade: 'moeda',
      },
      {
        linha: 72,
        rotulo: '(+) Outros: especificar - Própria',
        grupo: '(+) M.E. - Agrícola própria',
        nivel: 2,
        unidade: 'moeda',
        editavel: true,
      },
      {
        linha: 73,
        rotulo: '(+) M.E. - Agrícola arrendada',
        grupo: 'Receita',
        nivel: 1,
        unidade: 'moeda',
        eTotal: true,
      },
      {
        linha: 74,
        rotulo: '(+) Soja - Arrendada',
        grupo: '(+) M.E. - Agrícola arrendada',
        nivel: 2,
        unidade: 'moeda',
      },
      {
        linha: 75,
        rotulo: '(+) Milho - Arrendada',
        grupo: '(+) M.E. - Agrícola arrendada',
        nivel: 2,
        unidade: 'moeda',
      },
      {
        linha: 76,
        rotulo: '(+) Algodão - Arrendada',
        grupo: '(+) M.E. - Agrícola arrendada',
        nivel: 2,
        unidade: 'moeda',
      },
      {
        linha: 77,
        rotulo: '(+) Outros: especificar - Arrendada',
        grupo: '(+) M.E. - Agrícola arrendada',
        nivel: 2,
        unidade: 'moeda',
        editavel: true,
      },
      {
        linha: 78,
        rotulo: '(+) M.I. - Beneficiamento',
        grupo: 'Receita',
        nivel: 1,
        unidade: 'moeda',
        eTotal: true,
      },
      {
        linha: 79,
        rotulo: '(+) Soja grãos',
        grupo: '(+) M.I. - Beneficiamento',
        nivel: 2,
        unidade: 'moeda',
      },
      {
        linha: 80,
        rotulo: '(+) Milho grãos',
        grupo: '(+) M.I. - Beneficiamento',
        nivel: 2,
        unidade: 'moeda',
      },
      {
        linha: 81,
        rotulo: '(+) Algodão pluma',
        grupo: '(+) M.I. - Beneficiamento',
        nivel: 2,
        unidade: 'moeda',
      },
      {
        linha: 82,
        rotulo: '(+) Sementes',
        grupo: '(+) M.I. - Beneficiamento',
        nivel: 2,
        unidade: 'moeda',
      },
      {
        linha: 83,
        rotulo: '(+) M.I. - Outras receitas',
        grupo: 'Receita',
        nivel: 1,
        unidade: 'moeda',
        eTotal: true,
      },
      {
        linha: 84,
        rotulo: '(+) Ganho na venda de imobilizado (Bens da atividade rural)',
        grupo: '(+) M.I. - Outras receitas',
        nivel: 2,
        unidade: 'moeda',
      },
      {
        linha: 85,
        rotulo:
          '(+) Outros: especificar (ex. distribuição de lucros de outras sociedades; eventuais venda de insumos agrícolas, etc)',
        grupo: '(+) M.I. - Outras receitas',
        nivel: 2,
        unidade: 'moeda',
        editavel: true,
      },
      { linha: 86, rotulo: '(-) Custos', nivel: 0, unidade: 'moeda', eTotal: true },
      {
        linha: 87,
        rotulo: '(-) Defensivos - Própria',
        grupo: '(-) Custos',
        nivel: 1,
        unidade: 'moeda',
      },
      {
        linha: 88,
        rotulo: '(-) Defensivos - Arrendada',
        grupo: '(-) Custos',
        nivel: 1,
        unidade: 'moeda',
      },
      {
        linha: 89,
        rotulo: '(-) Fertilizantes e sais minerais - Própria',
        grupo: '(-) Custos',
        nivel: 1,
        unidade: 'moeda',
      },
      {
        linha: 90,
        rotulo: '(-) Fertilizantes e sais minerais - Arrendada',
        grupo: '(-) Custos',
        nivel: 1,
        unidade: 'moeda',
      },
      {
        linha: 91,
        rotulo: '(-) Sementes - Própria',
        grupo: '(-) Custos',
        nivel: 1,
        unidade: 'moeda',
      },
      {
        linha: 92,
        rotulo: '(-) Sementes - Arrendada',
        grupo: '(-) Custos',
        nivel: 1,
        unidade: 'moeda',
      },
      {
        linha: 93,
        rotulo: '(-) Máquinas/Equip. (aquisições)',
        grupo: '(-) Custos',
        nivel: 1,
        unidade: 'moeda',
      },
      {
        linha: 94,
        rotulo: '(-) Máquinas/Equip. (serviços)',
        grupo: '(-) Custos',
        nivel: 1,
        unidade: 'moeda',
      },
      {
        linha: 95,
        rotulo: '(-) Pecuária - DDG, uréia, sais, caroço e torta',
        grupo: '(-) Custos',
        nivel: 1,
        unidade: 'moeda',
      },
      {
        linha: 96,
        rotulo: '(-) Reposição de cabeças de gado (reprodução/recria/bezerro)',
        grupo: '(-) Custos',
        nivel: 1,
        unidade: 'moeda',
      },
      {
        linha: 97,
        rotulo: '(-) Reposição de cabeças de gado (boi magro/garrote)',
        grupo: '(-) Custos',
        nivel: 1,
        unidade: 'moeda',
      },
      {
        linha: 98,
        rotulo: '(-) Custos com cria do gado',
        grupo: '(-) Custos',
        nivel: 1,
        unidade: 'moeda',
      },
      {
        linha: 99,
        rotulo: '(-) Consultoria agronômica',
        grupo: '(-) Custos',
        nivel: 1,
        unidade: 'moeda',
      },
      {
        linha: 100,
        rotulo: '(-) Despesas com avião agrícola',
        grupo: '(-) Custos',
        nivel: 1,
        unidade: 'moeda',
      },
      {
        linha: 101,
        rotulo: '(-) Manutenção de estradas',
        grupo: '(-) Custos',
        nivel: 1,
        unidade: 'moeda',
      },
      {
        linha: 102,
        rotulo: '(-) Combustível (Diesel, gasolina, energia, etc)',
        grupo: '(-) Custos',
        nivel: 1,
        unidade: 'moeda',
      },
      {
        linha: 103,
        rotulo: '(-) Beneficiamento de sementes',
        grupo: '(-) Custos',
        nivel: 1,
        unidade: 'moeda',
      },
      {
        linha: 104,
        rotulo: '(-) Tributos e contribuições',
        grupo: '(-) Custos',
        nivel: 1,
        unidade: 'moeda',
      },
      {
        linha: 105,
        rotulo: '(-) Arrendamento não declarados',
        grupo: '(-) Custos',
        nivel: 1,
        unidade: 'moeda',
      },
      {
        linha: 106,
        rotulo: '(-) Arrendamento declarados',
        grupo: '(-) Custos',
        nivel: 1,
        unidade: 'moeda',
      },
      {
        linha: 107,
        rotulo: '(-) Fol. Pgto - Própria - Agrícola',
        grupo: '(-) Custos',
        nivel: 1,
        unidade: 'moeda',
      },
      {
        linha: 108,
        rotulo: '(-) Fol. Pgto - Arrendada - Agrícola',
        grupo: '(-) Custos',
        nivel: 1,
        unidade: 'moeda',
      },
      {
        linha: 109,
        rotulo: '(-) Fol. Pgto - Beneficiamento',
        grupo: '(-) Custos',
        nivel: 1,
        unidade: 'moeda',
      },
      {
        linha: 110,
        rotulo: '(-) Outros: especificar',
        grupo: '(-) Custos',
        nivel: 1,
        unidade: 'moeda',
        editavel: true,
      },
      {
        linha: 111,
        rotulo: '(-) Despesas administrativas',
        nivel: 0,
        unidade: 'moeda',
        eTotal: true,
      },
      {
        linha: 112,
        rotulo: '(-) Comerciais (comissões)',
        grupo: '(-) Despesas administrativas',
        nivel: 1,
        unidade: 'moeda',
      },
      {
        linha: 113,
        rotulo: '(-) Material de escritório',
        grupo: '(-) Despesas administrativas',
        nivel: 1,
        unidade: 'moeda',
      },
      {
        linha: 114,
        rotulo: '(-) Copa e cozinha',
        grupo: '(-) Despesas administrativas',
        nivel: 1,
        unidade: 'moeda',
      },
      {
        linha: 115,
        rotulo: '(-) Honorários contábeis/advocatícios',
        grupo: '(-) Despesas administrativas',
        nivel: 1,
        unidade: 'moeda',
      },
      {
        linha: 116,
        rotulo: '(-) Telefone/internet',
        grupo: '(-) Despesas administrativas',
        nivel: 1,
        unidade: 'moeda',
      },
      {
        linha: 117,
        rotulo: '(-) Água',
        grupo: '(-) Despesas administrativas',
        nivel: 1,
        unidade: 'moeda',
      },
      {
        linha: 118,
        rotulo: '(-) Outros: especificar',
        grupo: '(-) Despesas administrativas',
        nivel: 1,
        unidade: 'moeda',
        editavel: true,
      },
      {
        linha: 119,
        rotulo: '(+/-) Resultado financeiro',
        nivel: 0,
        unidade: 'moeda',
        eTotal: true,
      },
      {
        linha: 120,
        rotulo: '(+) Receita financeira',
        grupo: '(+/-) Resultado financeiro',
        nivel: 1,
        unidade: 'moeda',
      },
      {
        linha: 121,
        rotulo: '(-) Despesa financeira (taxas bancárias, juros sobre financiamentos)',
        grupo: '(+/-) Resultado financeiro',
        nivel: 1,
        unidade: 'moeda',
      },
      {
        linha: 122,
        rotulo: '(=) Lucro/Prejuízo do exercício',
        nivel: 0,
        unidade: 'moeda',
        eTotal: true,
      },
    ],
    apuracao: [
      {
        linha: 126,
        rotulo: 'Saldo de prejuízo a compensar de exercício(s) anterior(es)',
        nivel: 1,
        unidade: 'moeda',
      },
      { linha: 127, rotulo: 'Resultado do exercício', nivel: 1, unidade: 'moeda' },
      { linha: 128, rotulo: 'Compensação de prejuízo', nivel: 1, unidade: 'moeda' },
      { linha: 129, rotulo: 'Lucro/Prejuízo fiscal do exercício', nivel: 1, unidade: 'moeda' },
      { linha: 130, rotulo: 'Presunção de 20%', nivel: 1, unidade: 'moeda' },
      { linha: 131, rotulo: 'Resultado tributável', nivel: 1, unidade: 'moeda' },
      { linha: 132, rotulo: 'Total a recolher', nivel: 1, unidade: 'moeda' },
      { linha: 133, rotulo: 'Saldo de prejuízo a compensar', nivel: 1, unidade: 'moeda' },
    ],
  },
  {
    nome: 'Cenário 02 (PJxPJ)',
    anos: 20,
    contribuinte: 21,
    dre: [
      { linha: 22, rotulo: 'Receita', nivel: 0, unidade: 'moeda', eTotal: true },
      {
        linha: 23,
        rotulo: '(+) M.I. Arrendamento/Aluguel',
        grupo: 'Receita',
        nivel: 1,
        unidade: 'moeda',
        eTotal: true,
      },
      {
        linha: 24,
        rotulo: '(+) Arrendamento/Aluguel',
        grupo: '(+) M.I. Arrendamento/Aluguel',
        nivel: 2,
        unidade: 'moeda',
      },
      {
        linha: 25,
        rotulo: '(+) M.I. - Agrícola própria',
        grupo: 'Receita',
        nivel: 1,
        unidade: 'moeda',
        eTotal: true,
      },
      {
        linha: 26,
        rotulo: '(+) Soja - Própria',
        grupo: '(+) M.I. - Agrícola própria',
        nivel: 2,
        unidade: 'moeda',
      },
      {
        linha: 27,
        rotulo: '(+) Milho - Própria',
        grupo: '(+) M.I. - Agrícola própria',
        nivel: 2,
        unidade: 'moeda',
      },
      {
        linha: 28,
        rotulo: '(+) Algodão - Própria',
        grupo: '(+) M.I. - Agrícola própria',
        nivel: 2,
        unidade: 'moeda',
      },
      {
        linha: 29,
        rotulo: '(+) Milheto - Própria',
        grupo: '(+) M.I. - Agrícola própria',
        nivel: 2,
        unidade: 'moeda',
      },
      {
        linha: 30,
        rotulo: '(+) Sorgo - Própria',
        grupo: '(+) M.I. - Agrícola própria',
        nivel: 2,
        unidade: 'moeda',
      },
      {
        linha: 31,
        rotulo: '(+) Arroz - Própria',
        grupo: '(+) M.I. - Agrícola própria',
        nivel: 2,
        unidade: 'moeda',
      },
      {
        linha: 32,
        rotulo: '(+) Feijão - Própria',
        grupo: '(+) M.I. - Agrícola própria',
        nivel: 2,
        unidade: 'moeda',
      },
      {
        linha: 33,
        rotulo: '(+) Sementes - Própria',
        grupo: '(+) M.I. - Agrícola própria',
        nivel: 2,
        unidade: 'moeda',
      },
      {
        linha: 34,
        rotulo: '(+) Gado (cria/recria) - Própria',
        grupo: '(+) M.I. - Agrícola própria',
        nivel: 2,
        unidade: 'moeda',
      },
      {
        linha: 35,
        rotulo: '(+) Gado (abate) - Própria',
        grupo: '(+) M.I. - Agrícola própria',
        nivel: 2,
        unidade: 'moeda',
      },
      {
        linha: 36,
        rotulo: '(+) Outros: especificar - Própria',
        grupo: '(+) M.I. - Agrícola própria',
        nivel: 2,
        unidade: 'moeda',
        editavel: true,
      },
      {
        linha: 37,
        rotulo: '(+) M.I. - Agrícola arrendada',
        grupo: 'Receita',
        nivel: 1,
        unidade: 'moeda',
        eTotal: true,
      },
      {
        linha: 38,
        rotulo: '(+) Soja - Arrendada',
        grupo: '(+) M.I. - Agrícola arrendada',
        nivel: 2,
        unidade: 'moeda',
      },
      {
        linha: 39,
        rotulo: '(+) Milho - Arrendada',
        grupo: '(+) M.I. - Agrícola arrendada',
        nivel: 2,
        unidade: 'moeda',
      },
      {
        linha: 40,
        rotulo: '(+) Algodão - Arrendada',
        grupo: '(+) M.I. - Agrícola arrendada',
        nivel: 2,
        unidade: 'moeda',
      },
      {
        linha: 41,
        rotulo: '(+) Milheto - Arrendada',
        grupo: '(+) M.I. - Agrícola arrendada',
        nivel: 2,
        unidade: 'moeda',
      },
      {
        linha: 42,
        rotulo: '(+) Sorgo - Arrendada',
        grupo: '(+) M.I. - Agrícola arrendada',
        nivel: 2,
        unidade: 'moeda',
      },
      {
        linha: 43,
        rotulo: '(+) Arroz - Arrendada',
        grupo: '(+) M.I. - Agrícola arrendada',
        nivel: 2,
        unidade: 'moeda',
      },
      {
        linha: 44,
        rotulo: '(+) Feijão - Arrendada',
        grupo: '(+) M.I. - Agrícola arrendada',
        nivel: 2,
        unidade: 'moeda',
      },
      {
        linha: 45,
        rotulo: '(+) Sementes - Arrendada',
        grupo: '(+) M.I. - Agrícola arrendada',
        nivel: 2,
        unidade: 'moeda',
      },
      {
        linha: 46,
        rotulo: '(+) Gado (cria/recria) - Arrendada',
        grupo: '(+) M.I. - Agrícola arrendada',
        nivel: 2,
        unidade: 'moeda',
      },
      {
        linha: 47,
        rotulo: '(+) Gado (abate) - Arrendada',
        grupo: '(+) M.I. - Agrícola arrendada',
        nivel: 2,
        unidade: 'moeda',
      },
      {
        linha: 48,
        rotulo: '(+) Outros: especificar - Arrendada',
        grupo: '(+) M.I. - Agrícola arrendada',
        nivel: 2,
        unidade: 'moeda',
        editavel: true,
      },
      {
        linha: 49,
        rotulo: '(+) M.E. - Agrícola própria',
        grupo: 'Receita',
        nivel: 1,
        unidade: 'moeda',
        eTotal: true,
      },
      {
        linha: 50,
        rotulo: '(+) Soja - Própria',
        grupo: '(+) M.E. - Agrícola própria',
        nivel: 2,
        unidade: 'moeda',
      },
      {
        linha: 51,
        rotulo: '(+) Milho - Própria',
        grupo: '(+) M.E. - Agrícola própria',
        nivel: 2,
        unidade: 'moeda',
      },
      {
        linha: 52,
        rotulo: '(+) Algodão - Própria',
        grupo: '(+) M.E. - Agrícola própria',
        nivel: 2,
        unidade: 'moeda',
      },
      {
        linha: 53,
        rotulo: '(+) Outros: especificar - Própria',
        grupo: '(+) M.E. - Agrícola própria',
        nivel: 2,
        unidade: 'moeda',
        editavel: true,
      },
      {
        linha: 54,
        rotulo: '(+) M.E. - Agrícola arrendada',
        grupo: 'Receita',
        nivel: 1,
        unidade: 'moeda',
        eTotal: true,
      },
      {
        linha: 55,
        rotulo: '(+) Soja - Arrendada',
        grupo: '(+) M.E. - Agrícola arrendada',
        nivel: 2,
        unidade: 'moeda',
      },
      {
        linha: 56,
        rotulo: '(+) Milho - Arrendada',
        grupo: '(+) M.E. - Agrícola arrendada',
        nivel: 2,
        unidade: 'moeda',
      },
      {
        linha: 57,
        rotulo: '(+) Algodão - Arrendada',
        grupo: '(+) M.E. - Agrícola arrendada',
        nivel: 2,
        unidade: 'moeda',
      },
      {
        linha: 58,
        rotulo: '(+) Outros: especificar - Arrendada',
        grupo: '(+) M.E. - Agrícola arrendada',
        nivel: 2,
        unidade: 'moeda',
        editavel: true,
      },
      {
        linha: 59,
        rotulo: '(+) M.I. - Beneficiamento',
        grupo: 'Receita',
        nivel: 1,
        unidade: 'moeda',
        eTotal: true,
      },
      {
        linha: 60,
        rotulo: '(+) Soja grãos',
        grupo: '(+) M.I. - Beneficiamento',
        nivel: 2,
        unidade: 'moeda',
      },
      {
        linha: 61,
        rotulo: '(+) Milho grãos',
        grupo: '(+) M.I. - Beneficiamento',
        nivel: 2,
        unidade: 'moeda',
      },
      {
        linha: 62,
        rotulo: '(+) Algodão pluma',
        grupo: '(+) M.I. - Beneficiamento',
        nivel: 2,
        unidade: 'moeda',
      },
      {
        linha: 63,
        rotulo: '(+) Sementes',
        grupo: '(+) M.I. - Beneficiamento',
        nivel: 2,
        unidade: 'moeda',
      },
      {
        linha: 64,
        rotulo: '(+) M.I. - Outras receitas',
        grupo: 'Receita',
        nivel: 1,
        unidade: 'moeda',
        eTotal: true,
      },
      {
        linha: 65,
        rotulo: '(+) Ganho na venda de imobilizado (Bens da atividade rural)',
        grupo: '(+) M.I. - Outras receitas',
        nivel: 2,
        unidade: 'moeda',
      },
      {
        linha: 66,
        rotulo:
          '(+) Outros: especificar (ex. distribuição de lucros de outras sociedades; eventuais venda de insumos agrícolas, etc)',
        grupo: '(+) M.I. - Outras receitas',
        nivel: 2,
        unidade: 'moeda',
        editavel: true,
      },
      { linha: 67, rotulo: '(-) Custos', nivel: 0, unidade: 'moeda', eTotal: true },
      {
        linha: 68,
        rotulo: '(-) Defensivos - Própria',
        grupo: '(-) Custos',
        nivel: 1,
        unidade: 'moeda',
      },
      {
        linha: 69,
        rotulo: '(-) Defensivos - Arrendada',
        grupo: '(-) Custos',
        nivel: 1,
        unidade: 'moeda',
      },
      {
        linha: 70,
        rotulo: '(-) Fertilizantes e sais minerais - Própria',
        grupo: '(-) Custos',
        nivel: 1,
        unidade: 'moeda',
      },
      {
        linha: 71,
        rotulo: '(-) Fertilizantes e sais minerais - Arrendada',
        grupo: '(-) Custos',
        nivel: 1,
        unidade: 'moeda',
      },
      {
        linha: 72,
        rotulo: '(-) Sementes - Própria',
        grupo: '(-) Custos',
        nivel: 1,
        unidade: 'moeda',
      },
      {
        linha: 73,
        rotulo: '(-) Sementes - Arrendada',
        grupo: '(-) Custos',
        nivel: 1,
        unidade: 'moeda',
      },
      {
        linha: 74,
        rotulo: '(-) Máquinas/Equip. (aquisições)',
        grupo: '(-) Custos',
        nivel: 1,
        unidade: 'moeda',
      },
      {
        linha: 75,
        rotulo: '(-) Máquinas/Equip. (serviços)',
        grupo: '(-) Custos',
        nivel: 1,
        unidade: 'moeda',
      },
      {
        linha: 76,
        rotulo: '(-) Pecuária - DDG, uréia, sais, caroço e torta',
        grupo: '(-) Custos',
        nivel: 1,
        unidade: 'moeda',
      },
      {
        linha: 77,
        rotulo: '(-) Reposição de cabeças de gado (reprodução/recria/bezerro)',
        grupo: '(-) Custos',
        nivel: 1,
        unidade: 'moeda',
      },
      {
        linha: 78,
        rotulo: '(-) Reposição de cabeças de gado (boi magro/garrote)',
        grupo: '(-) Custos',
        nivel: 1,
        unidade: 'moeda',
      },
      {
        linha: 79,
        rotulo: '(-) Custos com cria do gado',
        grupo: '(-) Custos',
        nivel: 1,
        unidade: 'moeda',
      },
      {
        linha: 80,
        rotulo: '(-) Consultoria agronômica',
        grupo: '(-) Custos',
        nivel: 1,
        unidade: 'moeda',
      },
      {
        linha: 81,
        rotulo: '(-) Despesas com avião agrícola',
        grupo: '(-) Custos',
        nivel: 1,
        unidade: 'moeda',
      },
      {
        linha: 82,
        rotulo: '(-) Manutenção de estradas',
        grupo: '(-) Custos',
        nivel: 1,
        unidade: 'moeda',
      },
      {
        linha: 83,
        rotulo: '(-) Combustível (Diesel, gasolina, energia, etc)',
        grupo: '(-) Custos',
        nivel: 1,
        unidade: 'moeda',
      },
      {
        linha: 84,
        rotulo: '(-) Beneficiamento de sementes',
        grupo: '(-) Custos',
        nivel: 1,
        unidade: 'moeda',
      },
      {
        linha: 85,
        rotulo: '(-) Tributos e contribuições',
        grupo: '(-) Custos',
        nivel: 1,
        unidade: 'moeda',
      },
      {
        linha: 86,
        rotulo: '(-) Arrendamento não declarados',
        grupo: '(-) Custos',
        nivel: 1,
        unidade: 'moeda',
      },
      {
        linha: 87,
        rotulo: '(-) Arrendamento declarados',
        grupo: '(-) Custos',
        nivel: 1,
        unidade: 'moeda',
      },
      {
        linha: 88,
        rotulo: '(-) Fol. Pgto - Própria - Agrícola',
        grupo: '(-) Custos',
        nivel: 1,
        unidade: 'moeda',
      },
      {
        linha: 89,
        rotulo: '(-) Fol. Pgto - Arrendada - Agrícola',
        grupo: '(-) Custos',
        nivel: 1,
        unidade: 'moeda',
      },
      {
        linha: 90,
        rotulo: '(-) Fol. Pgto - Beneficiamento',
        grupo: '(-) Custos',
        nivel: 1,
        unidade: 'moeda',
      },
      {
        linha: 91,
        rotulo: '(-) Outros: especificar',
        grupo: '(-) Custos',
        nivel: 1,
        unidade: 'moeda',
        editavel: true,
      },
      {
        linha: 92,
        rotulo: '(-) Despesas administrativas',
        nivel: 0,
        unidade: 'moeda',
        eTotal: true,
      },
      {
        linha: 93,
        rotulo: '(-) Comerciais (comissões)',
        grupo: '(-) Despesas administrativas',
        nivel: 1,
        unidade: 'moeda',
      },
      {
        linha: 94,
        rotulo: '(-) Material de escritório',
        grupo: '(-) Despesas administrativas',
        nivel: 1,
        unidade: 'moeda',
      },
      {
        linha: 95,
        rotulo: '(-) Copa e cozinha',
        grupo: '(-) Despesas administrativas',
        nivel: 1,
        unidade: 'moeda',
      },
      {
        linha: 96,
        rotulo: '(-) Honorários contábeis/advocatícios',
        grupo: '(-) Despesas administrativas',
        nivel: 1,
        unidade: 'moeda',
      },
      {
        linha: 97,
        rotulo: '(-) Telefone/internet',
        grupo: '(-) Despesas administrativas',
        nivel: 1,
        unidade: 'moeda',
      },
      {
        linha: 98,
        rotulo: '(-) Água',
        grupo: '(-) Despesas administrativas',
        nivel: 1,
        unidade: 'moeda',
      },
      {
        linha: 99,
        rotulo: '(-) Outros: especificar',
        grupo: '(-) Despesas administrativas',
        nivel: 1,
        unidade: 'moeda',
        editavel: true,
      },
      {
        linha: 100,
        rotulo: '(+/-) Resultado financeiro',
        nivel: 0,
        unidade: 'moeda',
        eTotal: true,
      },
      {
        linha: 101,
        rotulo: '(+) Receita financeira',
        grupo: '(+/-) Resultado financeiro',
        nivel: 1,
        unidade: 'moeda',
      },
      {
        linha: 102,
        rotulo: '(-) Despesa financeira (taxas bancárias, juros sobre financiamentos)',
        grupo: '(+/-) Resultado financeiro',
        nivel: 1,
        unidade: 'moeda',
      },
      {
        linha: 103,
        rotulo: '(=) Lucro/Prejuízo do exercício',
        nivel: 0,
        unidade: 'moeda',
        eTotal: true,
      },
    ],
    apuracao: [],
  },
];

/**
 * A aba de Venda de Ativos, origem do slide de Transferência da Atividade Rural.
 *
 * Responde quanto de IRPF sobra se o produtor vender bens para pagar as dívidas.
 * A conta olha o cronograma de amortização da dívida e, para cada ano, realiza só
 * o tanto de bem que cobre a parcela daquele ano, o que faz a apuração correr
 * sete anos em vez dos três do estudo.
 *
 * **Estava fora do mapa até a versão 1.4.** O gerador descarta aba de cenário com
 * "Venda" no nome, e o documento em prosa apontava este slide para a apuração de
 * dentro das abas de cenário, que é outra coisa: aquela é o IRPF da operação
 * normal, esta é o da venda.
 */
export const ABA_VENDA_DE_ATIVOS: AbaVendaDeAtivosWp = {
  nome: 'Cenário 02 (Venda de Ativos)',
  cabecalhoValores: 18,
  colunaDoValor: 'C',
  valores: [
    { linha: 19, rotulo: 'Bens da atividade rural', nivel: 1, unidade: 'moeda' },
    { linha: 20, rotulo: 'Dívidas da atividade rural', nivel: 1, unidade: 'moeda' },
    { linha: 21, rotulo: 'Diferença', nivel: 0, unidade: 'moeda', eTotal: true },
  ],
  anos: 24,
  colunas: ['C', 'D', 'E', 'F', 'G', 'H', 'I'],
  apuracao: [
    {
      linha: 25,
      rotulo: 'Saldo de prejuízo a compensar de exercício(s) anterior(es)',
      nivel: 1,
      unidade: 'moeda',
    },
    { linha: 26, rotulo: 'Resultado do exercício', nivel: 1, unidade: 'moeda' },
    { linha: 27, rotulo: 'Compensação de prejuízo', nivel: 1, unidade: 'moeda' },
    { linha: 28, rotulo: 'Lucro/Prejuízo fiscal do exercício', nivel: 1, unidade: 'moeda' },
    { linha: 29, rotulo: 'Presunção de 20%', nivel: 1, unidade: 'moeda' },
    { linha: 30, rotulo: 'Resultado tributável', nivel: 1, unidade: 'moeda' },
    { linha: 31, rotulo: 'Total a recolher', nivel: 1, unidade: 'moeda' },
    { linha: 32, rotulo: 'Saldo de prejuízo a compensar', nivel: 1, unidade: 'moeda' },
  ],
};

export const ABAS_DE_APOIO: AbaApoioWp[] = [
  {
    nome: 'Imóveis Explorados',
    cabecalho: 7,
    colunas: [
      { coluna: 'B', rotulo: 'Denominação' },
      { coluna: 'C', rotulo: 'Matrícula' },
      { coluna: 'D', rotulo: 'Município' },
      { coluna: 'E', rotulo: 'Área Explorada (Ha)' },
      { coluna: 'F', rotulo: 'Tipo de Exploração' },
      { coluna: 'G', rotulo: 'Proprietário' },
      { coluna: 'H', rotulo: 'Participante(s)' },
      { coluna: 'I', rotulo: 'Percentual Parceria / Valor Arrendamento' },
    ],
  },
  {
    nome: 'Bens da Atv. Rural',
    cabecalho: 7,
    colunas: [
      { coluna: 'B', rotulo: 'Contribuinte' },
      { coluna: 'C', rotulo: 'Código' },
      { coluna: 'D', rotulo: 'Categoria' },
      { coluna: 'E', rotulo: 'Descrição' },
      { coluna: 'F', rotulo: 'Situação em 31/12/2024' },
    ],
  },
  {
    nome: 'Dívidas da Atv. Rural',
    cabecalho: 7,
    colunas: [
      { coluna: 'B', rotulo: 'Instituição Financeira' },
      { coluna: 'C', rotulo: 'Titularidade' },
      { coluna: 'D', rotulo: 'Finalidade' },
      { coluna: 'E', rotulo: 'Moeda' },
      { coluna: 'F', rotulo: 'Taxa de Juros (%)' },
      { coluna: 'G', rotulo: 'Data do Vencimento Final' },
      { coluna: 'H', rotulo: 'Total do Saldo Devedor' },
      { coluna: 'I', rotulo: '2026' },
      { coluna: 'J', rotulo: '2027' },
      { coluna: 'K', rotulo: '2028' },
      { coluna: 'L', rotulo: '2029' },
      { coluna: 'M', rotulo: '2030' },
      { coluna: 'N', rotulo: '2031' },
      { coluna: 'O', rotulo: '2032' },
      { coluna: 'P', rotulo: 'Total' },
    ],
  },
];

/**
 * As validações do mapa, em forma declarativa para o validador aplicar sem
 * conhecer o domínio. Todas foram conferidas contra número real do par Grupo
 * Bahia Potrich; ver a seção "Validações" do `PT-01-mapa-do-wp.md`.
 */
export const VALIDACOES: ValidacaoWp[] = [
  { tipo: 'soma_do_grupo', aba: 'Resumo', grupo: 'pessoa_fisica' },
  { tipo: 'soma_do_grupo', aba: 'Resumo', grupo: 'pj_lucro_presumido' },
  { tipo: 'soma_do_grupo', aba: 'Resumo', grupo: 'pj_lucro_real' },
  {
    tipo: 'soma_de_rotulos',
    aba: 'Resumo',
    total: 'Total',
    partes: ['Pessoa Física', 'PJ - Lucro Presumido', 'PJ - Lucro Real'],
  },
  /*
   * A presunção sai da RECEITA nas abas de cenário, conferido nas fórmulas do
   * modelo (`Cenário Atual (PF)` C120 = `C31*20%`, e C31 é a linha `Receita`) e no
   * WP da Família Lunardi, onde 20% de 39.627.025,54 dá os 7.925.405,11 lançados.
   *
   * **Cada aba declara a sua base, e nenhuma regra vale por omissão.** A Venda de
   * Ativos usa outra (C29 = `C26*20%`, o resultado do exercício), e uma regra sem
   * escopo cairia sobre ela no dia em que aparecesse ali uma linha chamada
   * `Receita`. O `Cenário 02 (PJxPJ)` não entra porque não tem apuração: sem
   * pessoa física não há IRPF a apurar.
   */
  {
    tipo: 'proporcao',
    de: 'Presunção de 20%',
    sobre: 'Receita',
    fator: 0.2,
    cenario: 'Cenário Atual (PF)',
  },
  {
    tipo: 'proporcao',
    de: 'Presunção de 20%',
    sobre: 'Receita',
    fator: 0.2,
    cenario: 'Cenário 01 (PFxPJ)',
  },
  {
    tipo: 'proporcao',
    de: 'Presunção de 20%',
    sobre: 'Resultado do exercício',
    fator: 0.2,
    cenario: 'Cenário 02 (Venda de Ativos)',
  },
  // O imposto incide sobre o resultado tributável, que é o menor entre lucro
  // fiscal e presunção, não sobre a presunção. Vale nas duas formas de apuração.
  { tipo: 'proporcao', de: 'Total a recolher', sobre: 'Resultado tributável', fator: 0.275 },
  { tipo: 'zero_antes_de', rotulo: 'CBS (a partir de 2027)', ano: 2027 },
];
