-- ============================================================================
-- 20260606100001_osg_v5_processes_and_stages.sql
-- ----------------------------------------------------------------------------
-- Parte 2/3 da migração v5: gargalos canônicos + 33 processos + ~170 etapas.
-- Pré-requisito: 20260606100000_osg_v5_full_remap.sql (limpa OSG, insere
-- projects, documentos, sistemas, sistema_clusters).
--
-- IDs derivados via mapa_uuid(slug) (mesmo helper da parte 1).
-- ============================================================================

BEGIN;

-- ============================================================================
-- 7. GARGALOS — 30 canônicos consolidados (origens: Interno · Cliente · Órgão externo)
-- ============================================================================
INSERT INTO public.gargalos
  (id, nome, descricao, origem, cluster_id, created_at, updated_at)
VALUES
  (mapa_uuid('gar-osg-dp-sem-revisao'),
   'DP sem revisão de par',
   'O Diagnóstico Patrimonial é executado por uma única pessoa, sem segunda leitura obrigatória. Erros de classificação ou de identificação de ônus se propagam para todos os documentos derivados (contratos sociais, alterações contratuais, anexos agrários, instrumento de doação).',
   'Interno', '0523512c-f980-4236-8a7c-53e06c9c7a80', NOW(), NOW()),
  (mapa_uuid('gar-osg-leitura-matricula-manual'),
   'Leitura manual de matrícula ponta a ponta',
   'A leitura de averbações para detectar ônus e impedimentos é inteiramente manual. Quem interrompe a leitura no meio pode marcar como onerado um imóvel cujo ônus já foi cancelado em averbação posterior. Risco amplificado em clientes com alto volume de imóveis.',
   'Interno', '0523512c-f980-4236-8a7c-53e06c9c7a80', NOW(), NOW()),
  (mapa_uuid('gar-osg-devolutiva-cliente'),
   'Devolutiva do cliente atrasa o início',
   'O envio dos documentos preliminares pelo cliente (IR, matrículas, CCIR, IPTU, escrituras, documentos pessoais) é o maior atraso do início do projeto. Sem documentação completa, o DP não fecha e o trabalho dependente não avança.',
   'Cliente', '0523512c-f980-4236-8a7c-53e06c9c7a80', NOW(), NOW()),
  (mapa_uuid('gar-osg-matricula-desatualizada'),
   'Matrícula desatualizada (em nome de terceiro ou falecido)',
   'Quando a matrícula não reflete o proprietário atual, integraliza-se pelos direitos da escritura ou contrato particular de compra e venda, com remissão à matrícula. O princípio da continuidade impede transferir o que não está em nome do titular.',
   'Órgão externo', '0523512c-f980-4236-8a7c-53e06c9c7a80', NOW(), NOW()),
  (mapa_uuid('gar-osg-bens-nao-declarados-ir'),
   'Bens com matrícula não declarados no IR',
   'Há imóveis com matrícula que não constam na declaração do IR do cliente. O cliente informa o valor contábil por e-mail e o registro fica no DP com observação para inclusão no próximo exercício.',
   'Cliente', '0523512c-f980-4236-8a7c-53e06c9c7a80', NOW(), NOW()),
  (mapa_uuid('gar-osg-doc-disperso-sem-padrao'),
   'Documentos dispersos e padrão de salvamento não seguido',
   'Existe manual de cadastro no Docbox mas a aderência é parcial. DPs e documentos ficam espalhados entre Docbox, e-mail, WhatsApp e Drive, sem centralização que dispare tarefa automática quando algo muda.',
   'Interno', '0523512c-f980-4236-8a7c-53e06c9c7a80', NOW(), NOW()),
  (mapa_uuid('gar-osg-cascata-acs'),
   'Cascata de alterações contratuais simultâneas',
   'Uma única matrícula nova muda área, valor contábil e denominação, disparando alterações contratuais em todas as PJs da estrutura (Agro + Participações + holdings individuais). Em estruturas multi-PJ chega a 5 a 8 alterações simultâneas que precisam ser coordenadas.',
   'Interno', '0523512c-f980-4236-8a7c-53e06c9c7a80', NOW(), NOW()),
  (mapa_uuid('gar-osg-troca-caracteres'),
   'Múltiplas camadas de revisão e troca de caracteres na minuta',
   'A minuta passa por várias camadas de revisão e a maior parte do esforço se concentra em troca de caracteres e ajustes pontuais. Elabora-se pouco e revisa-se muito, especialmente em ciclos com devolutivas do cliente.',
   'Interno', '0523512c-f980-4236-8a7c-53e06c9c7a80', NOW(), NOW()),
  (mapa_uuid('gar-osg-erro-limite-confrontacao'),
   'Erro em limites e confrontações vira exigência cartorial',
   'O cartório confere a descrição da matrícula caractere por caractere. Qualquer erro de transcrição (incluindo símbolos como º vs O) gera nota devolutiva e obriga a elaborar uma alteração contratual adicional só para corrigir a descrição.',
   'Órgão externo', '0523512c-f980-4236-8a7c-53e06c9c7a80', NOW(), NOW()),
  (mapa_uuid('gar-osg-assistente-nao-reabre-dp'),
   'Assistente não reabre o DP para conferir',
   'Durante a elaboração de minutas, o executor pode trabalhar a partir de memória ou de uma versão antiga do DP em vez de reabrir o DP atualizado. Diferenças entre a matrícula vigente e o DP propagam para o contrato e geram retrabalho.',
   'Interno', '0523512c-f980-4236-8a7c-53e06c9c7a80', NOW(), NOW()),
  (mapa_uuid('gar-osg-soma-capital-centavos'),
   'Soma do capital social com diferença de centavos',
   'A planilha de Capital Social é montada manualmente em Excel. A soma das quotas pode apresentar diferenças por casas decimais (arredondamento). A divergência de centavos é causa frequente de rejeição cartorial.',
   'Interno', '0523512c-f980-4236-8a7c-53e06c9c7a80', NOW(), NOW()),
  (mapa_uuid('gar-osg-assinatura-gov-br'),
   'Assinatura eletrônica via gov.br trava pela agenda do cliente',
   'A assinatura depende do certificado digital do cliente, que tipicamente fica com a contabilidade. Combinado com agenda dos sócios (viagens) e dificuldade com a plataforma gov.br, a coleta de assinaturas trava o avanço de documentos prontos.',
   'Cliente', '0523512c-f980-4236-8a7c-53e06c9c7a80', NOW(), NOW()),
  (mapa_uuid('gar-osg-aprovacao-modelo-cuba'),
   'Alteração de modelo Word exige aprovação centralizada',
   'Qualquer mudança no modelo-base de contrato depende de aprovação da gerência. Sem versionamento estruturado, mudanças aprovadas podem se perder ou ficar pendentes de propagação ao restante da equipe.',
   'Interno', '0523512c-f980-4236-8a7c-53e06c9c7a80', NOW(), NOW()),
  (mapa_uuid('gar-osg-junta-registro-simultaneo'),
   'Coordenação de registro simultâneo na Junta',
   'O CS Agro e o CS Participações precisam ser registrados em cadeia no mesmo dia. A AC Integralização e a AC Cessão de Cotas também. Atraso ou pendência em um dos documentos trava o registro do outro.',
   'Órgão externo', '0523512c-f980-4236-8a7c-53e06c9c7a80', NOW(), NOW()),
  (mapa_uuid('gar-osg-cliente-confunde-cessao'),
   'Cliente confunde cessão de cotas com transferência de matrícula',
   'O cliente pode entender a cessão de cotas da Agro para a Participações como uma transferência de imóveis, gerando dúvidas e travamento da assinatura mesmo com a minuta pronta. Exige reunião explicativa adicional.',
   'Cliente', '0523512c-f980-4236-8a7c-53e06c9c7a80', NOW(), NOW()),
  (mapa_uuid('gar-osg-atualizacao-cartorial-itbi'),
   'Atualização cartorial atrasa por custo de ITBI',
   'Após o registro da AC Integralização na Junta, é dever do cliente atualizar cada matrícula no cartório do imóvel, pagando ITBI. Por causa do custo, o cliente posterga essa etapa, mantendo as matrículas ainda em nome das PFs por longos períodos.',
   'Cliente', '0523512c-f980-4236-8a7c-53e06c9c7a80', NOW(), NOW()),
  (mapa_uuid('gar-osg-projeto-suspenso-2momento'),
   'Projeto suspenso aguardando saneamento de imóvel de 2º momento',
   'Imóveis classificados como 2º momento aguardam regularização pelo cliente (inventário pendente, regularização ambiental, ônus a sanar). O projeto fica em estado suspenso para esses imóveis até o cliente avisar e enviar a matrícula atualizada.',
   'Cliente', '0523512c-f980-4236-8a7c-53e06c9c7a80', NOW(), NOW()),
  (mapa_uuid('gar-osg-comunicacao-fragmentada'),
   'Comunicação fragmentada entre múltiplos canais',
   'A comunicação interna e com o cliente acontece por múltiplos canais (Slack, Teams, Google Chat, e-mail, WhatsApp) sem plataforma única para abertura e rastreamento de demandas. Solicitações se perdem e o status fica disperso.',
   'Interno', '0523512c-f980-4236-8a7c-53e06c9c7a80', NOW(), NOW()),
  (mapa_uuid('gar-osg-fiscal-sem-visibilidade'),
   'Trabalho do Fiscal não visível para a OSG',
   'O estudo tributário (planejamento rural e ITCMD) é executado pela área Fiscal fora do canal padrão da OSG. A OSG depende da devolutiva para fechar parceria e doação, sem visibilidade do andamento intermediário.',
   'Interno', '0523512c-f980-4236-8a7c-53e06c9c7a80', NOW(), NOW()),
  (mapa_uuid('gar-osg-planilha-cliente-fiscal'),
   'Planilha gerencial enviada pelo cliente com informação fiscal',
   'A OSG solicita ao cliente preenchimento de planilha gerencial (hectares efetivamente explorados, exploradores reais). O cliente às vezes envia dados com finalidade fiscal em vez de gerencial, e o Fiscal precisa contatá-lo diretamente para reconciliar.',
   'Cliente', '0523512c-f980-4236-8a7c-53e06c9c7a80', NOW(), NOW()),
  (mapa_uuid('gar-osg-area-explorada-vs-matricula'),
   'Descasamento entre área da matrícula e área explorada',
   'A área efetivamente explorada (planilha do cliente) costuma diferir da área total da matrícula por reserva legal, APP e áreas não exploradas. O anexo da parceria precisa tratar essa diferença caso a caso.',
   'Cliente', '0523512c-f980-4236-8a7c-53e06c9c7a80', NOW(), NOW()),
  (mapa_uuid('gar-osg-parceria-fachada-rfb'),
   'Risco de parceria de fachada perante a Receita Federal',
   'A parceria 20/80 é atraente tributariamente e alvo recorrente de fiscalização. Sem divisão real de risco entre parceiros, a Receita Federal pode desconsiderar a parceria e tratá-la como arrendamento disfarçado.',
   'Órgão externo', '0523512c-f980-4236-8a7c-53e06c9c7a80', NOW(), NOW()),
  (mapa_uuid('gar-osg-decisao-doacao-lenta'),
   'Decisão do cliente sobre a doação demora',
   'A formalização da doação é tecnicamente tranquila, mas a decisão do cliente sobre fazer ou não a doação é demorada. O peso do patrimônio envolvido e o valor do ITCMD a recolher pesam na demora.',
   'Cliente', '0523512c-f980-4236-8a7c-53e06c9c7a80', NOW(), NOW()),
  (mapa_uuid('gar-osg-itcmd-travamento-judicial'),
   'ITCMD pode travar o projeto indefinidamente',
   'A AC reflexo da doação só pode ser registrada na Junta após a quitação do ITCMD pelo cliente. Quando o cliente opta por contestar judicialmente o valor do ITCMD, a doação não se completa e o projeto fica pendente por anos.',
   'Cliente', '0523512c-f980-4236-8a7c-53e06c9c7a80', NOW(), NOW()),
  (mapa_uuid('gar-osg-clausula-trava-projeto'),
   'Discussão de cláusula trava o projeto por meses',
   'Uma única cláusula sensível (regras de saída, eventos pessoais, pagamento em dinheiro vs em bens) pode obrigar a equipe a se deslocar ao cliente e explicar à família. Cada ciclo de discussão e nova versão pode travar o projeto por meses.',
   'Cliente', '0523512c-f980-4236-8a7c-53e06c9c7a80', NOW(), NOW()),
  (mapa_uuid('gar-osg-governanca-poucos-dominam'),
   'Conhecimento de governança concentrado em poucas pessoas',
   'O pilar de governança é dominado por poucas pessoas do time. A concentração de conhecimento limita a padronização do diagnóstico, do acordo de quotistas e do regimento do conselho, e cria gargalo na revisão final.',
   'Interno', '0523512c-f980-4236-8a7c-53e06c9c7a80', NOW(), NOW()),
  (mapa_uuid('gar-osg-acordo-trava-doacao'),
   'Acordo de Quotistas pode travar a doação',
   'Em alguns projetos a doação só ocorre se o Acordo de Quotistas estiver assinado. Quando o cliente não fecha o Acordo, o encerramento do projeto fica vinculado e pode emperrar indefinidamente.',
   'Cliente', '0523512c-f980-4236-8a7c-53e06c9c7a80', NOW(), NOW()),
  (mapa_uuid('gar-osg-visibilidade-projetos'),
   'Visibilidade insuficiente do andamento dos projetos',
   'O andamento dos projetos é acompanhado por uma mistura de planilha, agenda pessoal, Slack, OpenProject e ferramentas externas. Não há visão consolidada de status, prazos e alocação de equipe disponível para sócios e seniores.',
   'Interno', '0523512c-f980-4236-8a7c-53e06c9c7a80', NOW(), NOW()),
  (mapa_uuid('gar-osg-horas-desacopladas'),
   'Lançamento de horas desacoplado dos projetos',
   'O lançamento de horas é feito em planilha separada do sistema de gestão de projetos. Sem integração entre OpenProject e o sistema de horas, o lançamento atrasa, distorce a medição de ROI e mascara o custo real por projeto.',
   'Interno', '0523512c-f980-4236-8a7c-53e06c9c7a80', NOW(), NOW()),
  (mapa_uuid('gar-osg-overhead-gestao-invisivel'),
   'Overhead de gestão invisível no ROI',
   'O acompanhamento recorrente (reuniões de status, cobrança ao cliente, suporte a notas devolutivas e suporte tributário pós-implementação) consome tempo significativo de coordenação que historicamente não é medido nem alocado a projeto.',
   'Interno', '0523512c-f980-4236-8a7c-53e06c9c7a80', NOW(), NOW());

-- ============================================================================
-- 8. PROCESSES — 33 (v5)
-- Ordem dentro do pilar via order_index. evaluation_status NULL para preenchimento manual.
-- ============================================================================
INSERT INTO public.processes
  (id, project_id, cluster_id, name, description, frequency, complexity_level,
   stage, order_index, deliverable, evaluation_status, created_at, updated_at)
VALUES
  -- P1 — Patrimonial (4)
  (mapa_uuid('prc-osg-p1-01'), mapa_uuid('prj-osg-p1'), '0523512c-f980-4236-8a7c-53e06c9c7a80',
   'P1.01 DP Inicial',
   'Levantamento completo do patrimônio do cliente em uma planilha-mestra (DP). Cruza a declaração de IR (valor contábil), as matrículas (titularidade, área, ônus) e os cadastros CCIR/ITR/IPTU. Lê as averbações de cada matrícula ponta a ponta para detectar impedimentos. Classifica cada bem na coluna integraliza (sim, 1º momento, 2º momento ou não). Registra a titularidade distinguindo propriedade de fato e propriedade de direito. É o entregável que dispara todo o restante do projeto.',
   '1x por projeto', 'Alta', 'discovery', 1,
   'Planilha-mestra DP completa, com titularidade (fato × direito) por matrícula, coluna integraliza classificada e observações referenciando as averbações de cada impedimento',
   NULL, NOW(), NOW()),
  (mapa_uuid('prc-osg-p1-02'), mapa_uuid('prj-osg-p1'), '0523512c-f980-4236-8a7c-53e06c9c7a80',
   'P1.02 Atualização do DP',
   'Revisão recorrente do DP a cada novo documento ou mudança enviada pelo cliente (matrícula atualizada, nova área, ônus sanado, novo imóvel). Reabre tipo do bem, área, valor contábil e denominação; reclassifica a coluna integraliza (tipicamente promovendo imóveis de 2º momento para 1º momento). É o gatilho da cascata de alterações contratuais nas PJs da estrutura.',
   'Recorrente ao longo do projeto', 'Alta', 'discovery', 2,
   'DP versão N+1 atualizado, reclassificação da coluna integraliza e sinalização dos impactos em cascata nos contratos derivados',
   NULL, NOW(), NOW()),
  (mapa_uuid('prc-osg-p1-03'), mapa_uuid('prj-osg-p1'), '0523512c-f980-4236-8a7c-53e06c9c7a80',
   'P1.03 Digitação de Matrícula',
   'Produção do papel de trabalho de digitação de matrícula. Extrai e transcreve a descrição do imóvel (área, denominação, localização, proprietário, código rural ou urbano e os limites e confrontações precisos) a partir da matrícula em PDF, manualmente ou via busca estruturada no SIGEF. O texto alimenta tanto o DP (verificação de área) quanto o preâmbulo dos contratos sociais e os anexos de parceria e composse, onde será copiado caractere por caractere.',
   '1x por imóvel', 'Alta', 'discovery', 3,
   'WP de digitação de matrícula (Word) com limites e confrontações precisos, prontos para serem copiados ao preâmbulo dos contratos e anexos agrários',
   NULL, NOW(), NOW()),
  (mapa_uuid('prc-osg-p1-04'), mapa_uuid('prj-osg-p1'), '0523512c-f980-4236-8a7c-53e06c9c7a80',
   'P1.04 Qualificação dos Sócios',
   'Coleta dos documentos pessoais e patrimoniais de cada sócio (RG, CPF, CNH, certidão de nascimento, certidão de casamento com regime de bens, pacto antenupcial quando aplicável, comprovante de endereço, documentos de cônjuges/companheiros e de filhos/herdeiros). Monta o WP de Qualificação (Nome, Nacionalidade, Estado Civil, Regime de Bens, Filiação, Profissão, Endereço). Inclui a Planilha de Capital Social, somando por sócio o valor contábil que cada um leva à integralização.',
   '1x por projeto', 'Média', 'discovery', 4,
   'WP de Qualificação dos Sócios com dados completos de cada PF + Planilha de Capital Social somada por sócio',
   NULL, NOW(), NOW()),

  -- P2 — Societária (8)
  (mapa_uuid('prc-osg-p2-01'), mapa_uuid('prj-osg-p2'), '0523512c-f980-4236-8a7c-53e06c9c7a80',
   'P2.01 Constituição da Agro',
   'Constituição da PJ Agro (LTDA, operacional) que receberá os imóveis. Os sócios iniciais são as PFs e o capital social inicial é a soma do valor contábil dos imóveis a integralizar. O objeto social é fechado em atividade agro/rural para preservar a imunidade de ITBI. Trabalho em modelo Word, com revisão por três pessoas (assistente, revisor com checklist e líder sênior) e registro na Junta Comercial em cadeia com a constituição da Participações.',
   '1x por projeto', 'Alta', 'discovery', 1,
   'Contrato Social Agro registrado na Junta Comercial, CNPJ e NIRE ativos',
   NULL, NOW(), NOW()),
  (mapa_uuid('prc-osg-p2-02'), mapa_uuid('prj-osg-p2'), '0523512c-f980-4236-8a7c-53e06c9c7a80',
   'P2.02 Constituição da Participações',
   'Constituição da PJ Participações (LTDA, controladora) que recebe apenas cotas, não imóveis. Cotistas são as PFs no momento da constituição. Objeto social distinto da Agro (gestão de participações), por isso é trabalho separado, mas elaborado em conjunto e com registro simultâneo na Junta Comercial.',
   '1x por projeto', 'Alta', 'discovery', 2,
   'Contrato Social Participações registrado na Junta Comercial, CNPJ e NIRE ativos',
   NULL, NOW(), NOW()),
  (mapa_uuid('prc-osg-p2-03'), mapa_uuid('prj-osg-p2'), '0523512c-f980-4236-8a7c-53e06c9c7a80',
   'P2.03 Holdings Individuais',
   'Constituição das holdings individuais (LTDA) por sócio, acima da Participações, quando o organograma aprovado pelo cliente prevê isolamento patrimonial individual. A PSA constitui todas as PJs do organograma aprovado pelo cliente (raro o cliente já possuir holdings prontas). Estrutura típica não tem holdings individuais; projetos maiores têm uma holding por sócio.',
   '0-N por projeto', 'Média', 'discovery', 3,
   'N contratos sociais de holdings individuais constituídos e registrados na Junta Comercial (1 por sócio, conforme organograma aprovado)',
   NULL, NOW(), NOW()),
  (mapa_uuid('prc-osg-p2-04'), mapa_uuid('prj-osg-p2'), '0523512c-f980-4236-8a7c-53e06c9c7a80',
   'P2.04 AC Integralização Agro (cláusula 5ª)',
   'Alteração contratual da Agro que efetiva a integralização dos imóveis de 1º momento. Aumenta o capital social e lista os imóveis com limites e confrontações na cláusula 5ª. Registrada simultaneamente na Junta com a Cessão de Cotas (P2.05). Após o registro, é dever do cliente atualizar cada matrícula no cartório do respectivo imóvel, pagando ITBI.',
   '1x por projeto + N na cascata', 'Alta', 'discovery', 4,
   'AC da Agro com cláusula 5ª alterada, registrada na Junta Comercial',
   NULL, NOW(), NOW()),
  (mapa_uuid('prc-osg-p2-05'), mapa_uuid('prj-osg-p2'), '0523512c-f980-4236-8a7c-53e06c9c7a80',
   'P2.05 AC Cessão de Cotas (concentração na Participações)',
   'Alteração contratual que transfere a totalidade das cotas da Agro das PFs para a PJ Participações (concentração de cotas na controladora). Movimento sem mudança de capital social — apenas troca de sócios, refletida na cláusula de composição societária do contrato da Agro. Registrada simultaneamente com a AC Integralização (P2.04) na Junta.',
   '1x por projeto + N na cascata', 'Alta', 'discovery', 5,
   'AC com a cessão das cotas da Agro para a Participações (nova composição societária), registrada na Junta',
   NULL, NOW(), NOW()),
  (mapa_uuid('prc-osg-p2-06'), mapa_uuid('prj-osg-p2'), '0523512c-f980-4236-8a7c-53e06c9c7a80',
   'P2.06 AC Imóvel Adicional (2º momento)',
   'Alteração contratual adicional na Agro quando um imóvel de 2º momento tem a pendência regularizada pelo cliente, ou quando o cliente adquire novo imóvel durante ou após o projeto. Diferente da P2.04 porque o capital social já existe e apenas aumenta. Recorrente ao longo dos anos, sobrevive ao encerramento oficial do projeto.',
   '0-N por projeto, recorrente', 'Média', 'discovery', 6,
   'AC da Agro integralizando imóvel adicional, com novo aumento de capital, registrada na Junta',
   NULL, NOW(), NOW()),
  (mapa_uuid('prc-osg-p2-07'), mapa_uuid('prj-osg-p2'), '0523512c-f980-4236-8a7c-53e06c9c7a80',
   'P2.07 Reorganização Societária (Cisão · Fusão · Incorporação)',
   'Caso especial que sai do fluxo padrão das alterações contratuais. Regido pela Lei 6.404/76, exige protocolo e justificação, ata de reunião de sócios da sociedade cindenda e laudo de avaliação. Resulta em alterações contratuais das sociedades envolvidas registradas na Junta.',
   '0-N por projeto', 'Alta', 'discovery', 7,
   'Reorganização concluída: protocolo e justificação aprovados, laudo de avaliação emitido e alterações contratuais das sociedades envolvidas registradas na Junta',
   NULL, NOW(), NOW()),
  (mapa_uuid('prc-osg-p2-08'), mapa_uuid('prj-osg-p2'), '0523512c-f980-4236-8a7c-53e06c9c7a80',
   'P2.08 AC por Exigência Cartorial',
   'Alteração contratual reativa a nota devolutiva do cartório quando a matrícula transferida apresenta erro de descrição (tipicamente limite ou confrontação). Pode ocorrer anos após o encerramento oficial do projeto, ao tentar atualizar a matrícula no cartório.',
   '0-N por projeto', 'Média', 'discovery', 8,
   'AC ajustando a descrição da matrícula, registrada na Junta, exigência sanada no cartório',
   NULL, NOW(), NOW()),

  -- P3 — Agrários (5)
  (mapa_uuid('prc-osg-p3-01'), mapa_uuid('prj-osg-p3'), '0523512c-f980-4236-8a7c-53e06c9c7a80',
   'P3.01 Planejamento Tributário Rural',
   'Estudo tributário transversal executado pela área Fiscal, que define o percentual da parceria (tipicamente 20/80, terra nua) e o regime de exploração (incluindo opção de Funrural). A OSG atua como ponte com o cliente: disponibiliza a planilha gerencial de exploração desde o início do projeto e repassa documentos e dúvidas. O resultado é gatilho para finalizar o Contrato de Parceria (P3.03).',
   '1x por projeto', 'Média', 'discovery', 1,
   'Relatório do Fiscal definindo o percentual da parceria, o regime de exploração rural, a opção de Funrural e os cenários tributários',
   NULL, NOW(), NOW()),
  (mapa_uuid('prc-osg-p3-02'), mapa_uuid('prj-osg-p3'), '0523512c-f980-4236-8a7c-53e06c9c7a80',
   'P3.02 Distrato de Arrendamento Pré-existente',
   'Rescisão de contrato de arrendamento pré-existente quando o cliente vinha de estrutura de arrendamento, antes de configurar a nova relação via parceria. Elabora o contrato de distrato e registra em cartório. Caso raro, pois a maioria dos clientes explora na pessoa física sem arrendamento.',
   '0-N por projeto', 'Média', 'discovery', 2,
   'Contrato de distrato do arrendamento pré-existente registrado em cartório',
   NULL, NOW(), NOW()),
  (mapa_uuid('prc-osg-p3-03'), mapa_uuid('prj-osg-p3'), '0523512c-f980-4236-8a7c-53e06c9c7a80',
   'P3.03 Contrato de Parceria Rural',
   'Contrato agrário principal entre a PJ Agro (parceiro-outorgante, dona dos imóveis após a integralização) e as PFs da família (parceiros-outorgados), com base na Lei 4.504/64 (Estatuto da Terra). O percentual é definido pelo Planejamento Tributário Rural (P3.01). Inclui anexo que copia os limites e confrontações da matrícula, troca o proprietário para a PJ, remove o valor contábil e adiciona os hectares efetivamente explorados (planilha preenchida pelo cliente). Elaborado em paralelo aos contratos sociais e registrado em cartório após o registro da Agro na Junta.',
   '1x por projeto', 'Alta', 'discovery', 3,
   'Contrato de parceria rural registrado em cartório, com anexo (descrição da matrícula + hectares explorados)',
   NULL, NOW(), NOW()),
  (mapa_uuid('prc-osg-p3-04'), mapa_uuid('prj-osg-p3'), '0523512c-f980-4236-8a7c-53e06c9c7a80',
   'P3.04 Contrato de Composse',
   'Contrato complementar entre as PFs (parceiros-outorgados) que regula como o grupo divide entre si os 80% da parceria. Baseado no art. 1.199 do Código Civil, faz remissão ao contrato de parceria como instrumento principal. Na maioria dos casos é pro indiviso (todos exploram tudo, sem demarcar áreas). Quando há área arrendada de terceiros que entra na exploração, ela também é tratada na composse. Registrado em cartório.',
   '1x por projeto', 'Média', 'discovery', 4,
   'Contrato de composse registrado em cartório, com anexo (descrição da matrícula + hectares) e remetendo à parceria como instrumento principal',
   NULL, NOW(), NOW()),
  (mapa_uuid('prc-osg-p3-05'), mapa_uuid('prj-osg-p3'), '0523512c-f980-4236-8a7c-53e06c9c7a80',
   'P3.05 Termo de Encerramento de Safra',
   'Fechamento do ciclo agrícola. Documento elaborado ao fim da safra para formalizar o encerramento dos efeitos do contrato de parceria/composse no período. Registrado em cartório quando aplicável.',
   'Sazonal / recorrente', 'Baixa', 'discovery', 5,
   'Termo de encerramento de safra elaborado e registrado',
   NULL, NOW(), NOW()),

  -- P4 — Sucessão (4)
  (mapa_uuid('prc-osg-p4-01'), mapa_uuid('prj-osg-p4'), '0523512c-f980-4236-8a7c-53e06c9c7a80',
   'P4.01 Planejamento Tributário ITCMD',
   'Cálculo da base do ITCMD sobre as cotas a doar em três cenários (valor contábil, valor de ITR e valor de mercado), executado pela área Fiscal. A OSG atua como ponte com o cliente, abre a demanda e disponibiliza a planilha de cotas. Em paralelo, calcula a divisão da legítima e da parte disponível.',
   '1x por projeto', 'Alta', 'discovery', 1,
   'Relatório de ITCMD com três cenários (contábil, ITR e mercado)',
   NULL, NOW(), NOW()),
  (mapa_uuid('prc-osg-p4-02'), mapa_uuid('prj-osg-p4'), '0523512c-f980-4236-8a7c-53e06c9c7a80',
   'P4.02 Apresentação Final de Sucessão',
   'Apresentação ao cliente com os três cenários de ITCMD consolidados, já com a estrutura societária e patrimonial finalizada. O cliente decide se segue ou não com a doação e qual cenário adota como base. Reunião dedicada, que pode envolver participação da família e desdobrar em múltiplas agendas.',
   '1x por projeto', 'Média', 'discovery', 2,
   'Apresentação com cenários de ITCMD; decisão do cliente sobre o cenário escolhido formalizada',
   NULL, NOW(), NOW()),
  (mapa_uuid('prc-osg-p4-03'), mapa_uuid('prj-osg-p4'), '0523512c-f980-4236-8a7c-53e06c9c7a80',
   'P4.03 Doação + AC Reflexo (unificado)',
   'Elaboração do instrumento de doação das cotas da Participações dos fundadores para os herdeiros, tipicamente em partes iguais, com cláusulas restritivas (incomunicabilidade, impenhorabilidade, inalienabilidade) e reserva de usufruto quando aplicável. Cliente recolhe o ITCMD via contabilidade dele. A alteração contratual reflexo da doação (Participações) é elaborada de forma complementar e averbada simultaneamente na Junta após a quitação do ITCMD. Em alguns projetos a doação é condicionada à assinatura prévia do Acordo de Quotistas.',
   '1x por projeto', 'Alta', 'discovery', 3,
   'Instrumento de doação assinado + AC da Participações refletindo a nova composição societária registrada na Junta + ITCMD quitado',
   NULL, NOW(), NOW()),
  (mapa_uuid('prc-osg-p4-04'), mapa_uuid('prj-osg-p4'), '0523512c-f980-4236-8a7c-53e06c9c7a80',
   'P4.04 Testamento (alternativa à doação)',
   'Alternativa à doação em vida quando o cliente opta por não doar. A PSA elabora a minuta do testamento, disponibiliza ao cliente para aprovação e leva ao cartório de notas, indicando a lavratura do testamento. O fluxo cartorial é distinto da doação e não passa pela Junta Comercial.',
   '0-1x por projeto', 'Média', 'discovery', 4,
   'Testamento lavrado em cartório de notas e registrado na central de testamentos',
   NULL, NOW(), NOW()),

  -- P5 — Governança (6) — roda em paralelo aos demais pilares
  (mapa_uuid('prc-osg-p5-01'), mapa_uuid('prj-osg-p5'), '0523512c-f980-4236-8a7c-53e06c9c7a80',
   'P5.01 Diagnóstico de Governança',
   'Diagnóstico de governança familiar via entrevistas individuais com os familiares sócios. O cliente responde a um rol de perguntas padrão que orienta a estruturação da profissionalização da gestão da família. É o gatilho dos demais documentos do pilar de governança. Inclui identificação da qualidade que une os sócios, do organograma macro da empresa e dos interesses profissionais dos envolvidos.',
   '1x por projeto', 'Média', 'discovery', 1,
   'Respostas do cliente ao questionário de governança consolidadas (diagnóstico de governança familiar)',
   NULL, NOW(), NOW()),
  (mapa_uuid('prc-osg-p5-02'), mapa_uuid('prj-osg-p5'), '0523512c-f980-4236-8a7c-53e06c9c7a80',
   'P5.02 Acordo de Quotistas',
   'Documento Word que disciplina como os sócios decidem entre si (quotas e transferência, eventos pessoais, saída e exclusão, não-concorrência, governança e disposições gerais). Menos padronizado que os contratos do P2: parte de um modelo-base e de uma biblioteca de cláusulas, preenchido conforme as respostas do cliente ao questionário. Em alguns projetos é cláusula vinculante para a doação do P4 (a doação só ocorre se o Acordo estiver assinado).',
   '1x por projeto', 'Alta', 'discovery', 2,
   'Acordo de Quotistas assinado',
   NULL, NOW(), NOW()),
  (mapa_uuid('prc-osg-p5-03'), mapa_uuid('prj-osg-p5'), '0523512c-f980-4236-8a7c-53e06c9c7a80',
   'P5.03 Protocolo de Remuneração',
   'Documento que estabelece regras de remuneração e benefícios de sócios e administradores por persona (diretores, sucessores, gestores familiares). Baseia-se em uma planilha Excel checklist de categorias de benefícios e em questionário; o cliente estipula a remuneração conforme o mercado ou o que julga sensato. O documento Word é gerado a partir de um arquivo de referência canônico.',
   '1x por projeto', 'Alta', 'discovery', 3,
   'Protocolo de Remuneração (planilha preenchida + documento Word assinado)',
   NULL, NOW(), NOW()),
  (mapa_uuid('prc-osg-p5-04'), mapa_uuid('prj-osg-p5'), '0523512c-f980-4236-8a7c-53e06c9c7a80',
   'P5.04 Matriz de Alçadas',
   'Planilha que define até onde cada pessoa pode decidir e o que cada nível aprova (por exemplo, um diretor pode executar compra de imóvel até certo valor; acima disso, decide o conselho ou a reunião de sócios). É documento estrutural com ciclo de aprovação próprio e seu conteúdo reflete no contrato social.',
   '1x por projeto', 'Média', 'discovery', 4,
   'Planilha de matriz de alçadas (quem aprova o quê) aprovada pelo cliente',
   NULL, NOW(), NOW()),
  (mapa_uuid('prc-osg-p5-05'), mapa_uuid('prj-osg-p5'), '0523512c-f980-4236-8a7c-53e06c9c7a80',
   'P5.05 Regimento Interno do Conselho',
   'Documento elaborado apenas quando o cliente decide formar conselho de administração (depende do porte). Diferente dos demais documentos de governança, não parte de um rol de perguntas padrão em branco. Estabelece as regras de funcionamento do conselho.',
   'Condicional (0-1x por projeto)', 'Média', 'discovery', 5,
   'Regimento Interno do Conselho aprovado',
   NULL, NOW(), NOW()),
  (mapa_uuid('prc-osg-p5-06'), mapa_uuid('prj-osg-p5'), '0523512c-f980-4236-8a7c-53e06c9c7a80',
   'P5.06 AC Reflexo da Governança (Participações)',
   'Alteração do contrato social da Participações para formalizar a estrutura de governança quando o cliente forma conselho de administração: ao haver conselho, mexe-se na administração (passa a constar conselho de administração e diretoria), exigindo alterar o contrato social. Em algumas Juntas Comerciais exige especificar cláusula a cláusula. Registrada na Junta. Ocorre somente se o conselho for formado.',
   'Condicional (0-1x por projeto)', 'Alta', 'discovery', 6,
   'Alteração contratual formalizando conselho e diretoria registrada na Junta Comercial',
   NULL, NOW(), NOW()),

  -- P6 — Gestão (6)
  (mapa_uuid('prc-osg-p6-01'), mapa_uuid('prj-osg-p6'), '0523512c-f980-4236-8a7c-53e06c9c7a80',
   'P6.01 Solicitações Preliminares',
   'Memorando de documentos solicitado ao cliente para abrir o projeto. Alinha o escopo com a gerência, dispara a coleta documental e controla o retorno do cliente. Os documentos recebidos são guardados no Docbox. Insumos previstos: IR, matrículas, CCIR, IPTU, escritura, documentos pessoais (RG, CPF, certidões), hectares explorados, definição de sede, administrador, percentuais de exploração e regras de divisão.',
   '1x por projeto', 'Baixa', 'discovery', 1,
   'Lista de documentos solicitada ao cliente, com checklist de retorno',
   NULL, NOW(), NOW()),
  (mapa_uuid('prc-osg-p6-02'), mapa_uuid('prj-osg-p6'), '0523512c-f980-4236-8a7c-53e06c9c7a80',
   'P6.02 Kickoff / Entrevista Preliminar',
   'Reunião inicial com o cliente para captar expectativas, identificar riscos eminentes do projeto e definir os líderes interno e externo. Também levanta a qualificação inicial dos sócios e a participação societária. A saída alimenta os pilares P1, P4 e P5.',
   '1x por projeto', 'Média', 'discovery', 2,
   'Ata de kickoff com expectativas do cliente, riscos eminentes e identificação dos líderes interno e externo',
   NULL, NOW(), NOW()),
  (mapa_uuid('prc-osg-p6-03'), mapa_uuid('prj-osg-p6'), '0523512c-f980-4236-8a7c-53e06c9c7a80',
   'P6.03 Apresentação do Projeto',
   'Apresentação ao cliente da estrutura proposta, conduzida após o DP estar pronto e o esboço da estrutura societária estar montado. O cliente aprova a estrutura proposta antes da formalização do projeto. Inclui o esboço da legítima disponível (visão preliminar da sucessão).',
   '1x por projeto', 'Média', 'discovery', 3,
   'PPT com a estrutura proposta (organograma e esboço da legítima) apresentado e aprovado pelo cliente',
   NULL, NOW(), NOW()),
  (mapa_uuid('prc-osg-p6-04'), mapa_uuid('prj-osg-p6'), '0523512c-f980-4236-8a7c-53e06c9c7a80',
   'P6.04 Formalização do Projeto',
   'Elaboração do projeto de sucessão empresarial e submissão à aprovação do cliente, com a assinatura do contrato PSA × cliente. É o "go" formal do projeto; sem essa formalização, o trabalho não passa de diagnóstico.',
   '1x por projeto', 'Média', 'discovery', 4,
   'Projeto de sucessão empresarial aprovado pelo cliente e contrato PSA × cliente assinado',
   NULL, NOW(), NOW()),
  (mapa_uuid('prc-osg-p6-05'), mapa_uuid('prj-osg-p6'), '0523512c-f980-4236-8a7c-53e06c9c7a80',
   'P6.05 Acompanhamento',
   'Gestão recorrente do andamento do projeto: atualização de status com o cliente, controle de prazos, reuniões internas de sprint, orientação das equipes ao longo dos pilares, suporte a notas devolutivas de cartório e suporte tributário pós-implementação. Captura o overhead de gestão e coordenação.',
   'Recorrente ao longo do projeto', 'Média', 'discovery', 5,
   'Atualizações de status com o cliente, controle de prazos e reuniões internas de sprint conduzidas',
   NULL, NOW(), NOW()),
  (mapa_uuid('prc-osg-p6-06'), mapa_uuid('prj-osg-p6'), '0523512c-f980-4236-8a7c-53e06c9c7a80',
   'P6.06 Finalização do Projeto',
   'Fechamento do projeto: diagnóstico flash verificando se os objetivos foram alcançados e se há novos riscos, elaboração do relatório final e apresentação/entrega ao cliente (handover).',
   '1x por projeto', 'Média', 'discovery', 6,
   'Diagnóstico flash, relatório final do projeto e entrega/handover ao cliente',
   NULL, NOW(), NOW());

-- ============================================================================
-- 9. PROCESS_STAGES — etapas AS-IS detalhadas (≈ 170 etapas)
-- Scenario: 'AS-IS' (TO-BE virá em remensuração futura)
-- Convenção slug: etp-osg-p1-01-01 (etapa 1 do processo P1.01)
-- ============================================================================
INSERT INTO public.process_stages
  (id, scenario, process_id, name, description, execution, stage_order, created_at, updated_at)
VALUES
  -- ============ P1.01 DP Inicial ============
  (mapa_uuid('etp-osg-p1-01-01'), 'AS-IS', mapa_uuid('prc-osg-p1-01'),
   'Solicitar e coletar documentos do cliente',
   'Pede IR, matrículas, CCIR, ITR, IPTU, escrituras/CCV, CAR quando houver. Cliente envia por e-mail, WhatsApp ou Docbox.',
   'Atendimento + Docbox', 1, NOW(), NOW()),
  (mapa_uuid('etp-osg-p1-01-02'), 'AS-IS', mapa_uuid('prc-osg-p1-01'),
   'Extrair valor contábil da declaração de IR',
   'Localiza cada imóvel na declaração de IR pela denominação ou número da matrícula e extrai o valor contábil declarado. Quando não há remissão direta na declaração, faz-se o link pelo nome do imóvel.',
   'Manual em Excel + PDF do IR', 2, NOW(), NOW()),
  (mapa_uuid('etp-osg-p1-01-03'), 'AS-IS', mapa_uuid('prc-osg-p1-01'),
   'Ler matrícula ponta a ponta (averbações)',
   'Leitura manual da matrícula do início ao fim para detectar impedimentos (hipoteca, penhora, alienação fiduciária, bloqueio judicial) e verificar se ônus anteriores foram cancelados em averbações posteriores.',
   'Manual', 3, NOW(), NOW()),
  (mapa_uuid('etp-osg-p1-01-04'), 'AS-IS', mapa_uuid('prc-osg-p1-01'),
   'Registrar titularidade (propriedade de fato × direito)',
   'Por matrícula, distinguir propriedade de fato e de direito. Princípio da continuidade impede transferir o que não está em nome do titular.',
   'Manual em DP', 4, NOW(), NOW()),
  (mapa_uuid('etp-osg-p1-01-05'), 'AS-IS', mapa_uuid('prc-osg-p1-01'),
   'Extrair códigos de CCIR e IPTU (conferência cruzada)',
   'Coleta dos códigos para checar identidade entre IR, matrícula e cadastro rural/urbano.',
   'Manual', 5, NOW(), NOW()),
  (mapa_uuid('etp-osg-p1-01-06'), 'AS-IS', mapa_uuid('prc-osg-p1-01'),
   'Cruzar matrícula × IR e preencher o DP',
   'Combina dados: tipo, denominação, matrícula, área, valor contábil, valor ITR/IPTU, valor de mercado se houver.',
   'Manual em Excel', 6, NOW(), NOW()),
  (mapa_uuid('etp-osg-p1-01-07'), 'AS-IS', mapa_uuid('prc-osg-p1-01'),
   'Tratar matrícula desatualizada integralizando pelos direitos',
   'Quando a matrícula não reflete o proprietário atual, integraliza-se pelos direitos da escritura pública de compra e venda ou pelo contrato particular de compra e venda, com remissão à matrícula.',
   'Manual', 7, NOW(), NOW()),
  (mapa_uuid('etp-osg-p1-01-08'), 'AS-IS', mapa_uuid('prc-osg-p1-01'),
   'Classificar coluna integraliza e marcar pendências',
   'Cada imóvel recebe a classificação na coluna integraliza (sim, 1º momento, 2º momento ou não), conforme a presença ou ausência de ônus. Pendências (documentos faltantes, ônus não sanados, divergências entre fontes) são sinalizadas com observação no DP.',
   'Manual em Excel', 8, NOW(), NOW()),

  -- ============ P1.02 Atualização do DP ============
  (mapa_uuid('etp-osg-p1-02-01'), 'AS-IS', mapa_uuid('prc-osg-p1-02'),
   'Receber matrícula atualizada/nova área',
   'Cliente envia matrícula atualizada (ônus sanado), nova área adquirida ou novos documentos via e-mail/Docbox.',
   'Inbox', 1, NOW(), NOW()),
  (mapa_uuid('etp-osg-p1-02-02'), 'AS-IS', mapa_uuid('prc-osg-p1-02'),
   'Reabrir o DP e atualizar campos',
   'Atualiza tipo do bem, área, valor contábil, denominação na linha do imóvel afetado.',
   'Manual em Excel', 2, NOW(), NOW()),
  (mapa_uuid('etp-osg-p1-02-03'), 'AS-IS', mapa_uuid('prc-osg-p1-02'),
   'Reclassificar coluna integraliza',
   'Tipicamente promove imóveis de 2º momento → 1º momento conforme regularização.',
   'Manual', 3, NOW(), NOW()),
  (mapa_uuid('etp-osg-p1-02-04'), 'AS-IS', mapa_uuid('prc-osg-p1-02'),
   'Abrir demandas de AC subsequentes',
   'Gatilho da cascata: dispara P2.06 (AC Imóvel Adicional) + recálculo de Capital Social + revisão de anexos agrários.',
   'Manual (e-mail/Slack)', 4, NOW(), NOW()),
  (mapa_uuid('etp-osg-p1-02-05'), 'AS-IS', mapa_uuid('prc-osg-p1-02'),
   'Sinalizar impactos cascata aos pilares',
   'Comunica ao societário, agrário e governança que campos derivados (cláusula 5ª, anexos) precisam ser revisitados.',
   'Manual', 5, NOW(), NOW()),

  -- ============ P1.03 Digitação de Matrícula ============
  (mapa_uuid('etp-osg-p1-03-01'), 'AS-IS', mapa_uuid('prc-osg-p1-03'),
   'Buscar matrícula no SIGEF ou ler PDF',
   'Quando há georreferenciamento, busca no SIGEF; caso contrário, lê o PDF enviado pelo cliente.',
   'SIGEF + PDF', 1, NOW(), NOW()),
  (mapa_uuid('etp-osg-p1-03-02'), 'AS-IS', mapa_uuid('prc-osg-p1-03'),
   'Extrair área, denominação, localização, proprietário',
   'Coleta campos básicos para o WP padrão.',
   'Manual em Word', 2, NOW(), NOW()),
  (mapa_uuid('etp-osg-p1-03-03'), 'AS-IS', mapa_uuid('prc-osg-p1-03'),
   'Transcrever limites e confrontações',
   'Cópia caractere-por-caractere para WP Word. Erro aqui (um grau vira O) gera exigência cartorial e dispara P2.08.',
   'Manual em Word', 3, NOW(), NOW()),
  (mapa_uuid('etp-osg-p1-03-04'), 'AS-IS', mapa_uuid('prc-osg-p1-03'),
   'Validar cruzamento com DP',
   'Confere se área e denominação batem com o DP.',
   'Manual', 4, NOW(), NOW()),

  -- ============ P1.04 Qualificação dos Sócios ============
  (mapa_uuid('etp-osg-p1-04-01'), 'AS-IS', mapa_uuid('prc-osg-p1-04'),
   'Coletar documentos pessoais',
   'RG, CPF, CNH, certidão nascimento, certidão casamento (com regime de bens), pacto antenupcial se aplicável, comprovante endereço, docs cônjuges/companheiros, docs filhos/herdeiros quando entram em sucessão.',
   'Atendimento + Docbox', 1, NOW(), NOW()),
  (mapa_uuid('etp-osg-p1-04-02'), 'AS-IS', mapa_uuid('prc-osg-p1-04'),
   'Montar WP de Qualificação',
   'Nome, Nacionalidade, Profissão, Estado Civil, Regime de Bens, Data Nascimento, Filiação, RG/CPF, Endereço, Relação de parentesco. Modelo Word padrão.',
   'Manual em Word', 2, NOW(), NOW()),
  (mapa_uuid('etp-osg-p1-04-03'), 'AS-IS', mapa_uuid('prc-osg-p1-04'),
   'Montar Planilha de Capital Social',
   'Excel manual que soma, por sócio, o que cada um leva à integralização (cruzando DP com a coluna integraliza). Considera também lucros, AFAC e aportes em moeda corrente quando aplicável. Demanda atenção ao arredondamento por casas decimais.',
   'Manual em Excel', 3, NOW(), NOW()),
  (mapa_uuid('etp-osg-p1-04-04'), 'AS-IS', mapa_uuid('prc-osg-p1-04'),
   'Revisão sênior',
   'Sênior revisa qualificação e cálculo do capital social. Fecha gap de revisão.',
   'Manual', 4, NOW(), NOW()),

  -- ============ P2.01 Constituição da Agro ============
  (mapa_uuid('etp-osg-p2-01-01'), 'AS-IS', mapa_uuid('prc-osg-p2-01'),
   'Verificar estado do contrato',
   'Confere DP, WP Sócios, Capital Social e definição de sede/objeto/administrador.',
   'Manual', 1, NOW(), NOW()),
  (mapa_uuid('etp-osg-p2-01-02'), 'AS-IS', mapa_uuid('prc-osg-p2-01'),
   'Elaborar minuta CS Agro',
   'Preâmbulo + cláusula 5ª (capital = soma integralizada). Objeto agro/rural para preservar imunidade ITBI.',
   'Manual em Word', 2, NOW(), NOW()),
  (mapa_uuid('etp-osg-p2-01-03'), 'AS-IS', mapa_uuid('prc-osg-p2-01'),
   'Checklist do revisor',
   'Revisor aplica checklist padronizado.',
   'Manual em Word', 3, NOW(), NOW()),
  (mapa_uuid('etp-osg-p2-01-04'), 'AS-IS', mapa_uuid('prc-osg-p2-01'),
   'Revisão sênior (líder do projeto)',
   'Líder sênior faz revisão final. "Elaboramos pouco, revisamos muito."',
   'Manual em Word', 4, NOW(), NOW()),
  (mapa_uuid('etp-osg-p2-01-05'), 'AS-IS', mapa_uuid('prc-osg-p2-01'),
   'Aprovação do cliente',
   'Cliente lê e aprova. Pode pedir explicação de cláusula.',
   'E-mail / gov.br', 5, NOW(), NOW()),
  (mapa_uuid('etp-osg-p2-01-06'), 'AS-IS', mapa_uuid('prc-osg-p2-01'),
   'Registro Junta Comercial',
   'Registro simultâneo com Participações. Gera CNPJ + NIRE.',
   'Junta Comercial', 6, NOW(), NOW()),

  -- ============ P2.02 Constituição da Participações ============
  (mapa_uuid('etp-osg-p2-02-01'), 'AS-IS', mapa_uuid('prc-osg-p2-02'),
   'Verificar estado do contrato',
   'Confere DP, WP Sócios, Capital Social Participações (em moeda, sem imóveis).',
   'Manual', 1, NOW(), NOW()),
  (mapa_uuid('etp-osg-p2-02-02'), 'AS-IS', mapa_uuid('prc-osg-p2-02'),
   'Elaborar minuta CS Participações',
   'Capital em moeda (sem imóveis). Objeto: gestão de participações (controladora). Sócios = PFs.',
   'Manual em Word', 2, NOW(), NOW()),
  (mapa_uuid('etp-osg-p2-02-03'), 'AS-IS', mapa_uuid('prc-osg-p2-02'),
   'Checklist do revisor',
   'Revisor aplica checklist.',
   'Manual em Word', 3, NOW(), NOW()),
  (mapa_uuid('etp-osg-p2-02-04'), 'AS-IS', mapa_uuid('prc-osg-p2-02'),
   'Revisão sênior',
   'Líder sênior revisa.',
   'Manual em Word', 4, NOW(), NOW()),
  (mapa_uuid('etp-osg-p2-02-05'), 'AS-IS', mapa_uuid('prc-osg-p2-02'),
   'Aprovação do cliente',
   'Cliente aprova.',
   'E-mail / gov.br', 5, NOW(), NOW()),
  (mapa_uuid('etp-osg-p2-02-06'), 'AS-IS', mapa_uuid('prc-osg-p2-02'),
   'Registro Junta Comercial',
   'Registro simultâneo com a Agro.',
   'Junta Comercial', 6, NOW(), NOW()),

  -- ============ P2.03 Holdings Individuais ============
  (mapa_uuid('etp-osg-p2-03-01'), 'AS-IS', mapa_uuid('prc-osg-p2-03'),
   'Verificar estado do contrato',
   'Confere se há holding pré-existente do cliente ou se constitui nova.',
   'Manual', 1, NOW(), NOW()),
  (mapa_uuid('etp-osg-p2-03-02'), 'AS-IS', mapa_uuid('prc-osg-p2-03'),
   'Elaborar minuta CS Holding',
   'Um contrato por sócio (volume).',
   'Manual em Word', 2, NOW(), NOW()),
  (mapa_uuid('etp-osg-p2-03-03'), 'AS-IS', mapa_uuid('prc-osg-p2-03'),
   'Checklist do revisor',
   'Aplicado por holding.',
   'Manual em Word', 3, NOW(), NOW()),
  (mapa_uuid('etp-osg-p2-03-04'), 'AS-IS', mapa_uuid('prc-osg-p2-03'),
   'Revisão sênior',
   'Líder sênior revisa.',
   'Manual em Word', 4, NOW(), NOW()),
  (mapa_uuid('etp-osg-p2-03-05'), 'AS-IS', mapa_uuid('prc-osg-p2-03'),
   'Aprovação do cliente',
   'Cliente aprova.',
   'E-mail / gov.br', 5, NOW(), NOW()),
  (mapa_uuid('etp-osg-p2-03-06'), 'AS-IS', mapa_uuid('prc-osg-p2-03'),
   'Registro Junta Comercial',
   'N holdings registradas.',
   'Junta Comercial', 6, NOW(), NOW()),

  -- ============ P2.04 AC Integralização Agro ============
  (mapa_uuid('etp-osg-p2-04-01'), 'AS-IS', mapa_uuid('prc-osg-p2-04'),
   'Verificar estado do contrato',
   'Estado atual da Agro + DP integralizando.',
   'Manual', 1, NOW(), NOW()),
  (mapa_uuid('etp-osg-p2-04-02'), 'AS-IS', mapa_uuid('prc-osg-p2-04'),
   'Elaborar minuta AC (cláusula 5ª)',
   'Aumento de capital social. Lista de imóveis com limites/confrontações copiados do WP Matrícula.',
   'Manual em Word', 2, NOW(), NOW()),
  (mapa_uuid('etp-osg-p2-04-03'), 'AS-IS', mapa_uuid('prc-osg-p2-04'),
   'Checklist do revisor',
   'Aplicado pelo revisor.',
   'Manual em Word', 3, NOW(), NOW()),
  (mapa_uuid('etp-osg-p2-04-04'), 'AS-IS', mapa_uuid('prc-osg-p2-04'),
   'Revisão sênior',
   'Sênior revisa cláusula 5ª e descrição dos imóveis.',
   'Manual em Word', 4, NOW(), NOW()),
  (mapa_uuid('etp-osg-p2-04-05'), 'AS-IS', mapa_uuid('prc-osg-p2-04'),
   'Registro Junta Comercial',
   'Registro simultâneo com P2.05 (cessão).',
   'Junta Comercial', 5, NOW(), NOW()),
  (mapa_uuid('etp-osg-p2-04-06'), 'AS-IS', mapa_uuid('prc-osg-p2-04'),
   'Cliente atualiza matrículas no cartório',
   'Responsabilidade do cliente. Custo ITBI. 1-2 anos no mínimo. PSA acompanha via P6.05.',
   'Cliente + Cartório', 6, NOW(), NOW()),

  -- ============ P2.05 AC Cessão de Cotas ============
  (mapa_uuid('etp-osg-p2-05-01'), 'AS-IS', mapa_uuid('prc-osg-p2-05'),
   'Verificar estado do contrato',
   'Confere se Participações está registrada e cotas das PFs na Agro.',
   'Manual', 1, NOW(), NOW()),
  (mapa_uuid('etp-osg-p2-05-02'), 'AS-IS', mapa_uuid('prc-osg-p2-05'),
   'Elaborar minuta AC (cláusula 7ª — cessão)',
   'Cessão de cotas PF → PJ Participações. Sem mudança de capital.',
   'Manual em Word', 2, NOW(), NOW()),
  (mapa_uuid('etp-osg-p2-05-03'), 'AS-IS', mapa_uuid('prc-osg-p2-05'),
   'Checklist do revisor',
   'Aplicado pelo revisor.',
   'Manual em Word', 3, NOW(), NOW()),
  (mapa_uuid('etp-osg-p2-05-04'), 'AS-IS', mapa_uuid('prc-osg-p2-05'),
   'Revisão sênior',
   'Sênior revisa cessão.',
   'Manual em Word', 4, NOW(), NOW()),
  (mapa_uuid('etp-osg-p2-05-05'), 'AS-IS', mapa_uuid('prc-osg-p2-05'),
   'Registro Junta Comercial',
   'Registro simultâneo com P2.04.',
   'Junta Comercial', 5, NOW(), NOW()),

  -- ============ P2.06 AC Imóvel Adicional ============
  (mapa_uuid('etp-osg-p2-06-01'), 'AS-IS', mapa_uuid('prc-osg-p2-06'),
   'Verificar estado do contrato',
   'Cliente avisa por e-mail/Docbox sobre nova matrícula ou ônus sanado.',
   'Manual', 1, NOW(), NOW()),
  (mapa_uuid('etp-osg-p2-06-02'), 'AS-IS', mapa_uuid('prc-osg-p2-06'),
   'Elaborar minuta AC 2º momento',
   'Capital social já existe; apenas aumenta com novo imóvel. Lista descrição do imóvel.',
   'Manual em Word', 2, NOW(), NOW()),
  (mapa_uuid('etp-osg-p2-06-03'), 'AS-IS', mapa_uuid('prc-osg-p2-06'),
   'Checklist do revisor',
   'Aplicado pelo revisor.',
   'Manual em Word', 3, NOW(), NOW()),
  (mapa_uuid('etp-osg-p2-06-04'), 'AS-IS', mapa_uuid('prc-osg-p2-06'),
   'Revisão sênior',
   'Sênior revisa.',
   'Manual em Word', 4, NOW(), NOW()),
  (mapa_uuid('etp-osg-p2-06-05'), 'AS-IS', mapa_uuid('prc-osg-p2-06'),
   'Registro Junta Comercial',
   'Registro da AC adicional.',
   'Junta Comercial', 5, NOW(), NOW()),

  -- ============ P2.07 Reorganização Societária ============
  (mapa_uuid('etp-osg-p2-07-01'), 'AS-IS', mapa_uuid('prc-osg-p2-07'),
   'Elaborar Protocolo e Justificação',
   'Lei 6.404/76 — protocolo + justificação econômica.',
   'Manual em Word', 1, NOW(), NOW()),
  (mapa_uuid('etp-osg-p2-07-02'), 'AS-IS', mapa_uuid('prc-osg-p2-07'),
   'Ata de Reunião de Sócios (sociedade cindenda)',
   'Aprovação dos sócios da operação.',
   'Manual em Word', 2, NOW(), NOW()),
  (mapa_uuid('etp-osg-p2-07-03'), 'AS-IS', mapa_uuid('prc-osg-p2-07'),
   'Elaborar laudo de avaliação',
   'Avaliação do patrimônio cindido/incorporado.',
   'Externo / PSA', 3, NOW(), NOW()),
  (mapa_uuid('etp-osg-p2-07-04'), 'AS-IS', mapa_uuid('prc-osg-p2-07'),
   'AC das sociedades envolvidas',
   'Alterações contratuais refletindo a operação em cada PJ.',
   'Manual em Word', 4, NOW(), NOW()),
  (mapa_uuid('etp-osg-p2-07-05'), 'AS-IS', mapa_uuid('prc-osg-p2-07'),
   'Checklist do revisor',
   'Revisor aplica checklist.',
   'Manual', 5, NOW(), NOW()),
  (mapa_uuid('etp-osg-p2-07-06'), 'AS-IS', mapa_uuid('prc-osg-p2-07'),
   'Revisão sênior',
   'Líder sênior revisa.',
   'Manual', 6, NOW(), NOW()),
  (mapa_uuid('etp-osg-p2-07-07'), 'AS-IS', mapa_uuid('prc-osg-p2-07'),
   'Registro Junta Comercial',
   'Registro da reorganização.',
   'Junta Comercial', 7, NOW(), NOW()),

  -- ============ P2.08 AC por Exigência Cartorial ============
  (mapa_uuid('etp-osg-p2-08-01'), 'AS-IS', mapa_uuid('prc-osg-p2-08'),
   'Receber nota devolutiva do cliente',
   'Cliente repassa nota devolutiva do cartório por e-mail/WhatsApp.',
   'Inbox', 1, NOW(), NOW()),
  (mapa_uuid('etp-osg-p2-08-02'), 'AS-IS', mapa_uuid('prc-osg-p2-08'),
   'Identificar diferença na descrição',
   'Compara descrição na AC com matrícula original. Erro de limites/confrontações na maioria das vezes.',
   'Manual', 2, NOW(), NOW()),
  (mapa_uuid('etp-osg-p2-08-03'), 'AS-IS', mapa_uuid('prc-osg-p2-08'),
   'Elaborar AC ajustando descrição',
   'Nova AC apenas para corrigir a descrição.',
   'Manual em Word', 3, NOW(), NOW()),
  (mapa_uuid('etp-osg-p2-08-04'), 'AS-IS', mapa_uuid('prc-osg-p2-08'),
   'Checklist do revisor',
   'Aplicado pelo revisor.',
   'Manual', 4, NOW(), NOW()),
  (mapa_uuid('etp-osg-p2-08-05'), 'AS-IS', mapa_uuid('prc-osg-p2-08'),
   'Revisão sênior',
   'Sênior revisa correção.',
   'Manual', 5, NOW(), NOW()),
  (mapa_uuid('etp-osg-p2-08-06'), 'AS-IS', mapa_uuid('prc-osg-p2-08'),
   'Registro Junta Comercial',
   'Registro da AC corretiva.',
   'Junta Comercial', 6, NOW(), NOW()),

  -- ============ P3.01 Planejamento Tributário Rural ============
  (mapa_uuid('etp-osg-p3-01-01'), 'AS-IS', mapa_uuid('prc-osg-p3-01'),
   'Disponibilizar Planilha de Exploração ao cliente',
   'OSG envia planilha gerencial para o cliente preencher (hectares e exploradores por imóvel).',
   'E-mail', 1, NOW(), NOW()),
  (mapa_uuid('etp-osg-p3-01-02'), 'AS-IS', mapa_uuid('prc-osg-p3-01'),
   'Receber planilha preenchida e repassar ao Fiscal',
   'Repasse via Slack ou e-mail à área Fiscal.',
   'Manual', 2, NOW(), NOW()),
  (mapa_uuid('etp-osg-p3-01-03'), 'AS-IS', mapa_uuid('prc-osg-p3-01'),
   'Aguardar diagnóstico tributário do Fiscal',
   'Fiscal calcula cenários e define percentual (tipicamente 20/80, terra nua).',
   'Externo (Fiscal)', 3, NOW(), NOW()),
  (mapa_uuid('etp-osg-p3-01-04'), 'AS-IS', mapa_uuid('prc-osg-p3-01'),
   'Validar com Gestor do Projeto',
   'Gestor confirma o cenário escolhido com o cliente.',
   'Reunião', 4, NOW(), NOW()),
  (mapa_uuid('etp-osg-p3-01-05'), 'AS-IS', mapa_uuid('prc-osg-p3-01'),
   'Definir % parceria',
   'Resultado dispara fechamento de P3.03 (Parceria).',
   'Manual', 5, NOW(), NOW()),

  -- ============ P3.02 Distrato de Arrendamento ============
  (mapa_uuid('etp-osg-p3-02-01'), 'AS-IS', mapa_uuid('prc-osg-p3-02'),
   'Elaborar minuta de distrato',
   'Rescisão do arrendamento pré-existente. Caso raro.',
   'Manual em Word', 1, NOW(), NOW()),
  (mapa_uuid('etp-osg-p3-02-02'), 'AS-IS', mapa_uuid('prc-osg-p3-02'),
   'Checklist do revisor',
   'Aplicado pelo revisor.',
   'Manual', 2, NOW(), NOW()),
  (mapa_uuid('etp-osg-p3-02-03'), 'AS-IS', mapa_uuid('prc-osg-p3-02'),
   'Revisão sênior',
   'Sênior revisa.',
   'Manual', 3, NOW(), NOW()),
  (mapa_uuid('etp-osg-p3-02-04'), 'AS-IS', mapa_uuid('prc-osg-p3-02'),
   'Registro em cartório',
   'Distrato registrado em cartório.',
   'Cartório', 4, NOW(), NOW()),

  -- ============ P3.03 Parceria Rural ============
  (mapa_uuid('etp-osg-p3-03-01'), 'AS-IS', mapa_uuid('prc-osg-p3-03'),
   'Receber planilha de exploração do cliente',
   'Hectares por imóvel + explorador. Pode diferir da área da matrícula (reserva legal + APP).',
   'Inbox', 1, NOW(), NOW()),
  (mapa_uuid('etp-osg-p3-03-02'), 'AS-IS', mapa_uuid('prc-osg-p3-03'),
   'Montar anexo (matrícula × hectares × %)',
   'Copia descrição da matrícula do CS Agro, troca proprietário PF→PJ, remove valor contábil, adiciona hectares e %.',
   'Manual em Word', 2, NOW(), NOW()),
  (mapa_uuid('etp-osg-p3-03-03'), 'AS-IS', mapa_uuid('prc-osg-p3-03'),
   'Elaborar minuta da Parceria',
   'PJ Agro outorgante × PFs outorgadas. Lei 4.504/64.',
   'Manual em Word', 3, NOW(), NOW()),
  (mapa_uuid('etp-osg-p3-03-04'), 'AS-IS', mapa_uuid('prc-osg-p3-03'),
   'Checklist do revisor',
   'Aplicado pelo revisor.',
   'Manual', 4, NOW(), NOW()),
  (mapa_uuid('etp-osg-p3-03-05'), 'AS-IS', mapa_uuid('prc-osg-p3-03'),
   'Revisão sênior',
   'Sênior revisa.',
   'Manual', 5, NOW(), NOW()),
  (mapa_uuid('etp-osg-p3-03-06'), 'AS-IS', mapa_uuid('prc-osg-p3-03'),
   'Assinatura',
   'Cliente assina via gov.br ou presencialmente.',
   'gov.br', 6, NOW(), NOW()),
  (mapa_uuid('etp-osg-p3-03-07'), 'AS-IS', mapa_uuid('prc-osg-p3-03'),
   'Registro em cartório',
   'Parceria registrada em cartório.',
   'Cartório', 7, NOW(), NOW()),

  -- ============ P3.04 Composse ============
  (mapa_uuid('etp-osg-p3-04-01'), 'AS-IS', mapa_uuid('prc-osg-p3-04'),
   'Elaborar minuta de Composse',
   'Define como o grupo de PFs divide entre si os 80% da parceria. Na maioria dos casos é pro indiviso (todos exploram tudo, sem demarcar áreas individuais).',
   'Manual em Word', 1, NOW(), NOW()),
  (mapa_uuid('etp-osg-p3-04-02'), 'AS-IS', mapa_uuid('prc-osg-p3-04'),
   'Checklist do revisor',
   'Aplicado pelo revisor.',
   'Manual', 2, NOW(), NOW()),
  (mapa_uuid('etp-osg-p3-04-03'), 'AS-IS', mapa_uuid('prc-osg-p3-04'),
   'Revisão sênior',
   'Sênior revisa.',
   'Manual', 3, NOW(), NOW()),
  (mapa_uuid('etp-osg-p3-04-04'), 'AS-IS', mapa_uuid('prc-osg-p3-04'),
   'Assinatura',
   'Todas as PFs assinam. Pode travar por agenda de sócios viajando.',
   'gov.br', 4, NOW(), NOW()),
  (mapa_uuid('etp-osg-p3-04-05'), 'AS-IS', mapa_uuid('prc-osg-p3-04'),
   'Registro em cartório',
   'Composse registrada em cartório.',
   'Cartório', 5, NOW(), NOW()),

  -- ============ P3.05 Encerramento Safra ============
  (mapa_uuid('etp-osg-p3-05-01'), 'AS-IS', mapa_uuid('prc-osg-p3-05'),
   'Elaborar Termo de Encerramento de Safra',
   'Documento padrão de encerramento de ciclo agrícola.',
   'Manual em Word', 1, NOW(), NOW()),
  (mapa_uuid('etp-osg-p3-05-02'), 'AS-IS', mapa_uuid('prc-osg-p3-05'),
   'Checklist do revisor',
   'Aplicado pelo revisor.',
   'Manual', 2, NOW(), NOW()),
  (mapa_uuid('etp-osg-p3-05-03'), 'AS-IS', mapa_uuid('prc-osg-p3-05'),
   'Registro em cartório',
   'Termo arquivado/registrado.',
   'Cartório', 3, NOW(), NOW()),

  -- ============ P4.01 Planejamento Tributário ITCMD ============
  (mapa_uuid('etp-osg-p4-01-01'), 'AS-IS', mapa_uuid('prc-osg-p4-01'),
   'Abrir demanda à área Fiscal',
   'OSG abre demanda no canal interno; disponibiliza planilha de cotas.',
   'Slack / e-mail', 1, NOW(), NOW()),
  (mapa_uuid('etp-osg-p4-01-02'), 'AS-IS', mapa_uuid('prc-osg-p4-01'),
   'Calcular cenário contábil',
   'Valor histórico do IR.',
   'Externo (Fiscal)', 2, NOW(), NOW()),
  (mapa_uuid('etp-osg-p4-01-03'), 'AS-IS', mapa_uuid('prc-osg-p4-01'),
   'Calcular cenário ITR',
   'Base ITR.',
   'Externo (Fiscal)', 3, NOW(), NOW()),
  (mapa_uuid('etp-osg-p4-01-04'), 'AS-IS', mapa_uuid('prc-osg-p4-01'),
   'Calcular cenário de mercado',
   'Valor de mercado. Reforma 2027 passa base contábil → mercado e invalida cenários antigos.',
   'Externo (Fiscal)', 4, NOW(), NOW()),
  (mapa_uuid('etp-osg-p4-01-05'), 'AS-IS', mapa_uuid('prc-osg-p4-01'),
   'Validar com Gestor',
   'Gestor consolida com OSG.',
   'Reunião', 5, NOW(), NOW()),

  -- ============ P4.02 Apresentação Final de Sucessão ============
  (mapa_uuid('etp-osg-p4-02-01'), 'AS-IS', mapa_uuid('prc-osg-p4-02'),
   'Consolidar 3 cenários ITCMD em PPTX',
   'Apresentação com cenários contábil/ITR/mercado e impacto no patrimônio.',
   'Manual em PowerPoint', 1, NOW(), NOW()),
  (mapa_uuid('etp-osg-p4-02-02'), 'AS-IS', mapa_uuid('prc-osg-p4-02'),
   'Apresentar ao cliente',
   'Reunião dedicada. Cliente pode trazer família. Múltiplas agendas.',
   'Reunião', 2, NOW(), NOW()),
  (mapa_uuid('etp-osg-p4-02-03'), 'AS-IS', mapa_uuid('prc-osg-p4-02'),
   'Cliente escolhe cenário',
   'Decisão formalizada para gatilho de P4.03.',
   'Manual', 3, NOW(), NOW()),

  -- ============ P4.03 Doação + AC Reflexo ============
  (mapa_uuid('etp-osg-p4-03-01'), 'AS-IS', mapa_uuid('prc-osg-p4-03'),
   'Elaborar minuta do instrumento de doação',
   'Cotas Participações dos fundadores para herdeiros (partes iguais).',
   'Manual em Word', 1, NOW(), NOW()),
  (mapa_uuid('etp-osg-p4-03-02'), 'AS-IS', mapa_uuid('prc-osg-p4-03'),
   'Definir reserva de usufruto',
   'Sim/não conforme desejo da família.',
   'Manual', 2, NOW(), NOW()),
  (mapa_uuid('etp-osg-p4-03-03'), 'AS-IS', mapa_uuid('prc-osg-p4-03'),
   'Inserir cláusulas restritivas',
   'Incomunicabilidade, impenhorabilidade, inalienabilidade.',
   'Manual', 3, NOW(), NOW()),
  (mapa_uuid('etp-osg-p4-03-04'), 'AS-IS', mapa_uuid('prc-osg-p4-03'),
   'Cliente recolhe ITCMD',
   'Contabilidade do cliente emite guia e quita. PSA acompanha. Pode travar indefinidamente (caso 2022 em discussão judicial).',
   'Cliente + Contabilidade', 4, NOW(), NOW()),
  (mapa_uuid('etp-osg-p4-03-05'), 'AS-IS', mapa_uuid('prc-osg-p4-03'),
   'Elaborar AC Participações reflexo (cláusula 7ª)',
   'AC reflete a doação na composição societária.',
   'Manual em Word', 5, NOW(), NOW()),
  (mapa_uuid('etp-osg-p4-03-06'), 'AS-IS', mapa_uuid('prc-osg-p4-03'),
   'Checklist do revisor',
   'Aplicado pelo revisor.',
   'Manual', 6, NOW(), NOW()),
  (mapa_uuid('etp-osg-p4-03-07'), 'AS-IS', mapa_uuid('prc-osg-p4-03'),
   'Revisão sênior',
   'Sênior revisa.',
   'Manual', 7, NOW(), NOW()),
  (mapa_uuid('etp-osg-p4-03-08'), 'AS-IS', mapa_uuid('prc-osg-p4-03'),
   'Assinatura',
   'Doadores e donatários assinam via gov.br.',
   'gov.br', 8, NOW(), NOW()),
  (mapa_uuid('etp-osg-p4-03-09'), 'AS-IS', mapa_uuid('prc-osg-p4-03'),
   'Averbação simultânea na Junta (doação + AC)',
   'AC reflexo + remissão ao instrumento de doação registradas em conjunto.',
   'Junta Comercial', 9, NOW(), NOW()),

  -- ============ P4.04 Testamento ============
  (mapa_uuid('etp-osg-p4-04-01'), 'AS-IS', mapa_uuid('prc-osg-p4-04'),
   'Elaborar minuta do testamento',
   'Minuta conforme decisão do cliente.',
   'Manual em Word', 1, NOW(), NOW()),
  (mapa_uuid('etp-osg-p4-04-02'), 'AS-IS', mapa_uuid('prc-osg-p4-04'),
   'Lavratura em cartório de notas',
   'Cartório de notas lavra. PSA indica e acompanha.',
   'Cartório', 2, NOW(), NOW()),
  (mapa_uuid('etp-osg-p4-04-03'), 'AS-IS', mapa_uuid('prc-osg-p4-04'),
   'Registro na central de testamentos',
   'Documento entra na central, ficando disponível para futura sucessão.',
   'Cartório', 3, NOW(), NOW()),

  -- ============ P5.01 Diagnóstico de Governança ============
  (mapa_uuid('etp-osg-p5-01-01'), 'AS-IS', mapa_uuid('prc-osg-p5-01'),
   'Entrevistar individualmente os familiares sócios',
   'Aplica roteiro de entrevista padrão a cada familiar sócio, individualmente.',
   'Reunião', 1, NOW(), NOW()),
  (mapa_uuid('etp-osg-p5-01-02'), 'AS-IS', mapa_uuid('prc-osg-p5-01'),
   'Identificar qualidade que une os sócios',
   'Mapeamento da identidade familiar.',
   'Manual', 2, NOW(), NOW()),
  (mapa_uuid('etp-osg-p5-01-03'), 'AS-IS', mapa_uuid('prc-osg-p5-01'),
   'Identificar organograma macro da empresa',
   'Mapa de pessoas-chave.',
   'Manual em PowerPoint', 3, NOW(), NOW()),
  (mapa_uuid('etp-osg-p5-01-04'), 'AS-IS', mapa_uuid('prc-osg-p5-01'),
   'Identificar interesses profissionais',
   'Diagnóstico para futura matriz de alçadas e protocolo de remuneração.',
   'Manual', 4, NOW(), NOW()),

  -- ============ P5.02 Acordo de Quotistas ============
  (mapa_uuid('etp-osg-p5-02-01'), 'AS-IS', mapa_uuid('prc-osg-p5-02'),
   'Debater acordos familiares',
   'Família discute regras de convivência.',
   'Reunião', 1, NOW(), NOW()),
  (mapa_uuid('etp-osg-p5-02-02'), 'AS-IS', mapa_uuid('prc-osg-p5-02'),
   'Debater acordos societários',
   'Sócios discutem quotas, eventos pessoais, saída, não-concorrência.',
   'Reunião', 2, NOW(), NOW()),
  (mapa_uuid('etp-osg-p5-02-03'), 'AS-IS', mapa_uuid('prc-osg-p5-02'),
   'Elaborar minuta',
   'Modelo-base + biblioteca de cláusulas. Variantes 2025 (5-D, 19-B, 20-B, 20-C).',
   'Manual em Word', 3, NOW(), NOW()),
  (mapa_uuid('etp-osg-p5-02-04'), 'AS-IS', mapa_uuid('prc-osg-p5-02'),
   'Checklist do revisor',
   'Aplicado pelo revisor.',
   'Manual', 4, NOW(), NOW()),
  (mapa_uuid('etp-osg-p5-02-05'), 'AS-IS', mapa_uuid('prc-osg-p5-02'),
   'Revisão sênior',
   'Sênior revisa a minuta. Mudanças no modelo-base passam pela aprovação da gerência.',
   'Manual', 5, NOW(), NOW()),
  (mapa_uuid('etp-osg-p5-02-06'), 'AS-IS', mapa_uuid('prc-osg-p5-02'),
   'Reunião com cliente para discutir cláusulas',
   'Pode travar agenda 2 meses por discussão.',
   'Reunião', 6, NOW(), NOW()),
  (mapa_uuid('etp-osg-p5-02-07'), 'AS-IS', mapa_uuid('prc-osg-p5-02'),
   'Assinatura',
   'Sócios assinam. Em alguns projetos é pré-condição para doação P4.',
   'gov.br', 7, NOW(), NOW()),

  -- ============ P5.03 Protocolo de Remuneração ============
  (mapa_uuid('etp-osg-p5-03-01'), 'AS-IS', mapa_uuid('prc-osg-p5-03'),
   'Aplicar questionário em Excel ao cliente',
   'Checklist de categorias de benefícios.',
   'Manual em Excel', 1, NOW(), NOW()),
  (mapa_uuid('etp-osg-p5-03-02'), 'AS-IS', mapa_uuid('prc-osg-p5-03'),
   'Definir remuneração de administradores/gestores',
   'Cliente estipula conforme mercado.',
   'Manual', 2, NOW(), NOW()),
  (mapa_uuid('etp-osg-p5-03-03'), 'AS-IS', mapa_uuid('prc-osg-p5-03'),
   'Estabelecer valor mínimo de distribuição de lucros',
   'Política mínima de dividendos.',
   'Manual', 3, NOW(), NOW()),
  (mapa_uuid('etp-osg-p5-03-04'), 'AS-IS', mapa_uuid('prc-osg-p5-03'),
   'Elaborar Protocolo',
   'Word gerado a partir de arquivo de referência canônico.',
   'Manual em Word', 4, NOW(), NOW()),
  (mapa_uuid('etp-osg-p5-03-05'), 'AS-IS', mapa_uuid('prc-osg-p5-03'),
   'Aprovação do cliente',
   'Cliente assina.',
   'gov.br', 5, NOW(), NOW()),

  -- ============ P5.04 Matriz de Alçadas ============
  (mapa_uuid('etp-osg-p5-04-01'), 'AS-IS', mapa_uuid('prc-osg-p5-04'),
   'Definir alçadas dos administradores',
   'Até onde cada pessoa pode decidir (R$ por tipo de operação).',
   'Manual em Excel', 1, NOW(), NOW()),
  (mapa_uuid('etp-osg-p5-04-02'), 'AS-IS', mapa_uuid('prc-osg-p5-04'),
   'Definir Secretário do Conselho',
   'Se houver conselho.',
   'Manual', 2, NOW(), NOW()),
  (mapa_uuid('etp-osg-p5-04-03'), 'AS-IS', mapa_uuid('prc-osg-p5-04'),
   'Elaborar organograma e DAC dos diretores',
   'Descrição/Análise de Cargo dos diretores.',
   'Manual em Word/Excel', 3, NOW(), NOW()),
  (mapa_uuid('etp-osg-p5-04-04'), 'AS-IS', mapa_uuid('prc-osg-p5-04'),
   'Aprovação do cliente',
   'Cliente aprova matriz.',
   'gov.br', 4, NOW(), NOW()),

  -- ============ P5.05 Regimento Interno do Conselho ============
  (mapa_uuid('etp-osg-p5-05-01'), 'AS-IS', mapa_uuid('prc-osg-p5-05'),
   'Elaborar regimento interno',
   'Sem rol de perguntas padrão (único da governança). Mais artesanal.',
   'Manual em Word', 1, NOW(), NOW()),
  (mapa_uuid('etp-osg-p5-05-02'), 'AS-IS', mapa_uuid('prc-osg-p5-05'),
   'Aprovação do conselho',
   'Conselho aprova regimento.',
   'Reunião', 2, NOW(), NOW()),

  -- ============ P5.06 AC Reflexo da Governança ============
  (mapa_uuid('etp-osg-p5-06-01'), 'AS-IS', mapa_uuid('prc-osg-p5-06'),
   'Verificar estado do contrato',
   'Avalia se contrato atual permite ajuste pontual ou exige reescrita completa.',
   'Manual', 1, NOW(), NOW()),
  (mapa_uuid('etp-osg-p5-06-02'), 'AS-IS', mapa_uuid('prc-osg-p5-06'),
   'Elaborar minuta AC reflexo conselho',
   'AC inclui conselho e diretoria na administração. Em algumas juntas: cláusula a cláusula (20+ cláusulas).',
   'Manual em Word', 2, NOW(), NOW()),
  (mapa_uuid('etp-osg-p5-06-03'), 'AS-IS', mapa_uuid('prc-osg-p5-06'),
   'Checklist do revisor',
   'Aplicado pelo revisor.',
   'Manual', 3, NOW(), NOW()),
  (mapa_uuid('etp-osg-p5-06-04'), 'AS-IS', mapa_uuid('prc-osg-p5-06'),
   'Revisão sênior',
   'Sênior revisa.',
   'Manual', 4, NOW(), NOW()),
  (mapa_uuid('etp-osg-p5-06-05'), 'AS-IS', mapa_uuid('prc-osg-p5-06'),
   'Registro Junta Comercial',
   'AC registrada.',
   'Junta Comercial', 5, NOW(), NOW()),

  -- ============ P6.01 Solicitações Preliminares ============
  (mapa_uuid('etp-osg-p6-01-01'), 'AS-IS', mapa_uuid('prc-osg-p6-01'),
   'Alinhar escopo do projeto com a gerência',
   'Define perfil do cliente e escopo desejado.',
   'Reunião', 1, NOW(), NOW()),
  (mapa_uuid('etp-osg-p6-01-02'), 'AS-IS', mapa_uuid('prc-osg-p6-01'),
   'Solicitar memorando de documentos preliminares',
   'Pedido informal por e-mail/WhatsApp. Sem rastreio estruturado.',
   'E-mail/WhatsApp', 2, NOW(), NOW()),
  (mapa_uuid('etp-osg-p6-01-03'), 'AS-IS', mapa_uuid('prc-osg-p6-01'),
   'Validar recebimento dos 11 insumos',
   'IR · Matrícula · CCIR · IPTU · Escritura · Doc PF (RG/CPF/certidões) · Hectares · Sede · Administrador · % exploração · Regras de divisão.',
   'Docbox + Manual', 3, NOW(), NOW()),

  -- ============ P6.02 Kickoff ============
  (mapa_uuid('etp-osg-p6-02-01'), 'AS-IS', mapa_uuid('prc-osg-p6-02'),
   'Identificar expectativas do cliente',
   'Mapeamento de objetivos e medo do cliente.',
   'Reunião', 1, NOW(), NOW()),
  (mapa_uuid('etp-osg-p6-02-02'), 'AS-IS', mapa_uuid('prc-osg-p6-02'),
   'Identificar riscos eminentes',
   'Pontos críticos do projeto (impedimentos, conflitos familiares, ITCMD).',
   'Manual', 2, NOW(), NOW()),
  (mapa_uuid('etp-osg-p6-02-03'), 'AS-IS', mapa_uuid('prc-osg-p6-02'),
   'Identificar líder interno e externo',
   'Define ponto único de contato.',
   'Manual', 3, NOW(), NOW()),
  (mapa_uuid('etp-osg-p6-02-04'), 'AS-IS', mapa_uuid('prc-osg-p6-02'),
   'Coleta inicial de qualificação',
   'Dados básicos das PFs envolvidas.',
   'Manual', 4, NOW(), NOW()),

  -- ============ P6.03 Apresentação do Projeto ============
  (mapa_uuid('etp-osg-p6-03-01'), 'AS-IS', mapa_uuid('prc-osg-p6-03'),
   'Elaborar PPTX com a estrutura proposta',
   'Após DP pronto e esboço societário.',
   'Manual em PowerPoint', 1, NOW(), NOW()),
  (mapa_uuid('etp-osg-p6-03-02'), 'AS-IS', mapa_uuid('prc-osg-p6-03'),
   'Apresentar organograma proposto',
   'Agro + Participações + Holdings (se houver).',
   'Reunião', 2, NOW(), NOW()),
  (mapa_uuid('etp-osg-p6-03-03'), 'AS-IS', mapa_uuid('prc-osg-p6-03'),
   'Incluir esboço da legítima disponível',
   'Inclui o esboço da legítima disponível para dar ao cliente uma visão preliminar da sucessão já na primeira reunião de tomada de decisão.',
   'Manual', 3, NOW(), NOW()),
  (mapa_uuid('etp-osg-p6-03-04'), 'AS-IS', mapa_uuid('prc-osg-p6-03'),
   'Cliente aprova estrutura',
   'Aprovação dispara formalização.',
   'Reunião', 4, NOW(), NOW()),

  -- ============ P6.04 Formalização do Projeto ============
  (mapa_uuid('etp-osg-p6-04-01'), 'AS-IS', mapa_uuid('prc-osg-p6-04'),
   'Elaborar projeto de sucessão empresarial',
   'Documento canônico de proposta consolidada (todos os pilares).',
   'Manual em Word', 1, NOW(), NOW()),
  (mapa_uuid('etp-osg-p6-04-02'), 'AS-IS', mapa_uuid('prc-osg-p6-04'),
   'Submeter à aprovação do cliente',
   'Cliente formaliza o aceite.',
   'gov.br', 2, NOW(), NOW()),
  (mapa_uuid('etp-osg-p6-04-03'), 'AS-IS', mapa_uuid('prc-osg-p6-04'),
   'Assinar contrato PSA × cliente',
   'Go formal do projeto.',
   'gov.br', 3, NOW(), NOW()),

  -- ============ P6.05 Acompanhamento ============
  (mapa_uuid('etp-osg-p6-05-01'), 'AS-IS', mapa_uuid('prc-osg-p6-05'),
   'Reuniões de status com cliente',
   'Cadência variável conforme a fase do projeto e o porte do cliente. Conduzida primariamente por e-mail e reuniões pontuais.',
   'Reunião / e-mail', 1, NOW(), NOW()),
  (mapa_uuid('etp-osg-p6-05-02'), 'AS-IS', mapa_uuid('prc-osg-p6-05'),
   'Cobrança ao cliente',
   'Pendências cobradas por e-mail/WhatsApp.',
   'E-mail/WhatsApp', 2, NOW(), NOW()),
  (mapa_uuid('etp-osg-p6-05-03'), 'AS-IS', mapa_uuid('prc-osg-p6-05'),
   'Suporte a notas devolutivas',
   'Quando cartório devolve, dispara P2.08.',
   'Manual', 3, NOW(), NOW()),
  (mapa_uuid('etp-osg-p6-05-04'), 'AS-IS', mapa_uuid('prc-osg-p6-05'),
   'Suporte tributário pós-implementação',
   'Dúvidas tributárias residuais (Fiscal envolvido).',
   'Slack/Reunião', 4, NOW(), NOW()),

  -- ============ P6.06 Finalização ============
  (mapa_uuid('etp-osg-p6-06-01'), 'AS-IS', mapa_uuid('prc-osg-p6-06'),
   'Realizar diagnóstico flash dos objetivos alcançados',
   'Confere o que foi/não foi integralizado e novos riscos.',
   'Manual em Word', 1, NOW(), NOW()),
  (mapa_uuid('etp-osg-p6-06-02'), 'AS-IS', mapa_uuid('prc-osg-p6-06'),
   'Elaborar relatório final',
   'Consolidação dos entregáveis.',
   'Manual em Word', 2, NOW(), NOW()),
  (mapa_uuid('etp-osg-p6-06-03'), 'AS-IS', mapa_uuid('prc-osg-p6-06'),
   'Apresentar/entregar relatório ao cliente',
   'Handover formal.',
   'Reunião', 3, NOW(), NOW());

COMMIT;
