-- 20260917140000_gov03_o_preco_da_opcao_nao_e_campo.sql
-- GOV-03: sai `opcao_compra_preco`, que nao escreve linha nenhuma no Acordo.
--
-- ESCRITA EM 17/09/2026. NAO APLICAR SEM O OK.
--
--
-- A REGRA, E ELA E A MESMA QUE DERRUBOU SEIS CAMPOS EM 15/09
--
-- Campo que nao vira frase no documento e campo que nao devia existir. Este nao
-- vira: nenhum dos 266 blocos o cita, e nao e esquecimento meu, e porque o
-- modelo nao tem lugar para ele.
--
--
-- O QUE EU MEDI, depois de errar a primeira leitura
--
-- Eu tinha dito ao Eduardo que o preco VARIAVA no acervo, e estava errado:
-- comparei frases DIFERENTES de documentos diferentes. Sao duas frases, e cada
-- uma e estavel:
--
--   Frase A, na definicao de OPCAO DE COMPRA (Clausula Primeira):
--     "o preco de cada QUOTA sera o preco atribuido neste ACORDO, para cada
--      hipotese que a OPCAO DE COMPRA for prevista, sendo que caso nao
--      especifique, sera considerado o VALOR DA QUOTA"
--     Identica em Horita, Perci, modelo e Via Fertil.
--
--   Frase B, no subscritor desistente:
--     "o preco de cada QUOTA objeto DA OPCAO DE COMPRA sera o maior dentre os
--      valores adquiridos atraves das seguintes metodologias: (i)... (ii)..."
--     Identica em Perci, modelo e AgroAlianca.
--
-- Nenhuma varia. O que varia DENTRO da frase B e a taxa de juros sobre o valor
-- subscrito, e essa ja e campo (`juros_valor_subscrito`), medida a parte: o
-- Perci escreve 1% num lugar e 0,50% no outro.
--
-- E a frase A ja diz o que fazer quando o cliente nao combina preco proprio:
-- "caso nao especifique, sera considerado o VALOR DA QUOTA". O modelo resolve
-- sozinho, sem campo.
--
--
-- O DADO QUE SE PERDE, e por que perder e o certo
--
-- Tres dos cinco acordos do sandbox tem valor escrito, todos de teste:
--
--   Abacaxi v1  "o VALOR DAS QUOTAS apurado na forma da Clausula Decima Nona"
--   Zamo v1/v2  "Valor patrimonial da quota apurado em balanco especial"
--
-- Nenhum desses textos sai no documento hoje, nem sairia: nao ha frase
-- esperando por eles. Mante-los e pior que perde-los, porque o consultor
-- responde achando que combinou o preco e o Acordo entrega outra coisa.
--
-- EM PRODUCAO nao ha nada a perder: zero acordos cadastrados.
--
--
-- O QUE FICA, e nao por descuido
--
-- `opcao_compra_quem` FICA e foi ligado em 17/09: esse varia de verdade, tres
-- redacoes em quatro acordos ("QUOTISTAS que sejam titulares da maioria das
-- QUOTAS" no modelo e no AgroAlianca, "demais QUOTISTAS" no Perci, "QUOTISTAS
-- e/ou seus curadores" no Horita), e agora escreve a frase 8.2.

ALTER TABLE public.acordo_quotistas
  DROP COLUMN IF EXISTS opcao_compra_preco;
